ALTER TABLE orders ADD COLUMN partner_id TEXT REFERENCES partners(id);
CREATE TABLE IF NOT EXISTS partners (
 id TEXT PRIMARY KEY, partner_code TEXT NOT NULL UNIQUE, legal_name TEXT NOT NULL, display_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, phone TEXT NOT NULL, id_last4 TEXT, company_name TEXT, tax_id TEXT,
 status TEXT NOT NULL CHECK(status IN ('applicant','pending_contract','active','suspended','terminated','rejected')), contract_status TEXT NOT NULL DEFAULT 'unsigned', contract_version TEXT, contract_signed_at TEXT,
 referral_code TEXT NOT NULL UNIQUE, total_valid_sales INTEGER NOT NULL DEFAULT 0, total_sales_amount REAL NOT NULL DEFAULT 0, password_hash TEXT, password_salt TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS contract_versions (id TEXT PRIMARY KEY, version TEXT NOT NULL UNIQUE, title TEXT NOT NULL, content_html TEXT NOT NULL, content_hash TEXT NOT NULL, effective_date TEXT NOT NULL, is_active INTEGER NOT NULL DEFAULT 0, requires_resign INTEGER NOT NULL DEFAULT 0, legal_review_required INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contract_signatures (id TEXT PRIMARY KEY, partner_id TEXT NOT NULL REFERENCES partners(id), contract_version_id TEXT NOT NULL REFERENCES contract_versions(id), legal_name TEXT NOT NULL, signed_at TEXT NOT NULL, ip_address TEXT, user_agent TEXT, contract_content_hash TEXT NOT NULL, signature_hash TEXT NOT NULL, pdf_hash TEXT, consent_version TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(partner_id,contract_version_id));
CREATE TABLE IF NOT EXISTS partner_invites (id TEXT PRIMARY KEY, partner_id TEXT NOT NULL REFERENCES partners(id), token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS partner_login_attempts (id TEXT PRIMARY KEY, email TEXT NOT NULL, attempted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, success INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS partner_leads (id TEXT PRIMARY KEY, partner_id TEXT NOT NULL REFERENCES partners(id), merchant_id TEXT REFERENCES merchants(id), lead_name TEXT NOT NULL, lead_phone TEXT, lead_email TEXT, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, converted_at TEXT);
CREATE TABLE IF NOT EXISTS partner_attribution_audits (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL REFERENCES partner_leads(id), previous_partner_id TEXT, new_partner_id TEXT NOT NULL REFERENCES partners(id), actor_id TEXT, reason TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS commissions (id TEXT PRIMARY KEY, partner_id TEXT NOT NULL REFERENCES partners(id), order_id TEXT NOT NULL REFERENCES orders(id), payment_id TEXT REFERENCES payments(id), commission_type TEXT NOT NULL CHECK(commission_type IN ('sales','service','adjustment')), base_amount REAL NOT NULL DEFAULT 0, service_bonus REAL NOT NULL DEFAULT 0, adjustment_amount REAL NOT NULL DEFAULT 0, final_amount REAL NOT NULL, tier INTEGER, status TEXT NOT NULL CHECK(status IN ('pending','confirmed','payable','paid','reversed','cancelled')), earned_at TEXT, confirmed_at TEXT, paid_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(partner_id,order_id,commission_type));
CREATE TABLE IF NOT EXISTS commission_adjustments (id TEXT PRIMARY KEY, commission_id TEXT NOT NULL REFERENCES commissions(id), reason TEXT NOT NULL, amount REAL NOT NULL, status TEXT NOT NULL DEFAULT 'confirmed', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settlements (id TEXT PRIMARY KEY, settlement_no TEXT NOT NULL UNIQUE, partner_id TEXT NOT NULL REFERENCES partners(id), period_start TEXT NOT NULL, period_end TEXT NOT NULL, gross_commission REAL NOT NULL DEFAULT 0, service_bonus REAL NOT NULL DEFAULT 0, refund_deduction REAL NOT NULL DEFAULT 0, other_adjustment REAL NOT NULL DEFAULT 0, net_payable REAL NOT NULL DEFAULT 0, status TEXT NOT NULL CHECK(status IN ('draft','approved','paid','cancelled')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, approved_at TEXT, paid_at TEXT);
CREATE TABLE IF NOT EXISTS settlement_items (id TEXT PRIMARY KEY, settlement_id TEXT NOT NULL REFERENCES settlements(id), commission_id TEXT NOT NULL REFERENCES commissions(id), amount REAL NOT NULL, UNIQUE(settlement_id,commission_id));
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_type TEXT NOT NULL, actor_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, metadata TEXT, ip_address TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_partner_leads_partner ON partner_leads(partner_id,created_at);
CREATE INDEX IF NOT EXISTS idx_commissions_partner ON commissions(partner_id,status);
CREATE INDEX IF NOT EXISTS idx_orders_partner ON orders(partner_id);
INSERT OR IGNORE INTO contract_versions (id,version,title,content_html,content_hash,effective_date,is_active,legal_review_required) VALUES ('contract_v1_0','v1.0','創百業智慧鏈業務承攬合作契約（法律審閱草稿）','<h1>創百業智慧鏈業務承攬合作契約 v1.0</h1><p>甲方：陳靈有限公司；乙方：線上申請之合作夥伴。</p><h2>合作性質</h2><p>本合作為獨立承攬／居間合作關係，非僱傭關係；夥伴自行安排合作方式，不設出勤、工時、排班或工作地點管理。</p><h2>報酬</h2><p>有效成交第 1～10 件每件 NT$1,000；第 11～60 件每件 NT$1,500；第 61～120 件每件 NT$2,000；第 121 件起每件 NT$3,000。採非追溯式級距。甲方得依實際輔導成果核准每案 0～NT$1,000 輔導獎金。</p><h2>成立、退款與扣回</h2><p>獎金以客戶全額繳清、案件有效歸屬、未取消且無有效退款為成立條件。退款或撤銷時，甲方得依約調整或扣回尚未結算及未來結算之獎金。</p><h2>商業規範</h2><p>夥伴應保密商業資訊，不得飛單、私下收款或不實推廣。競業、禁止招攬與違約責任條款於正式版本由甲方指定台灣執業律師審閱確認。</p><p><strong>LEGAL_REVIEW_REQUIRED：本版本為系統草稿，正式大規模使用前應完成台灣執業律師最終法律審閱。</strong></p>','draft','2026-08-21',1,1);
