PRAGMA foreign_keys=OFF;
DROP TRIGGER IF EXISTS trg_order_pricing_coupon_reservation;
DROP TRIGGER IF EXISTS trg_order_pricing_no_delete;
DROP TRIGGER IF EXISTS trg_order_pricing_no_update;
DROP TABLE IF EXISTS financing_outbound_clicks;
DROP TABLE IF EXISTS financing_audit_logs;
DROP TABLE IF EXISTS financing_referral_leads;
DROP TABLE IF EXISTS financing_referral_consents;
DROP TABLE IF EXISTS financing_products;
DROP TABLE IF EXISTS financing_partners;
DROP TABLE IF EXISTS merchant_delivery_clicks;
DROP TABLE IF EXISTS merchant_delivery_links;
DROP TABLE IF EXISTS merchant_order_payment_intents;
DROP TABLE IF EXISTS merchant_payment_integrations;
DROP TABLE IF EXISTS merchant_order_pricing;
DROP TABLE IF EXISTS merchant_coupon_redemptions;
DROP TABLE IF EXISTS merchant_member_coupons;
DROP TABLE IF EXISTS merchant_coupon_campaigns;
PRAGMA foreign_keys=ON;
