import { awardCommissionForOrder, reverseOrderCommission } from "./partner.js";
import { handleSettlementRequest } from "./settlements.js";
const METHODS = new Set(["card","atm","virtual_account","bank_transfer","line_pay","apple_pay","google_pay","e_wallet","convenience_store","cash","cheque","other"]);
const PAYMENT_STATUSES = new Set(["pending","paid","failed","cancelled","refunded","partially_refunded"]);
const PROVIDERS = new Set(["ecpay","newebpay","linepay","stripe"]);
const encoder = new TextEncoder();
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=UTF-8", ...headers } });
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const b64 = (value) => btoa(String.fromCharCode(...new Uint8Array(value))).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
const unb64 = (value) => Uint8Array.from(atob(value.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((value.length + 3) % 4)), (c) => c.charCodeAt(0));

async function sign(value, secret) { const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return b64(await crypto.subtle.sign("HMAC", key, encoder.encode(value))); }
async function sessionToken(env) { const payload = b64(encoder.encode(JSON.stringify({ exp: Date.now() + 8 * 3600_000, scope: "finance" }))); return `${payload}.${await sign(payload, env.FINANCE_SESSION_SECRET)}`; }
async function authorized(request, env) { const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, ""); if (!token || !env.FINANCE_SESSION_SECRET) return false; const [payload, signature] = token.split("."); if (!payload || signature !== await sign(payload, env.FINANCE_SESSION_SECRET)) return false; try { return JSON.parse(new TextDecoder().decode(unb64(payload))).exp > Date.now(); } catch { return false; } }
async function refreshOrder(db, orderId) { if (!orderId) return; const order = await db.prepare("SELECT amount_due FROM orders WHERE id = ?").bind(orderId).first(); if (!order) return; const paid = await db.prepare("SELECT COALESCE(SUM(gross_amount),0) total FROM payments WHERE order_id = ? AND status IN ('paid','partially_refunded','refunded')").bind(orderId).first(); const refunded = await db.prepare("SELECT COALESCE(SUM(r.amount),0) total FROM refunds r JOIN payments p ON p.id=r.payment_id WHERE p.order_id=? AND r.status='refunded'").bind(orderId).first(); const amount = Math.max(0, Number(paid.total) - Number(refunded.total)); const state = amount <= 0 ? "unpaid" : amount < Number(order.amount_due) ? "partial" : "paid"; await db.prepare("UPDATE orders SET amount_paid=?, payment_status=?, updated_at=? WHERE id=?").bind(amount, state, now(), orderId).run(); }
async function financeAudit(db, action, orderId, metadata) { await db.prepare("INSERT INTO audit_logs (id,actor_type,actor_id,action,entity_type,entity_id,metadata) VALUES (?,?,?,?,?,?,?)").bind(id("audit"), "admin", "finance", action, "order", orderId, JSON.stringify(metadata)).run(); }
function number(value) { const result = Number(value); return Number.isFinite(result) && result >= 0 ? result : null; }
async function body(request) { try { return await request.json(); } catch { return {}; } }
async function listPayments(db, url) { const where = []; const args = []; for (const [key, column] of [["merchant_id","p.merchant_id"],["status","p.status"],["payment_method","p.payment_method"],["source","p.source"],["provider","p.payment_provider"]]) if (url.searchParams.get(key)) { where.push(`${column}=?`); args.push(url.searchParams.get(key)); } if (url.searchParams.get("q")) { where.push("(p.payment_no LIKE ? OR m.name LIKE ? OR o.order_no LIKE ?)"); args.push(...Array(3).fill(`%${url.searchParams.get("q")}%`)); } const rows = await db.prepare(`SELECT p.*,m.name merchant_name,o.order_no,o.title order_title FROM payments p JOIN merchants m ON m.id=p.merchant_id LEFT JOIN orders o ON o.id=p.order_id ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY p.created_at DESC LIMIT 500`).bind(...args).all(); return rows.results; }
async function manualPayment(db, data) { const gross = number(data.amount); if (!data.merchant_id || gross === null || !METHODS.has(data.payment_method)) return { error: "invalid manual payment", status: 400 }; const merchant = await db.prepare("SELECT id FROM merchants WHERE id=?").bind(data.merchant_id).first(); if (!merchant) return { error: "merchant not found", status: 404 }; const fee = data.fee_amount === "" || data.fee_amount == null ? null : number(data.fee_amount); if (fee !== null && fee > gross) return { error: "invalid fee", status: 400 }; const status = data.status === "pending" ? "pending" : "paid"; const paymentId = id("pay"); const paymentNo = `PAY-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`; const timestamp = now(); await db.prepare("INSERT INTO payments (id,payment_no,merchant_id,order_id,gross_amount,fee_amount,net_amount,amount,currency,payment_method,payment_provider,status,paid_at,confirmed_at,source,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(paymentId,paymentNo,data.merchant_id,data.order_id || null,gross,fee, gross-(fee || 0),gross,data.currency || "TWD",data.payment_method,data.payment_provider || null,status,status === "paid" ? timestamp : null,status === "paid" ? timestamp : null,"manual",String(data.note || "").slice(0,500),timestamp,timestamp).run(); await refreshOrder(db, data.order_id); return { id: paymentId, payment_no: paymentNo }; }
async function summary(db) { const income = await db.prepare("SELECT COALESCE(SUM(gross_amount),0) gross,COALESCE(SUM(fee_amount),0) fees,COALESCE(SUM(net_amount),0) net,COUNT(*) count FROM payments WHERE status='paid' AND strftime('%Y-%m',paid_at)=strftime('%Y-%m','now')").first(); const refunds = await db.prepare("SELECT COALESCE(SUM(amount),0) total FROM refunds WHERE status='refunded' AND strftime('%Y-%m',refunded_at)=strftime('%Y-%m','now')").first(); const expenses = await db.prepare("SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE strftime('%Y-%m',date)=strftime('%Y-%m','now')").first(); const pending = await db.prepare("SELECT COALESCE(SUM(amount_due-amount_paid),0) total FROM orders WHERE payment_status IN ('unpaid','partial')").first(); const methods = await db.prepare("SELECT payment_method,COALESCE(SUM(gross_amount),0) total FROM payments WHERE status='paid' GROUP BY payment_method ORDER BY total DESC").all(); const merchants = await db.prepare("SELECT m.id,m.merchant_code,m.name,COALESCE(SUM(o.amount_due),0) amount_due,COALESCE(SUM(o.amount_paid),0) amount_paid FROM merchants m LEFT JOIN orders o ON o.merchant_id=m.id GROUP BY m.id ORDER BY amount_paid DESC").all(); return { month_gross:Number(income.gross)-Number(refunds.total), month_refunds:Number(refunds.total), month_fees:Number(income.fees), month_net:Number(income.net)-Number(refunds.total), pending:Number(pending.total), expenses:Number(expenses.total), profit:Number(income.net)-Number(refunds.total)-Number(expenses.total), payment_count:Number(income.count), methods:methods.results, merchants:merchants.results }; }
async function webhook(request, env, provider) { if (!PROVIDERS.has(provider)) return json({ error:"Unsupported provider" },404); const secret = env[`PAYMENT_${provider.toUpperCase()}_WEBHOOK_SECRET`]; if (!secret) return json({ error:"Provider adapter is not configured" },503); const raw = await request.text(); const given = request.headers.get("x-payment-signature") || ""; if (given !== await sign(raw, secret)) return json({ error:"Invalid webhook signature" },401); return json({ error:"Provider adapter verification must be implemented before accepting payments" },501); }
export async function handleFinanceRequest(request, env, url, cors, adminSession = null) {
  if (!env.FINANCE_DB) return json({ error:"Finance database is unavailable" },503,cors);
  if (url.pathname.startsWith("/api/payments/webhook/")) return webhook(request,env,url.pathname.split("/").pop());
  if (url.pathname === "/api/finance/auth/login") return json({error:"舊版財務登入已停用，請使用正式管理員登入。"},410,cors);
  if (!adminSession && !(await authorized(request,env))) return json({error:"Finance administrator authentication required"},401,cors);
  const db=env.FINANCE_DB;
  if (url.pathname.startsWith("/api/finance/settlement-profiles/") || url.pathname.startsWith("/api/finance/settlement-settings/") || url.pathname.startsWith("/api/finance/settlements")) {
    return (await handleSettlementRequest(request, env, url, cors, adminSession)) || json({error:"Not found"},404,cors);
  }
  if (url.pathname === "/api/finance/summary" && request.method === "GET") return json(await summary(db),200,cors);
  if (url.pathname === "/api/finance/payments" && request.method === "GET") return json({items:await listPayments(db,url)},200,cors);
  if (url.pathname === "/api/finance/payments/manual" && request.method === "POST") { const result=await manualPayment(db,await body(request)); if(!result.error){const payment=await db.prepare("SELECT order_id,status FROM payments WHERE id=?").bind(result.id).first();if(payment?.status==='paid')await awardCommissionForOrder(db,payment.order_id,result.id);} return json(result,result.status||201,cors); }
  const pay=url.pathname.match(/^\/api\/finance\/payments\/([^/]+)$/); if (pay && request.method === "GET") { const item=await db.prepare("SELECT p.*,m.name merchant_name,o.order_no,o.title order_title FROM payments p JOIN merchants m ON m.id=p.merchant_id LEFT JOIN orders o ON o.id=p.order_id WHERE p.id=?").bind(pay[1]).first(); return item?json(item,200,cors):json({error:"Payment not found"},404,cors); }
  if (pay && request.method === "PATCH") { const data=await body(request); if (!PAYMENT_STATUSES.has(data.status)) return json({error:"Invalid status"},400,cors); const payment=await db.prepare("SELECT order_id FROM payments WHERE id=?").bind(pay[1]).first(); if(!payment) return json({error:"Payment not found"},404,cors); await db.prepare("UPDATE payments SET status=?,confirmed_at=CASE WHEN ?='paid' THEN ? ELSE confirmed_at END,updated_at=? WHERE id=?").bind(data.status,data.status,now(),now(),pay[1]).run(); await refreshOrder(db,payment.order_id); if(data.status==='paid')await awardCommissionForOrder(db,payment.order_id,pay[1]); if(['refunded','partially_refunded'].includes(data.status))await reverseOrderCommission(db,payment.order_id); return json({ok:true},200,cors); }
  const refund=url.pathname.match(/^\/api\/finance\/payments\/([^/]+)\/refunds$/); if(refund && request.method==="POST") { const data=await body(request); const amount=number(data.amount); const payment=await db.prepare("SELECT * FROM payments WHERE id=?").bind(refund[1]).first(); if(!payment||amount===null||amount===0||amount>Number(payment.gross_amount)) return json({error:"Invalid refund"},400,cors); const timestamp=now(); await db.prepare("INSERT INTO refunds (id,payment_id,amount,provider_refund_id,reason,status,refunded_at) VALUES (?,?,?,?,?,?,?)").bind(id("refund"),payment.id,amount,data.provider_refund_id||null,String(data.reason||"").slice(0,500),"refunded",timestamp).run(); const refunded=await db.prepare("SELECT COALESCE(SUM(amount),0) total FROM refunds WHERE payment_id=? AND status='refunded'").bind(payment.id).first(); await db.prepare("UPDATE payments SET status=?,updated_at=? WHERE id=?").bind(Number(refunded.total)>=Number(payment.gross_amount)?"refunded":"partially_refunded",timestamp,payment.id).run(); await refreshOrder(db,payment.order_id); await reverseOrderCommission(db,payment.order_id); return json({ok:true},201,cors); }
  if(url.pathname==="/api/finance/orders" && request.method==="GET") { const rows=await db.prepare("SELECT o.*,m.name merchant_name FROM orders o JOIN merchants m ON m.id=o.merchant_id ORDER BY o.created_at DESC LIMIT 500").all(); return json({items:rows.results},200,cors); }
  if(url.pathname==="/api/finance/orders" && request.method==="POST") { const data=await body(request); const amount=number(data.amount_due),kind=["standard_merchant_promotion","renewal","custom","test","other"].includes(data.partner_order_kind)?data.partner_order_kind:"other",vipEligible=data.partner_vip_eligible===true?1:0; if(!data.merchant_id||!data.title||amount===null)return json({error:"Invalid order"},400,cors); if(data.partner_id){const partner=await db.prepare("SELECT id,status FROM partners WHERE id=?").bind(data.partner_id).first();if(!partner||partner.status!=="active")return json({error:"Invalid partner attribution"},400,cors);} if(vipEligible){const lead=await db.prepare("SELECT id,partner_id,merchant_id FROM partner_leads WHERE id=?").bind(data.lead_id||null).first();if(kind!=="standard_merchant_promotion"||!data.partner_id||!lead||lead.partner_id!==data.partner_id||lead.merchant_id!==data.merchant_id)return json({error:"VIP eligible order requires an attributable standard merchant-promotion lead"},400,cors);} const oid=id("order"),orderNo=`ORD-${Date.now()}-${crypto.randomUUID().slice(0,5).toUpperCase()}`; await db.prepare("INSERT INTO orders (id,order_no,merchant_id,title,amount_due,currency,due_date,partner_id,lead_id,partner_order_kind,partner_vip_eligible,partner_vip_eligibility_note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(oid,orderNo,data.merchant_id,String(data.title).slice(0,200),amount,data.currency||"TWD",data.due_date||null,data.partner_id||null,data.lead_id||null,kind,vipEligible,data.partner_vip_eligibility_note?String(data.partner_vip_eligibility_note).slice(0,500):null).run(); if(vipEligible) await financeAudit(db,"vip_order_eligibility_created",oid,{partner_id:data.partner_id,lead_id:data.lead_id,kind,note:data.partner_vip_eligibility_note||null}); return json({id:oid,order_no:orderNo},201,cors); }
  const order=url.pathname.match(/^\/api\/finance\/orders\/([^/]+)$/); if(order && request.method==="PATCH") { const data=await body(request); const amount=data.amount_due === undefined ? null : number(data.amount_due); if(data.amount_due !== undefined && amount === null)return json({error:"Invalid order amount"},400,cors); const current=await db.prepare("SELECT * FROM orders WHERE id=?").bind(order[1]).first(); if(!current)return json({error:"Order not found"},404,cors); const kind=data.partner_order_kind===undefined?current.partner_order_kind:(["standard_merchant_promotion","renewal","custom","test","other"].includes(data.partner_order_kind)?data.partner_order_kind:null),vipEligible=data.partner_vip_eligible===undefined?Number(current.partner_vip_eligible||0):(data.partner_vip_eligible===true?1:0); if(!kind)return json({error:"Invalid partner order kind"},400,cors); if(vipEligible){const lead=await db.prepare("SELECT id,partner_id,merchant_id FROM partner_leads WHERE id=?").bind(current.lead_id).first();if(kind!=="standard_merchant_promotion"||!current.partner_id||!lead||lead.partner_id!==current.partner_id||lead.merchant_id!==current.merchant_id)return json({error:"VIP eligible order requires an attributable standard merchant-promotion lead"},400,cors);} await db.prepare("UPDATE orders SET title=COALESCE(?,title),amount_due=COALESCE(?,amount_due),due_date=COALESCE(?,due_date),partner_order_kind=?,partner_vip_eligible=?,partner_vip_eligibility_note=COALESCE(?,partner_vip_eligibility_note),updated_at=? WHERE id=?").bind(data.title?String(data.title).slice(0,200):null,amount,data.due_date||null,kind,vipEligible,data.partner_vip_eligibility_note===undefined?null:String(data.partner_vip_eligibility_note).slice(0,500),now(),order[1]).run(); if(data.partner_vip_eligible!==undefined||data.partner_order_kind!==undefined) await financeAudit(db,"vip_order_eligibility_updated",order[1],{partner_id:current.partner_id,lead_id:current.lead_id,kind,vip_eligible:Boolean(vipEligible),note:data.partner_vip_eligibility_note===undefined?current.partner_vip_eligibility_note:(data.partner_vip_eligibility_note||null)}); await refreshOrder(db,order[1]); return json({ok:true},200,cors); }
  if(url.pathname==="/api/finance/merchants" && request.method==="GET") { const rows=await db.prepare("SELECT * FROM merchants WHERE status='active' ORDER BY name").all(); return json({items:rows.results},200,cors); }
  if(url.pathname==="/api/finance/expenses" && request.method==="GET") { const rows=await db.prepare("SELECT * FROM expenses ORDER BY date DESC LIMIT 500").all(); return json({items:rows.results},200,cors); }
  if(url.pathname==="/api/finance/expenses" && request.method==="POST") { const data=await body(request),amount=number(data.amount); if(amount===null||!data.title||!data.category)return json({error:"Invalid expense"},400,cors); await db.prepare("INSERT INTO expenses (id,date,category,title,amount,payment_method,vendor,note) VALUES (?,?,?,?,?,?,?,?)").bind(id("expense"),data.date||now().slice(0,10),data.category,String(data.title).slice(0,200),amount,data.payment_method||null,data.vendor||null,data.note||null).run(); return json({ok:true},201,cors); }
  return json({error:"Not found"},404,cors);
}
