const E=new TextEncoder(),ITERATIONS=100000,COOKIE="baiye_merchant_session";
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=UTF-8","cache-control":"no-store",...h}});
const b64=a=>btoa(String.fromCharCode(...a)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
const random=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
const sha=async v=>b64(new Uint8Array(await crypto.subtle.digest("SHA-256",E.encode(String(v)))));
const same=(a,b)=>{if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0};
const cookieValue=(r,n)=>String(r.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(`${n}=`))?.slice(n.length+1)||"";
export async function deriveMerchantPassword(password,salt,iterations=ITERATIONS){const key=await crypto.subtle.importKey("raw",E.encode(password),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:E.encode(salt),iterations},key,256)))}
const sessionCookie=(v,age=28800)=>`${COOKIE}=${v}; Path=/; HttpOnly; Secure; SameSite=None; Partitioned; Max-Age=${age}`;
export async function getMerchantSession(request,env){const token=cookieValue(request,COOKIE);if(!token||!env.FINANCE_DB)return null;return env.FINANCE_DB.prepare(`SELECT s.id session_id,s.merchant_id,s.user_id,s.csrf_hash,s.expires_at,u.email,u.display_name,u.status,m.name merchant_name,GROUP_CONCAT(DISTINCT p.permission_code) permissions FROM merchant_user_sessions s JOIN merchant_users u ON u.merchant_id=s.merchant_id AND u.id=s.user_id JOIN merchants m ON m.id=s.merchant_id LEFT JOIN merchant_user_roles ur ON ur.merchant_id=u.merchant_id AND ur.user_id=u.id LEFT JOIN merchant_role_permissions p ON p.role_id=ur.role_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND datetime(s.expires_at)>datetime('now') AND u.status='active' GROUP BY s.id`).bind(await sha(token)).first()}
export async function requireMerchant(request,env,permission=""){const s=await getMerchantSession(request,env);if(!s)return null;if(!["GET","HEAD","OPTIONS"].includes(request.method)){const csrf=request.headers.get("x-csrf-token")||"";if(!csrf||!same(await sha(csrf),s.csrf_hash))return null}if(permission&&!String(s.permissions||"").split(",").includes(permission))return null;return s}
export async function handleMerchantAuth(request,env,url,cors={}){const db=env.FINANCE_DB;if(!db)return json({error:"Merchant auth unavailable"},503,cors);
 if(url.pathname==="/api/merchant-auth/login"&&request.method==="POST"){const b=await request.json().catch(()=>({})),email=String(b.email||"").trim().toLowerCase(),merchant=String(b.merchant_id||"").trim(),bucket=new Date().toISOString().slice(0,16),rate=`${merchant}:${email}`;await db.prepare("INSERT OR IGNORE INTO merchant_login_attempts(rate_key,bucket_start) VALUES(?,?)").bind(rate,bucket).run();const a=await db.prepare("UPDATE merchant_login_attempts SET attempt_count=attempt_count+1,last_attempt_at=CURRENT_TIMESTAMP WHERE rate_key=? AND bucket_start=? AND attempt_count<5").bind(rate,bucket).run();if(!a.meta?.changes)return json({error:"登入嘗試過多"},429,cors);const u=await db.prepare("SELECT * FROM merchant_users WHERE merchant_id=? AND email=?").bind(merchant,email).first();const supplied=u?await deriveMerchantPassword(String(b.password||""),u.password_salt,Number(u.password_iterations||ITERATIONS)):random();if(!u||u.status!=="active"||!same(supplied,u.password_hash)){await db.prepare("INSERT INTO merchant_security_events(id,merchant_id,user_id,action) VALUES(?,?,?,'login_failed')").bind(`mse_${crypto.randomUUID()}`,merchant,u?.id||null).run();return json({error:"帳號或密碼錯誤"},401,cors)}const token=random(),csrf=random(),expires=new Date(Date.now()+28800000).toISOString();await db.batch([db.prepare("INSERT INTO merchant_user_sessions(id,merchant_id,user_id,token_hash,csrf_hash,expires_at) VALUES(?,?,?,?,?,?)").bind(`mus_${crypto.randomUUID()}`,merchant,u.id,await sha(token),await sha(csrf),expires),db.prepare("INSERT INTO merchant_security_events(id,merchant_id,user_id,action) VALUES(?,?,?,'login_success')").bind(`mse_${crypto.randomUUID()}`,merchant,u.id)]);return json({user:{id:u.id,merchant_id:merchant,email:u.email,name:u.display_name},csrf_token:csrf,expires_at:expires},200,{...cors,"set-cookie":sessionCookie(token)})}
 if(url.pathname==="/api/merchant-auth/session"&&request.method==="GET"){const s=await getMerchantSession(request,env);if(!s)return json({error:"未登入"},401,cors);const csrf=random();await db.prepare("UPDATE merchant_user_sessions SET csrf_hash=? WHERE id=?").bind(await sha(csrf),s.session_id).run();return json({user:{id:s.user_id,merchant_id:s.merchant_id,email:s.email,name:s.display_name},merchant:{id:s.merchant_id,name:s.merchant_name},permissions:String(s.permissions||"").split(",").filter(Boolean),csrf_token:csrf,expires_at:s.expires_at},200,cors)}
 if(url.pathname==="/api/merchant-auth/logout"&&request.method==="POST"){const s=await requireMerchant(request,env);if(!s)return json({error:"未授權"},401,cors);await db.batch([db.prepare("UPDATE merchant_user_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE id=?").bind(s.session_id),db.prepare("INSERT INTO merchant_security_events(id,merchant_id,user_id,action) VALUES(?,?,?,'logout')").bind(`mse_${crypto.randomUUID()}`,s.merchant_id,s.user_id)]);return json({ok:true},200,{...cors,"set-cookie":sessionCookie("",0)})}
 return null}
