import { useEffect, useMemo, useState } from "react";

const API = "https://chuang-baiye-ai.baiye-platform.workers.dev";
const MERCHANT_ID = "meiling_patchwork";
const weekdays = ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"];
const statuses: Record<string, string> = { pending: "待確認", confirmed: "已確認", cancelled: "已取消", completed: "已完成", no_show: "未到" };
type Service = { id:string;name:string;description?:string;duration_minutes:number;buffer_before_minutes:number;buffer_after_minutes:number;price_text?:string;max_capacity:number;active:number };
type Hour = { id:string;weekday:number;start_time:string;end_time:string;active:number;staff_id?:string };
type Blackout = { id:string;start_at:string;end_at:string;reason?:string;active:number };
type Booking = { booking_code:string;start_at:string;end_at:string;status:string;source:string;customer_name:string;customer_phone:string;service_name:string;staff_name:string };
type Settings = { enabled:number;slot_interval_minutes:number;minimum_notice_minutes:number;maximum_advance_days:number;cancellation_cutoff_minutes:number;reschedule_cutoff_minutes:number;default_buffer_before_minutes:number;default_buffer_after_minutes:number;reminders_enabled:number };

export function AdminBookings() {
  const [token,setToken]=useState(()=>sessionStorage.getItem("baiye_finance_session")||"");
  const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  const [settings,setSettings]=useState<Settings|null>(null); const [services,setServices]=useState<Service[]>([]); const [hours,setHours]=useState<Hour[]>([]); const [blackouts,setBlackouts]=useState<Blackout[]>([]); const [bookings,setBookings]=useState<Booking[]>([]);
  const [hour,setHour]=useState({weekday:"1",start_time:"09:00",end_time:"17:00"}); const [view,setView]=useState<"day"|"week"|"month">("week");
  const [blackout,setBlackout]=useState({start_at:"",end_at:"",reason:""}); const [query,setQuery]=useState(""); const [statusFilter,setStatusFilter]=useState("");
  const request=async(path:string,init:RequestInit={})=>{const join=path.includes("?")?"&":"?";const response=await fetch(`${API}${path}${join}merchant_id=${MERCHANT_ID}`,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...init.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||"操作失敗");return data;};
  const load=async()=>{setLoading(true);setMessage("");try{const [config,list]=await Promise.all([request("/api/admin/booking/settings"),request("/api/admin/bookings")]);setSettings(config.settings);setServices(config.services);setHours(config.hours);setBlackouts(config.blackouts);setBookings(list.items);}catch(error){setMessage(error instanceof Error?error.message:"讀取失敗");}finally{setLoading(false);}};
  useEffect(()=>{if(token)void load();},[token]);
  const login=async(event:React.FormEvent)=>{event.preventDefault();setMessage("");try{const response=await fetch(`${API}/api/finance/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.error||"登入失敗");sessionStorage.setItem("baiye_finance_session",data.token);setToken(data.token);setPassword("");}catch(error){setMessage(error instanceof Error?error.message:"登入失敗");}};
  const saveSettings=async(event:React.FormEvent)=>{event.preventDefault();if(!settings)return;try{await request("/api/admin/booking/settings",{method:"PATCH",body:JSON.stringify({...settings,enabled:Boolean(settings.enabled),reminders_enabled:Boolean(settings.reminders_enabled)})});setMessage("預約規則已儲存。");await load();}catch(error){setMessage(error instanceof Error?error.message:"儲存失敗");}};
  const addHour=async(event:React.FormEvent)=>{event.preventDefault();try{await request("/api/admin/booking/hours",{method:"POST",body:JSON.stringify({...hour,weekday:Number(hour.weekday)})});setMessage("開放時段已新增。");await load();}catch(error){setMessage(error instanceof Error?error.message:"新增失敗");}};
  const toggleHour=async(item:Hour)=>{try{await request(`/api/admin/booking/hours/${item.id}`,{method:"PATCH",body:JSON.stringify({active:!item.active})});await load();}catch(error){setMessage(error instanceof Error?error.message:"更新失敗");}};
  const addBlackout=async(event:React.FormEvent)=>{event.preventDefault();try{await request("/api/admin/booking/blackouts",{method:"POST",body:JSON.stringify({start_at:new Date(blackout.start_at).toISOString(),end_at:new Date(blackout.end_at).toISOString(),reason:blackout.reason})});setBlackout({start_at:"",end_at:"",reason:""});setMessage("休假／封鎖時段已新增。");await load();}catch(error){setMessage(error instanceof Error?error.message:"新增失敗");}};
  const toggleBlackout=async(item:Blackout)=>{try{await request(`/api/admin/booking/blackouts/${item.id}`,{method:"PATCH",body:JSON.stringify({active:!item.active})});await load();}catch(error){setMessage(error instanceof Error?error.message:"更新失敗");}};
  const saveService=async(item:Service)=>{try{await request(`/api/admin/booking/services/${item.id}`,{method:"PATCH",body:JSON.stringify({...item,active:Boolean(item.active)})});setMessage(`${item.name} 已儲存。`);await load();}catch(error){setMessage(error instanceof Error?error.message:"儲存失敗");}};
  const updateStatus=async(code:string,status:string)=>{try{await request(`/api/admin/bookings/${encodeURIComponent(code)}/status`,{method:"PATCH",body:JSON.stringify({status})});await load();}catch(error){setMessage(error instanceof Error?error.message:"更新失敗");}};
  const visibleBookings=useMemo(()=>{const now=new Date(), start=new Date(now); if(view==="day")start.setHours(0,0,0,0);if(view==="week")start.setDate(now.getDate()-now.getDay());if(view==="month")start.setDate(1);start.setHours(0,0,0,0);const needle=query.trim().toLowerCase();return bookings.filter(item=>new Date(item.start_at)>=start&&(!statusFilter||item.status===statusFilter)&&(!needle||[item.booking_code,item.customer_name,item.customer_phone,item.service_name,item.staff_name].some(value=>String(value||"").toLowerCase().includes(needle))));},[bookings,view,query,statusFilter]);
  if(!token)return <main className="finance-shell finance-login"><section className="finance-panel"><h1>美玲拼布｜預約管理</h1><p>使用平台管理員驗證後管理開放時段與預約。</p><form className="finance-form" onSubmit={login}><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="財務管理密碼" required/><button>安全登入預約後台</button></form>{message&&<p className="finance-note">{message}</p>}</section></main>;
  return <main className="finance-shell booking-admin"><header className="finance-hero"><div><h1>美玲拼布｜預約管理</h1><p>merchant_id：{MERCHANT_ID}，所有預約均依商家隔離。</p></div><div className="finance-actions"><a className="booking-admin-link" href="https://meilingpatchwork.com/booking/" target="_blank" rel="noreferrer">開啟顧客預約頁</a><button onClick={()=>{sessionStorage.removeItem("baiye_finance_session");setToken("");}}>登出</button></div></header>{message&&<p className="finance-note">{message}</p>}{loading&&<p>讀取中…</p>}
    {settings&&<section className="finance-panel"><h2>預約規則</h2><form className="booking-settings-grid" onSubmit={saveSettings}><label className="booking-switch"><input type="checkbox" checked={Boolean(settings.enabled)} onChange={e=>setSettings({...settings,enabled:e.target.checked?1:0})}/> 啟用線上預約</label><label>可提前預約天數<input type="number" min="1" value={settings.maximum_advance_days} onChange={e=>setSettings({...settings,maximum_advance_days:Number(e.target.value)})}/></label><label>最短提前分鐘<input type="number" min="0" value={settings.minimum_notice_minutes} onChange={e=>setSettings({...settings,minimum_notice_minutes:Number(e.target.value)})}/></label><label>時段間隔分鐘<input type="number" min="5" value={settings.slot_interval_minutes} onChange={e=>setSettings({...settings,slot_interval_minutes:Number(e.target.value)})}/></label><label>取消截止分鐘<input type="number" min="0" value={settings.cancellation_cutoff_minutes} onChange={e=>setSettings({...settings,cancellation_cutoff_minutes:Number(e.target.value)})}/></label><label>改期截止分鐘<input type="number" min="0" value={settings.reschedule_cutoff_minutes} onChange={e=>setSettings({...settings,reschedule_cutoff_minutes:Number(e.target.value)})}/></label><label>預設前置 Buffer<input type="number" min="0" value={settings.default_buffer_before_minutes} onChange={e=>setSettings({...settings,default_buffer_before_minutes:Number(e.target.value)})}/></label><label>預設後置 Buffer<input type="number" min="0" value={settings.default_buffer_after_minutes} onChange={e=>setSettings({...settings,default_buffer_after_minutes:Number(e.target.value)})}/></label><label className="booking-switch"><input type="checkbox" checked={Boolean(settings.reminders_enabled)} onChange={e=>setSettings({...settings,reminders_enabled:e.target.checked?1:0})}/> 啟用 24 小時 LINE 提醒</label><button>儲存預約規則</button></form></section>}
    <section className="finance-panel"><h2>每週開放時段</h2>{hours.length===0&&<p className="finance-note">尚未設定營業時間，因此前台不會顯示可預約時段。</p>}<div className="booking-hours-list">{hours.map(item=><button className={item.active?"active":""} key={item.id} onClick={()=>void toggleHour(item)}>{weekdays[item.weekday]} {item.start_time}–{item.end_time}<small>{item.active?"開放中":"已停用"}</small></button>)}</div><form className="booking-hour-form" onSubmit={addHour}><select value={hour.weekday} onChange={e=>setHour({...hour,weekday:e.target.value})}>{weekdays.map((name,index)=><option value={index} key={name}>{name}</option>)}</select><input type="time" value={hour.start_time} onChange={e=>setHour({...hour,start_time:e.target.value})} required/><span>至</span><input type="time" value={hour.end_time} onChange={e=>setHour({...hour,end_time:e.target.value})} required/><button>新增開放時段</button></form></section>
    <section className="finance-panel"><h2>休假／特殊封鎖</h2><div className="booking-hours-list">{blackouts.map(item=><button className={item.active?"active":""} key={item.id} onClick={()=>void toggleBlackout(item)}>{new Date(item.start_at).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"})}–{new Date(item.end_at).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"})}<small>{item.reason||"未填原因"}・{item.active?"封鎖中":"已停用"}</small></button>)}</div><form className="booking-hour-form" onSubmit={addBlackout}><input type="datetime-local" value={blackout.start_at} onChange={e=>setBlackout({...blackout,start_at:e.target.value})} required/><span>至</span><input type="datetime-local" value={blackout.end_at} onChange={e=>setBlackout({...blackout,end_at:e.target.value})} required/><input value={blackout.reason} onChange={e=>setBlackout({...blackout,reason:e.target.value})} placeholder="原因，例如公休"/><button>新增封鎖時段</button></form></section>
    <section className="finance-panel"><h2>服務／課程</h2><div className="booking-service-grid">{services.map((item,index)=><article key={item.id}><input value={item.name} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,name:e.target.value}:v))}/><textarea value={item.description||""} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,description:e.target.value}:v))}/><label>服務時間（分鐘）<input type="number" min="15" value={item.duration_minutes} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,duration_minutes:Number(e.target.value)}:v))}/></label><label>前置 Buffer（分鐘）<input type="number" min="0" value={item.buffer_before_minutes} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,buffer_before_minutes:Number(e.target.value)}:v))}/></label><label>後置 Buffer（分鐘）<input type="number" min="0" value={item.buffer_after_minutes} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,buffer_after_minutes:Number(e.target.value)}:v))}/></label><label>價格說明<input value={item.price_text||""} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,price_text:e.target.value}:v))}/></label><label>每時段人數<input type="number" min="1" value={item.max_capacity} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,max_capacity:Number(e.target.value)}:v))}/></label><label className="booking-switch"><input type="checkbox" checked={Boolean(item.active)} onChange={e=>setServices(items=>items.map((v,i)=>i===index?{...v,active:e.target.checked?1:0}:v))}/> 開放預約</label><button onClick={()=>void saveService(item)}>儲存服務</button></article>)}</div></section>
    <section className="finance-panel"><div className="booking-calendar-head"><h2>預約行事曆</h2><div>{(["day","week","month"] as const).map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}>{item==="day"?"日":item==="week"?"週":"月"}</button>)}</div></div><div className="booking-list-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋顧客、手機、服務或預約編號"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">全部狀態</option>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>{visibleBookings.length===0?<p className="finance-note">目前沒有符合範圍的預約。</p>:<table className="finance-table"><thead><tr><th>日期時間</th><th>顧客</th><th>服務／人員</th><th>狀態</th><th>操作</th></tr></thead><tbody>{visibleBookings.map(item=><tr key={item.booking_code}><td data-label="日期時間">{new Date(item.start_at).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"})}</td><td data-label="顧客">{item.customer_name}<br/><small>{item.customer_phone}</small></td><td data-label="服務／人員">{item.service_name}<br/><small>{item.staff_name}</small></td><td data-label="狀態">{statuses[item.status]||item.status}</td><td data-label="操作"><select value={item.status} onChange={e=>void updateStatus(item.booking_code,e.target.value)}>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></td></tr>)}</tbody></table>}</section>
  </main>;
}
