import { useEffect, useMemo, useState } from "react";

const API = "https://chuang-baiye-ai.baiye-platform.workers.dev/api/finance";
const labels: Record<string, string> = { card:"信用卡 / 金融卡",atm:"ATM",virtual_account:"虛擬帳號",bank_transfer:"銀行轉帳",line_pay:"LINE Pay",apple_pay:"Apple Pay",google_pay:"Google Pay",e_wallet:"電子支付",convenience_store:"超商付款",cash:"現金",cheque:"支票",other:"其他" };
const money = (value: unknown) => new Intl.NumberFormat("zh-TW", { style:"currency",currency:"TWD",maximumFractionDigits:0 }).format(Number(value || 0));
type Summary = { month_gross:number;month_refunds:number;month_fees:number;month_net:number;pending:number;expenses:number;profit:number;payment_count:number;methods:Array<{payment_method:string;total:number}>;merchants:Array<{id:string;merchant_code:string;name:string;amount_due:number;amount_paid:number}> };
type Merchant = { id:string; name:string };
type Payment = Record<string, string | number | null>;

export function AdminFinancePage() {
  const [token,setToken]=useState(()=>sessionStorage.getItem("baiye_finance_session")||""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [summary,setSummary]=useState<Summary|null>(null); const [payments,setPayments]=useState<Payment[]>([]); const [merchants,setMerchants]=useState<Merchant[]>([]); const [form,setForm]=useState({merchant_id:"",amount:"",payment_method:"bank_transfer",note:"",status:"paid"});
  const request=async(path:string,init:RequestInit={})=>{ const response=await fetch(`${API}${path}`,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...init.headers}}); const data=await response.json(); if(!response.ok) throw new Error(data.error||"Request failed"); return data; };
  const load=async()=>{ try { const [s,p,m]=await Promise.all([request("/summary"),request("/payments"),request("/merchants")]); setSummary(s);setPayments(p.items);setMerchants(m.items); if(!form.merchant_id&&m.items[0])setForm((v)=>({...v,merchant_id:m.items[0].id})); } catch(e){setError(e instanceof Error?e.message:"讀取失敗");} };
  useEffect(()=>{if(token) void load();},[token]);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setError("");try{const response=await fetch(`${API}/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.error||"登入失敗");sessionStorage.setItem("baiye_finance_session",data.token);setToken(data.token);setPassword("");}catch(e){setError(e instanceof Error?e.message:"登入失敗");}};
  const add=async(e:React.FormEvent)=>{e.preventDefault();try{await request("/payments/manual",{method:"POST",body:JSON.stringify({...form,amount:Number(form.amount)})});setForm((v)=>({...v,amount:"",note:""}));await load();}catch(e){setError(e instanceof Error?e.message:"新增失敗");}};
  const exportCsv=()=>{const rows=[["日期","商家","訂單","付款方式","支付平台","金額","手續費","淨額","狀態","交易編號"],...payments.map((p)=>[String(p.paid_at||p.created_at||""),String(p.merchant_name||""),String(p.order_no||""),labels[String(p.payment_method)]||String(p.payment_method||""),String(p.payment_provider||""),String(p.gross_amount||""),String(p.fee_amount||""),String(p.net_amount||""),String(p.status||""),String(p.provider_trade_no||p.payment_no||"")])];const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(r=>r.map(v=>`\"${v.replaceAll('"','""')}\"`).join(",")).join("\n")],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="baiye-finance-payments.csv";a.click();URL.revokeObjectURL(url);};
  const metrics=useMemo(()=>summary?[['本月總收款',summary.month_gross],['本月退款',summary.month_refunds],['本月手續費',summary.month_fees],['本月淨收入',summary.month_net],['待收款',summary.pending],['本月支出',summary.expenses],['本月損益',summary.profit],['付款筆數',summary.payment_count]]:[],[summary]);
  if(!token)return <main className="finance-shell finance-login"><section className="finance-panel"><h1>財務管理 / 金流帳本</h1><p>此區使用 Worker 後端驗證，不使用公開前端管理員帳密。</p><form className="finance-form" onSubmit={login}><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="財務管理密碼" required/><button>安全登入財務帳本</button></form>{error&&<p className="finance-note">{error}</p>}</section></main>;
  return <main className="finance-shell"><header className="finance-hero"><div><h1>財務管理 / 金流帳本</h1><p>所有付款方式統一入帳；自動 Webhook 與人工確認清楚區分。</p></div><div className="finance-actions"><button onClick={exportCsv}>匯出 CSV</button><button onClick={()=>{sessionStorage.removeItem("baiye_finance_session");setToken("");}}>登出</button></div></header>{error&&<p className="finance-note">{error}</p>}<section className="finance-grid">{metrics.map(([name,value])=><article className="finance-metric" key={String(name)}><span>{name}</span><strong>{name==='付款筆數'?value:money(value)}</strong></article>)}</section><div className="finance-layout"><section><article className="finance-panel"><h2>付款紀錄</h2><table className="finance-table"><thead><tr><th>日期</th><th>商家 / 訂單</th><th>付款方式</th><th>實收</th><th>手續費</th><th>淨額</th><th>狀態</th><th>來源</th></tr></thead><tbody>{payments.map((p)=><tr key={String(p.id)}><td data-label="日期">{String(p.paid_at||p.created_at||"").slice(0,10)}</td><td data-label="商家 / 訂單">{String(p.merchant_name||"")}<br/><small>{String(p.order_no||p.payment_no||"")}</small></td><td data-label="付款方式">{labels[String(p.payment_method)]||String(p.payment_method||"")}</td><td data-label="實收">{money(p.gross_amount)}</td><td data-label="手續費">{money(p.fee_amount)}</td><td data-label="淨額">{money(p.net_amount)}</td><td data-label="狀態"><span className="finance-status">{String(p.status)}</span></td><td data-label="來源">{p.source==='manual'?'人工確認':'自動入帳'}</td></tr>)}</tbody></table></article><article className="finance-panel"><h2>付款方式統計</h2><table className="finance-table"><tbody>{summary?.methods.map((m)=><tr key={m.payment_method}><td>{labels[m.payment_method]||m.payment_method}</td><td>{money(m.total)}</td></tr>)}</tbody></table></article></section><aside><article className="finance-panel"><h2>新增人工付款</h2><p className="finance-note">銀行轉帳、現金、支票與其他線下付款，確認後才會計入收入。</p><form className="finance-form" onSubmit={add}><select value={form.merchant_id} onChange={(e)=>setForm({...form,merchant_id:e.target.value})}>{merchants.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><input inputMode="decimal" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})} placeholder="收款金額" required/><select value={form.payment_method} onChange={(e)=>setForm({...form,payment_method:e.target.value})}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="paid">已確認收款</option><option value="pending">待確認</option></select><input value={form.note} onChange={(e)=>setForm({...form,note:e.target.value})} placeholder="備註，例如帳號末五碼"/><button>寫入統一帳本</button></form></article><article className="finance-panel"><h2>商家統計</h2>{summary?.merchants.map(m=><p key={m.id}><strong>{m.name}</strong><br/><small>應收 {money(m.amount_due)} ・ 已收 {money(m.amount_paid)} ・ 待收 {money(m.amount_due-m.amount_paid)}</small></p>)}</article></aside></div></main>;
}
