import { useEffect, useState } from "react";
import { adminApi } from "../admin-auth-client";
import { AdminModuleNav } from "../components/AdminModuleNav";

const errorText = (error: unknown) => error instanceof Error ? error.message : "加購管理服務暫時無法使用。";

export function AdminAddonsPage() {
  const [requests, setRequests] = useState<any[]>([]), [pricing, setPricing] = useState<any[]>([]), [notice, setNotice] = useState("");
  const [quote, setQuote] = useState({ merchant_id: "", change_request_id: "", code: "simple_cart", quantity: 1, quoted_amount_minor: "" });
  const load = async () => { try { const [r,p] = await Promise.all([adminApi("/api/admin/content-change-requests"),adminApi("/api/admin/addon-pricing")]); setRequests(r.items || []); setPricing(p.items || []); } catch (error) { setNotice(errorText(error)); } };
  useEffect(() => { void load(); }, []);
  const issue = async () => { try { const result = await adminApi("/api/admin/addon-quotes", { method: "POST", body: JSON.stringify({ merchant_id: quote.merchant_id, change_request_id: quote.change_request_id || undefined, contract_total_minor: 0, items: [{ code: quote.code, quantity: Number(quote.quantity), quoted_amount_minor: quote.quoted_amount_minor === "" ? undefined : Number(quote.quoted_amount_minor) }] }) }); setNotice(`已發出 ${result.quote_no}：主方案 NT$18,000 ＋ 加購 NT$${Math.round(result.addon_amount_minor / 100).toLocaleString("zh-TW")}，總額 NT$${Math.round(result.contract_total_minor / 100).toLocaleString("zh-TW")}。`); await load(); } catch (error) { setNotice(errorText(error)); } };
  return <main className="admin-page contract-admin"><AdminModuleNav current="contracts" /><header><p>附件 B 與補充協議</p><h1>內容修改與加購管理</h1><span>百工 Admin 確認 Quote；總額由伺服器計算</span></header>{notice && <div className="partner-message">{notice}</div>}<section className="admin-panel"><h2>Merchant Content Change Requests</h2>{requests.map((item) => <button type="button" className="contract-list-item" key={item.id} onClick={() => setQuote({ ...quote, merchant_id: item.merchant_id, change_request_id: item.id })}><strong>{item.merchant_name} · {item.status}</strong><span>{item.items_text}</span></button>)}{!requests.length && <p>目前沒有修改申請。</p>}</section><section className="admin-panel"><h2>建立 Add-on Quote</h2><p>「起」價格不會由系統自行決定，必須輸入百工 Admin 確認的最終報價。前端 total 欄位不採信。</p><div className="contract-form-grid"><label>Merchant ID<input value={quote.merchant_id} onChange={(e) => setQuote({ ...quote, merchant_id: e.target.value })} /></label><label>Request ID<input value={quote.change_request_id} onChange={(e) => setQuote({ ...quote, change_request_id: e.target.value })} /></label><label>加購項目<select value={quote.code} onChange={(e) => setQuote({ ...quote, code: e.target.value })}>{pricing.map((item) => <option key={item.code} value={item.code}>{item.label} · {item.minimum_label || (item.amount_minor != null ? `NT$${Math.round(item.amount_minor / 100).toLocaleString("zh-TW")}` : "Admin 報價")}</option>)}</select></label><label>數量<input type="number" min="1" value={quote.quantity} onChange={(e) => setQuote({ ...quote, quantity: Number(e.target.value) })} /></label><label>Admin 最終報價（分）<input type="number" min="0" value={quote.quoted_amount_minor} onChange={(e) => setQuote({ ...quote, quoted_amount_minor: e.target.value })} placeholder="起價／客製項目必填" /></label></div><button className="btn btn-primary" onClick={() => void issue()}>由伺服器計算並發出報價</button></section></main>;
}
