import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowRight, CalendarCheck, CheckCircle, Compass, Heart, MagnifyingGlass, ShieldCheck, Sparkle, Star, UserCircle } from "@phosphor-icons/react";
import { MarketingHero, MarketingSection, PremiumCard, PublicLayout, SectionHeading } from "../components";
import { advisorApi, twd } from "../advisor-client";
import "../advisor-marketplace.css";

type Category={slug:string;display_name:string;description:string;icon_name:string;policy_disclaimer:string};
type Advisor={id:string;slug:string;display_name:string;tagline:string;biography:string;specialties:string[];photo_url:string;rating:number;completed_services:number;service_start_minor:number;next_available_at?:string;categories:{slug:string;name:string}[];star_level:{label:string;level:string}|null};
type Service={id:string;name:string;description:string;price_minor:number;duration_minutes:number;service_mode:string;notice?:string};
const SAFE_COPY="本平台服務屬文化、娛樂、生活探索、個人成長與一般陪談用途，不替代醫療、心理治療、法律或投資專業服務。";

function MarketplaceHeader(){return <header className="advisor-header"><Link to="/advisors" className="advisor-brand"><Sparkle weight="fill"/><span>創百業智慧鏈</span><strong>身心靈生活顧問聯盟</strong></Link><nav><Link to="/advisors/match">AI 找顧問</Link><Link to="/advisor/apply">成為老師</Link><Link to="/advisor/login">老師登入</Link></nav></header>}
function AdvisorPublicShell({children}:{children:React.ReactNode}){return <PublicLayout><MarketplaceHeader/>{children}<footer className="advisor-footer"><strong>創百業智慧鏈｜身心靈生活顧問聯盟</strong><p>{SAFE_COPY}</p></footer></PublicLayout>}
function Stars({value}:{value:number}){return <span className="advisor-rating"><Star weight="fill"/> {value ? value.toFixed(1) : "新上架"}</span>}
function AdvisorCard({advisor}:{advisor:Advisor}){return <PremiumCard className="advisor-card"><img src={advisor.photo_url||"/brand/chuang-baiye-smart-chain-logo.png"} alt={`${advisor.display_name}老師`}/><div><div className="advisor-card-meta"><Stars value={advisor.rating}/>{advisor.star_level&&<span className="advisor-level">{advisor.star_level.label}・平台服務等級</span>}</div><h2>{advisor.display_name}</h2><p>{advisor.tagline}</p><div className="advisor-tags">{advisor.categories?.map(c=><span key={c.slug}>{c.name}</span>)}</div><p className="advisor-proof">已完成 {advisor.completed_services} 次服務・{advisor.service_start_minor?twd(advisor.service_start_minor):"價格待確認"} 起</p><div className="advisor-card-actions"><Link className="btn btn-outline" to={`/advisors/${advisor.slug}`}>查看老師</Link><Link className="btn btn-primary" to={`/advisors/${advisor.slug}?book=1`}>立即預約</Link></div></div></PremiumCard>}

export function AdvisorMarketplacePage(){const [categories,setCategories]=useState<Category[]>([]),[advisors,setAdvisors]=useState<Advisor[]>([]),[params,setParams]=useSearchParams(),[error,setError]=useState("");const category=params.get("category")||"",q=params.get("q")||"";useEffect(()=>{Promise.all([advisorApi<{categories:Category[]}>("/api/advisors/categories"),advisorApi<{advisors:Advisor[]}>(`/api/advisors?category=${encodeURIComponent(category)}&q=${encodeURIComponent(q)}`)]).then(([a,b])=>{setCategories(a.categories);setAdvisors(b.advisors);setError("")}).catch(e=>setError(e.message))},[category,q]);return <AdvisorPublicShell><MarketingHero eyebrow="創百業智慧鏈｜生活探索 Marketplace" title="今天想探索什麼問題？" description="從事業、感情、夢境到個人成長，依服務專長、時段與公開評價找到合適的老師／顧問。" primary={{label:"讓 AI 協助分類",to:"/advisors/match"}} secondary={{label:"申請成為老師",to:"/advisor/apply"}}><div className="advisor-hero-orbit"><Compass/><span>生活探索</span><Heart/><span>個人成長</span></div></MarketingHero><MarketingSection><SectionHeading eyebrow="探索方向" title="依你的問題，找到適合的服務類型"/><form className="advisor-search" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setParams(p=>{p.set("q",String(data.get("q")||""));return p})}}><MagnifyingGlass/><input name="q" defaultValue={q} aria-label="關鍵字搜尋" placeholder="搜尋老師、專長或想探索的問題"/><button className="btn btn-primary">搜尋</button></form><div className="advisor-category-list"><button className={!category?"active":""} onClick={()=>setParams({})}>全部</button>{categories.map(c=><button className={category===c.slug?"active":""} key={c.slug} onClick={()=>setParams({category:c.slug})}>{c.display_name}</button>)}</div>{error&&<p role="alert" className="advisor-error">{error}</p>}<div className="advisor-grid">{advisors.map(a=><AdvisorCard advisor={a} key={a.id}/>)}</div>{!error&&!advisors.length&&<div className="advisor-empty">目前沒有符合條件的老師，請調整搜尋條件。</div>}</MarketingSection><MarketingSection className="advisor-safety"><ShieldCheck/><div><h2>探索可以很自由，資訊必須很清楚</h2><p>{SAFE_COPY}</p></div></MarketingSection></AdvisorPublicShell>}

export function AdvisorCategoryPage(){const {slug}=useParams();return <AdvisorMarketplacePage key={slug}/>}

export function AdvisorMatchPage(){const [question,setQuestion]=useState(""),[result,setResult]=useState<{message:string;advisors:Advisor[];safety:string}|null>(null),[loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);try{setResult(await advisorApi("/api/advisors/match",{method:"POST",body:JSON.stringify({question})}))}finally{setLoading(false)}}return <AdvisorPublicShell><MarketingHero eyebrow="AI 顧問推薦" title="把現在的困惑，用自己的方式說出來" description="AI 只協助需求分類與推薦服務，不會替你算命、診斷或下重大人生決定。"/><MarketingSection><form className="advisor-match-form" onSubmit={submit}><label>今天想探索什麼？<textarea value={question} onChange={e=>setQuestion(e.target.value)} minLength={6} required placeholder="例如：最近工作很不順，不知道是否該換方向。"/></label><button className="btn btn-primary btn-lg" disabled={loading}>{loading?"正在整理方向…":"推薦適合的老師"}</button></form>{result&&<><div className="advisor-match-copy"><Sparkle/><p>{result.message}</p><small>{result.safety}</small></div><div className="advisor-grid">{result.advisors.map(a=><AdvisorCard advisor={a} key={a.id}/>)}</div></>}</MarketingSection></AdvisorPublicShell>}

export function AdvisorProfilePage(){const {slug}=useParams(),[data,setData]=useState<{advisor:Advisor;services:Service[];reviews:{rating:number;review_text:string}[];disclaimer:string}|null>(null),[selected,setSelected]=useState(""),[date,setDate]=useState(""),[slots,setSlots]=useState<string[]>([]),[message,setMessage]=useState("");useEffect(()=>{advisorApi<any>(`/api/advisors/${slug}`).then(d=>{setData(d);setSelected(d.services[0]?.id||"")}).catch(e=>setMessage(e.message))},[slug]);useEffect(()=>{if(!date||!selected)return;advisorApi<{slots:string[]}>(`/api/advisors/${slug}/availability?service_id=${selected}&date=${date}`).then(r=>setSlots(r.slots)).catch(()=>setSlots([]))},[date,selected,slug]);async function book(time:string){try{const service=data?.services.find(s=>s.id===selected);const r=await advisorApi<any>("/api/advisor/bookings",{method:"POST",body:JSON.stringify({advisor_id:data?.advisor.id,service_id:selected,date,time,accept_terms:true,accept_service:true,accept_price:true,accept_cancellation:true,accept_disclaimer:true})});setMessage(`預約已確認：${r.booking.booking_code}（Staging Test Provider）`)}catch(e:any){setMessage(e.message)}}if(!data)return <AdvisorPublicShell><main className="advisor-loading">{message||"正在載入老師資料…"}</main></AdvisorPublicShell>;return <AdvisorPublicShell><main className="advisor-profile"><section className="advisor-profile-hero"><img src={data.advisor.photo_url} alt={data.advisor.display_name}/><div><span className="eyebrow">老師專屬品牌頁</span><h1>{data.advisor.display_name}</h1><p>{data.advisor.tagline}</p><Stars value={data.advisor.rating}/><div className="advisor-tags">{data.advisor.categories.map(c=><span key={c.slug}>{c.name}</span>)}</div></div></section><section className="advisor-profile-layout"><article><h2>關於老師</h2><p>{data.advisor.biography}</p><h2>服務項目</h2><div className="advisor-service-list">{data.services.map(s=><label className={selected===s.id?"selected":""} key={s.id}><input type="radio" name="service" checked={selected===s.id} onChange={()=>setSelected(s.id)}/><span><strong>{s.name}</strong><small>{s.description}</small></span><b>{twd(s.price_minor)}・{s.duration_minutes} 分鐘</b></label>)}</div><h2>客戶評價</h2>{data.reviews.length?data.reviews.map((r,i)=><blockquote key={i}><Stars value={r.rating}/><p>{r.review_text}</p></blockquote>):<p>目前尚無公開評價。</p>}</article><aside className="advisor-booking-card"><h2>立即預約</h2><label>選擇日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="advisor-slots">{slots.map(t=><button key={t} onClick={()=>book(t)}>{t}</button>)}</div>{date&&!slots.length&&<p>此日期目前沒有可預約時段。</p>}<p className="advisor-disclaimer">{data.disclaimer}</p>{message&&<p role="status" className="advisor-message">{message}</p>}</aside></section></main></AdvisorPublicShell>}

export function AdvisorApplyPage(){const [status,setStatus]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await advisorApi<any>("/api/advisor/apply",{method:"POST",body:JSON.stringify({display_name:f.get("display_name"),legal_name:f.get("legal_name"),email:f.get("email"),experience:f.get("experience"),introduction:f.get("introduction"),service_modes:["online"],proposed_services:[],desired_pricing:{},portfolio_urls:[],declarations:{independent_provider:true,content_policy:true,no_guaranteed_income:true}})});setStatus(`申請已送出：${r.status}`)}catch(e:any){setStatus(e.message)}}return <AdvisorPublicShell><MarketingHero eyebrow="顧問合作申請" title="不用先付建站費，建立自己的線上顧問品牌" description="平台提供品牌頁、服務展示、預約、會員、付款準備、AI 介紹影片流程、評價、AI 客服與後台；不保證流量、客戶或收入。"/><MarketingSection><form className="advisor-form" onSubmit={submit}><label>顯示名稱<input name="display_name" required/></label><label>法定姓名（不公開）<input name="legal_name" required/></label><label>Email（不公開）<input name="email" type="email" required/></label><label>服務經歷<textarea name="experience" required/></label><label>自我介紹<textarea name="introduction" required/></label><label className="advisor-check"><input type="checkbox" required/>我了解合作為獨立服務提供者，並同意內容安全規範。</label><button className="btn btn-primary btn-lg">送出合作申請</button>{status&&<p role="status">{status}</p>}</form></MarketingSection></AdvisorPublicShell>}

const dashboardNav=[["總覽","/advisor/dashboard"],["個人品牌","/advisor/profile"],["服務","/advisor/services"],["可預約時間","/advisor/availability"],["預約","/advisor/bookings"],["客戶","/advisor/customers"],["評價","/advisor/reviews"],["媒體","/advisor/media"],["收入","/advisor/earnings"],["契約","/advisor/contracts"],["帳戶","/advisor/account"]];
function AdvisorShell({children}:{children:React.ReactNode}){return <div className="advisor-console"><aside><Link to="/advisor/dashboard" className="advisor-console-brand"><Sparkle/>顧問工作台</Link><nav>{dashboardNav.map(([l,to])=><Link to={to} key={to}>{l}</Link>)}</nav></aside><main>{children}</main></div>}
export function AdvisorLoginPage(){const nav=useNavigate(),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await advisorApi<any>("/api/advisor/login",{method:"POST",body:JSON.stringify({phone:f.get("phone"),password:f.get("password")})});sessionStorage.setItem("baiye_advisor_csrf",r.csrf_token);nav("/advisor/dashboard")}catch(e:any){setError(e.message)}}return <AdvisorPublicShell><main className="advisor-auth"><form onSubmit={submit}><UserCircle/><h1>老師／顧問登入</h1><p>使用既有百工會員手機與 8 位數字會員密碼登入。</p><label>手機號碼<input name="phone" inputMode="tel" required/></label><label>8 位數字會員密碼<input name="password" type="password" inputMode="numeric" pattern="[0-9]{8}" required/></label><button className="btn btn-primary btn-lg">登入顧問工作台</button>{error&&<p role="alert">{error}</p>}</form></main></AdvisorPublicShell>}
export function AdvisorDashboardPage(){const [data,setData]=useState<any>(null);useEffect(()=>{advisorApi("/api/advisor/dashboard").then(setData).catch(()=>setData({error:true}))},[]);const cards=useMemo(()=>data?.metrics?[['本月預約',data.metrics.month_bookings],['今日預約',data.metrics.today],['待確認',data.metrics.pending],['已完成',data.metrics.completed],['本月有效服務',data.metrics.valid_month],['目前分潤',`${data.metrics.commission_rate_bp/100}%`],['預估可結算',twd(data.metrics.estimated_settlement_minor)],['評分',data.metrics.rating],['平台服務等級',data.metrics.star_level?.label||'尚未取得'],['Profile 完成度',`${data.metrics.profile_completeness}%`]]:[] as any[],[data]);return <AdvisorShell><header className="advisor-console-title"><span>STAGING</span><h1>顧問儀表板</h1><p>所有付款及匯款均為測試／準備狀態。</p></header><div className="advisor-metric-grid">{cards.map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>{data?.error&&<p>請先登入顧問工作台。</p>}</AdvisorShell>}
export function AdvisorWorkspacePage({section}:{section:string}){const labels:Record<string,string>={profile:'個人品牌',services:'服務管理',availability:'可預約時間',bookings:'預約管理',customers:'客戶',reviews:'評價',media:'AI 介紹影片與媒體',earnings:'收入與結算',contracts:'合作契約',account:'帳戶'};return <AdvisorShell><header className="advisor-console-title"><span>STAGING</span><h1>{labels[section]}</h1><p>此模組遵循顧問獨立資料範圍、內容審核與稽核規則。</p></header><PremiumCard><CheckCircle/><h2>{labels[section]} V1</h2><p>{section==='media'?'腳本、肖像授權、人工審核、Admin 上傳與發布流程；未連接影片 Provider，不會假裝生成。':section==='earnings'?'逐筆顯示售價、分潤快照、退款扣回與結算狀態；真實匯款維持停用。':section==='contracts'?'契約版本 advisor_partner_v1_0；法律狀態 pending_review，Staging 可測簽署、PDF 與 Evidence。':'功能已建立於 Advisor Domain，資料不與 Merchant 混用。'}</p></PremiumCard></AdvisorShell>}
