import { ArrowRight, CreditCard, Gift, HandCoins, Motorcycle } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { PublicLayout, SectionHeading } from "../components";
import { adminApi } from "../admin-auth-client";
const API=(import.meta.env.VITE_PLATFORM_API_URL||"https://chuang-baiye-ai.baiye-platform.workers.dev").replace(/\/$/,"");
async function publicApi(path:string){const r=await fetch(`${API}${path}`),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"服務暫時無法使用。");return d}
export function MemberBenefitsPage(){const [items,setItems]=useState<Array<{merchant_id:string;display_name:string;code:string}>>([]),[error,setError]=useState("");useEffect(()=>{void publicApi("/api/member-benefits/merchants").then(d=>setItems(d.items||[])).catch(e=>setError(e.message))},[]);return <PublicLayout><main className="section growth-public-page"><div className="container"><SectionHeading eyebrow="會員專屬" title="加入會員領 NT$100 禮券" description="掃碼加入已開通活動的合作商家會員，符合活動資格即可取得百元會員禮券。"/>{error&&<p className="growth-alert">{error}</p>}{items.length===0?<div className="growth-empty"><Gift/><h2>目前尚無已啟用活動商家</h2><p>商家完成設定與驗收後，將在此公開顯示。</p></div>:<div className="growth-card-grid">{items.map(x=><article key={x.merchant_id}><Gift/><h2>{x.display_name}</h2><p>禮券由商家提供，期限與最低消費依活動條款為準。</p><Link className="btn btn-primary" to={`/q/${x.code}`}>掃碼入會與點餐 <ArrowRight/></Link></article>)}</div>}<p className="legal-hint">會員禮券條款：DRAFT_FOR_LEGAL_REVIEW</p></div></main></PublicLayout>}
export function BusinessFinancingPage(){const [items,setItems]=useState<Array<{id:string;brand_name:string;institution_type:string;official_domain:string}>>([]),[error,setError]=useState("");useEffect(()=>{void publicApi("/api/financing/partners").then(d=>setItems(d.items||[])).catch(e=>setError(e.message))},[]);return <PublicLayout><main className="section growth-public-page"><div className="container"><SectionHeading eyebrow="商家營運支持" title="商家融資合作專區" description="提供經審核合作機構資訊及申請轉介，實際條件以合作機構審核與正式契約為準。"/><div className="growth-disclosure"><HandCoins/><p>創百業智慧鏈僅提供合作機構資訊展示及申請轉介，不直接提供貸款、不決定核貸結果、不保證過件，不代收借貸本金、利息或任何保證金。</p></div>{error&&<p className="growth-alert">{error}</p>}{items.length===0?<div className="growth-empty"><h2>目前沒有通過審核並公開的合作機構</h2><p>未驗證或法務尚未核准的機構不會顯示。</p></div>:<div className="growth-card-grid">{items.map(x=><article key={x.id}><h2>{x.brand_name}</h2><p>{x.institution_type}</p><a className="btn btn-outline" href={x.official_domain} target="_blank" rel="noopener noreferrer">查看官方網站</a></article>)}</div>}<p className="legal-hint">融資轉介及個資分享條款：DRAFT_FOR_LEGAL_REVIEW</p></div></main></PublicLayout>}
export function AdminFinancingPage(){const [partners,setPartners]=useState<Array<Record<string,unknown>>>([]),[leads,setLeads]=useState<Array<Record<string,unknown>>>([]),[message,setMessage]=useState("");useEffect(()=>{void Promise.all([adminApi("/api/admin/financing/partners"),adminApi("/api/admin/financing/leads")]).then(([a,b])=>{setPartners(a.items||[]);setLeads(b.items||[])}).catch(e=>setMessage(e.message))},[]);return <main className="admin-page growth-admin-page"><div className="container"><h1>商家融資合作管理</h1><div className="growth-disclosure"><CreditCard/><strong>所有新機構預設停用；禁止私人放款與 P2P 媒合。</strong></div>{message&&<p className="growth-alert">{message}</p>}<h2>合作機構</h2>{partners.length===0?<div className="growth-empty">尚無已建立機構。</div>:<div className="growth-card-grid">{partners.map((x,i)=><article key={String(x.id||i)}><h3>{String(x.brand_name||"")}</h3><p>{String(x.verified_status||"pending")}／{String(x.legal_review_status||"pending")}</p></article>)}</div>}<h2>轉介 Leads</h2><p>列表 API 僅回傳非敏感營運欄位，不回傳加密聯絡資料。</p><div className="growth-empty">{leads.length} 筆待管理紀錄</div><Link to="/admin/ordering" className="btn btn-outline"><Motorcycle/>付款與外送管理</Link></div></main>}
