import { Alarm, Buildings, ChartBar, CheckSquare, CirclesFour, ClipboardText, ClockCounterClockwise, CurrencyDollar, FileText, Gear, Globe, House, ListChecks, MagnifyingGlass, Monitor, ShieldCheck, SignOut, Siren, UserCircle, UsersThree, X } from "@phosphor-icons/react";
import { useEffect,useState,type FormEvent,type ReactNode } from "react";
import { Link,Navigate,useLocation,useNavigate,useParams } from "react-router-dom";
import { PlatformLogo } from "../components";
import { ownerApi,ownerLogin,ownerLogout,ownerSession } from "../owner-admin-client";
import "../owner-admin.css";

type OwnerUser={email:string;name:string;role:"OWNER_ADMIN"};
type Json=Record<string,any>;
const nav=[
  ["","營運總覽",House],["merchants","客戶／商家",UsersThree],["contracts","承攬合約",FileText],["projects","網站建置",Globe],["services","功能服務",CirclesFour],["receivables","收款管理",CurrencyDollar],["tasks","工作進度",CheckSquare],["documents","文件中心",ClipboardText],["reports","營運報表",ChartBar],["alerts","異常／提醒",Siren],["monitors","系統監控",Monitor],["audit","操作紀錄",ClockCounterClockwise],["settings","系統設定",Gear],["security","管理員安全",ShieldCheck],
] as const;
const label:Record<string,string>={NEW:"新客戶",IN_PROGRESS:"製作中",WAITING_CLIENT:"等待資料",WAITING_PAYMENT:"等待付款",WAITING_APPROVAL:"等待驗收",COMPLETED:"已完成",PAUSED:"暫停",TERMINATED:"終止",NOT_STARTED:"未開始",WAITING_CLIENT_DATA:"等待資料",TESTING:"測試中",PRODUCTION:"Production",DRAFT:"草稿",WAITING_SIGNATURE:"等待簽署",SIGNED:"已簽署",ACTIVE:"進行中",UNPAID:"未付款",PARTIAL:"部分付款",PAID:"已付款",OVERDUE:"逾期",WAIVED:"免除",TODO:"待辦",BLOCKED:"受阻",DONE:"完成",WAITING:"等待",NOT_ENABLED:"未啟用",SETUP:"設定中",HEALTHY:"正常",WARNING:"注意",DOWN:"離線",UNKNOWN:"未知",NOT_APPLICABLE:"不適用",CLIENT_DATA:"客戶資料",LOGO:"Logo",BRAND:"品牌資料",DOMAIN:"網域",HOME:"首頁",PRODUCTS_SERVICES:"商品／服務",LINE_OA:"LINE OA",AI_CUSTOMER_SERVICE:"AI 智能客服",WEBSITE_BOOKING:"網站預約",MEMBERSHIP:"會員",POSLESS_ORDERING:"免POS機點餐",PAYMENT:"金流",CLIENT_ACCEPTANCE:"客戶驗收"};
const show=(v:any)=>v===null||v===undefined||v===""?"尚未填寫":label[String(v)]||String(v);
const money=(v:any)=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(Number(v||0)/100);

export function OwnerLoginPage(){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[otp,setOtp]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const navigate=useNavigate();
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await ownerLogin(email,password,otp);navigate("/owner-admin",{replace:true});}catch(err){setError(err instanceof Error?err.message:"登入失敗。");}finally{setBusy(false);}};
  useEffect(()=>{document.querySelector('meta[name="robots"]')?.setAttribute("content","noindex,nofollow");},[]);
  return <main className="owner-login"><section><PlatformLogo/><span>BAIYE OWNER ADMIN</span><h1>創百業總管理中心</h1><p>Owner 專用入口。登入需要平台密碼與六位數 MFA 驗證碼。</p><form onSubmit={submit}>{error&&<div className="owner-error" role="alert">{error}</div>}<label>Owner Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>密碼<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><label>MFA 驗證碼<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} autoComplete="one-time-code"/></label><button disabled={busy}>{busy?"安全驗證中…":"進入總管理中心"}</button></form><small>受 Cloudflare Access 與 Owner Authentication 雙層保護</small></section></main>;
}

export function OwnerRoute({children}:{children:ReactNode}){const [state,setState]=useState<"loading"|"ready"|"denied">("loading"),[user,setUser]=useState<OwnerUser>();useEffect(()=>{ownerSession().then(d=>{setUser(d.user);setState("ready");}).catch(()=>setState("denied"));},[]);if(state==="loading")return <main className="owner-loading">正在驗證 Owner Session…</main>;if(state==="denied")return <Navigate to="/owner-admin/login" replace/>;return <OwnerShell user={user!}>{children}</OwnerShell>;}

function OwnerShell({user,children}:{user:OwnerUser;children:ReactNode}){const [open,setOpen]=useState(false),location=useLocation(),navigate=useNavigate();const current=location.pathname.split("/")[2]||"";return <div className="owner-shell"><aside className={open?"open":""}><header><PlatformLogo/><div><strong>創百業</strong><span>總管理中心</span></div><button onClick={()=>setOpen(false)} aria-label="關閉選單"><X/></button></header><nav>{nav.map(([path,text,Icon])=><Link className={current===path?"active":""} to={`/owner-admin${path?`/${path}`:""}`} onClick={()=>setOpen(false)} key={path}><Icon/><span>{text}</span></Link>)}</nav><footer><UserCircle/><div><strong>{user.name}</strong><span>{user.role}</span></div><button aria-label="登出" onClick={()=>void ownerLogout().then(()=>navigate("/owner-admin/login",{replace:true}))}><SignOut/></button></footer></aside>{open&&<button className="owner-backdrop" onClick={()=>setOpen(false)} aria-label="關閉選單"/>}<section className="owner-area"><header className="owner-top"><button onClick={()=>setOpen(true)} aria-label="開啟選單"><ListChecks/></button><div><strong>創百業智慧鏈｜總管理中心</strong><span>Production 營運與客戶管理</span></div><ShieldCheck weight="fill"/></header><main>{children}</main></section></div>}

function useData(path:string){const [data,setData]=useState<any>(),[error,setError]=useState("");const load=()=>ownerApi(path).then(setData).catch(e=>setError(e.message));useEffect(()=>{void load();},[path]);return{data,error,reload:load};}
const Badge=({value}:{value:any})=><span className={`owner-badge status-${String(value||"UNKNOWN").toLowerCase()}`}>{show(value)}</span>;
const Empty=({text="目前沒有資料"}:{text?:string})=><div className="owner-empty">{text}</div>;

export function OwnerDashboard(){const{data,error}=useData("/api/owner/dashboard");if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const m=data.metrics||{};const metrics=[["商家總數",m.merchant_total,Buildings],["進行中案件",m.active_cases,ClipboardText],["網站建置中",m.websites_building,Globe],["等待客戶資料",m.waiting_client,Alarm],["等待簽約",m.waiting_signature,FileText],["待收款",m.pending_receivables,CurrencyDollar],["本月新增客戶",m.new_this_month,UsersThree],["Production 異常",m.production_alerts,Siren],["今日待辦",m.tasks_today,CheckSquare]];return <Page title="營運總覽" subtitle="數字直接由 Production D1 即時計算"><section className="owner-metrics">{metrics.map(([t,v,I])=>{const Icon=I as typeof Buildings;return <article key={String(t)}><Icon/><span>{t}</span><strong>{Number(v||0)}</strong></article>})}</section><div className="owner-dashboard-grid"><Panel title="最近案件"><div className="owner-list">{data.recent.length?data.recent.map((x:Json)=><Link to={`/owner-admin/merchants/${x.id}`} key={x.id}><div><strong>{x.name}</strong><small>{show(x.next_step)}</small></div><Badge value={x.website_status}/><time>{x.updated_at}</time></Link>):<Empty/>}</div></Panel><Panel title="待處理事項"><div className="owner-list">{data.tasks.length?data.tasks.map((x:Json)=><div key={x.id}><div><strong>{x.title}</strong><small>{show(x.merchant_name)} · {show(x.due_date)}</small></div><Badge value={x.status}/></div>):<Empty text="目前沒有未完成事項"/>}</div></Panel><Panel title="異常提醒"><div className="owner-list">{data.alerts.length?data.alerts.map((x:Json)=><div key={x.merchant_id}><div><strong>{x.merchant_name}</strong><small>{show(x.url)} · {show(x.last_error)}</small></div><Badge value={x.health_status}/></div>):<Empty text="目前沒有異常提醒"/>}</div></Panel></div></Page>}

export function OwnerMerchants(){const[q,setQ]=useState(""),[status,setStatus]=useState(""),{data,error}=useData(`/api/owner/merchants?q=${encodeURIComponent(q)}&status=${status}`);return <Page title="客戶／商家" subtitle="沿用現有 Production merchant_id，不建立重複商家"><div className="owner-filters"><label><MagnifyingGlass/><input placeholder="搜尋商家、編號或 Email" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部狀態</option>{["NEW","IN_PROGRESS","WAITING_CLIENT","WAITING_PAYMENT","WAITING_APPROVAL","COMPLETED","PAUSED","TERMINATED"].map(x=><option value={x} key={x}>{show(x)}</option>)}</select></div>{error?<ErrorBox text={error}/>:!data?<Loading/>:<div className="owner-table-cards">{data.items.map((x:Json)=><Link to={`/owner-admin/merchants/${x.merchant_id}`} key={x.merchant_id}><div><strong>{x.business_name}</strong><small>{x.merchant_code} · {show(x.owner_name)}</small></div><dl><dt>方案</dt><dd>{show(x.plan_code)}</dd><dt>案件</dt><dd><Badge value={x.status}/></dd><dt>網站</dt><dd><Badge value={x.website_status}/></dd><dt>合約</dt><dd><Badge value={x.contract_status}/></dd><dt>收款</dt><dd><Badge value={x.payment_status}/></dd></dl><time>更新 {x.updated_at}</time></Link>)}</div>}</Page>}

const merchantTabs=["基本資料","合約","收款","網站","LINE","AI 客服","免POS機點餐","網站預約","文件","工作進度","系統紀錄"];
export function OwnerMerchantDetail(){const{id=""}=useParams(),[tab,setTab]=useState(0),{data,error,reload}=useData(`/api/owner/merchants/${encodeURIComponent(id)}`);if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const m=data.merchant;return <Page title={m.business_name} subtitle={`merchant_id：${m.merchant_id}`}><div className="owner-detail-head"><Badge value={m.lifecycle_status||"NEW"}/><span>{show(m.merchant_code)}</span><span>最後更新 {m.updated_at}</span></div><div className="owner-tabs">{merchantTabs.map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}</div><Panel title={merchantTabs[tab]}>{tab===0&&<KeyValues data={{business_name:m.business_name,legal_name:m.legal_name,owner_name:m.owner_name,contact_name:m.contact_name,phone:m.phone,mobile:m.mobile,email:m.email,tax_id:m.tax_id,address:m.address,LINE:m.line_contact,notes:m.notes,created_at:m.created_at,updated_at:m.updated_at}}/>}{tab===1&&<Records items={data.contracts} type="contract"/>}{tab===2&&<Records items={data.receivables} type="money"/>}{tab===3&&<WebsiteProject data={data} merchantId={id} reload={reload}/>} {tab===4&&<KeyValues data={{line_oa_name:data.assets?.line_oa_name,line_basic_id:data.assets?.line_basic_id,liff_id:data.assets?.liff_id}}/>}{tab===5&&<Service data={data.services} code="ai_customer_service"/>}{tab===6&&<Service data={data.services} code="posless_ordering"/>}{tab===7&&<Service data={data.services} code="website_booking"/>}{tab===8&&<Records items={data.documents}/>} {tab===9&&<Records items={data.tasks}/>} {tab===10&&<Records items={data.audit}/>}</Panel></Page>}

function WebsiteProject({data,merchantId,reload}:{data:any;merchantId:string;reload:()=>void}){const[status,setStatus]=useState(data.project?.status||"NOT_STARTED"),[next,setNext]=useState(data.project?.next_step||""),[busy,setBusy]=useState(false);const create=async()=>{setBusy(true);try{await ownerApi("/api/owner/projects",{method:"POST",body:JSON.stringify({merchant_id:merchantId})});reload();}finally{setBusy(false);}};const save=async()=>{setBusy(true);try{await ownerApi(`/api/owner/projects/${data.project.id}`,{method:"PATCH",body:JSON.stringify({status,next_step:next})});reload();}finally{setBusy(false);}};if(!data.project)return <div><Empty text="尚未建立網站建置案件"/><button className="owner-action" onClick={()=>void create()} disabled={busy}>建立網站案件與 Checklist</button></div>;return <div><form className="owner-edit-grid" onSubmit={e=>{e.preventDefault();void save();}}><label>案件狀態<select value={status} onChange={e=>setStatus(e.target.value)}>{['NOT_STARTED','WAITING_CLIENT_DATA','IN_PROGRESS','TESTING','WAITING_APPROVAL','PRODUCTION','COMPLETED','PAUSED'].map(x=><option value={x} key={x}>{show(x)}</option>)}</select></label><label>下一步<input value={next} onChange={e=>setNext(e.target.value)} placeholder="尚未填寫"/></label><button disabled={busy}>儲存案件進度</button></form><h3>建置 Checklist</h3><div className="owner-checklist">{data.checklist.map((item:Json)=><label key={item.id}><span><strong>{show(item.item_code)}</strong><small>{show(item.note)}</small></span><select value={item.status} onChange={async e=>{await ownerApi(`/api/owner/checklist/${item.id}`,{method:"PATCH",body:JSON.stringify({status:e.target.value,note:item.note})});reload();}}>{['TODO','WAITING','IN_PROGRESS','DONE','BLOCKED','NOT_APPLICABLE'].map(x=><option value={x} key={x}>{show(x)}</option>)}</select></label>)}</div></div>}
function Service({data,code}:{data:any[];code:string}){const item=data.find(x=>x.service_code===code);return item?<KeyValues data={item}/>:<Empty text="尚未啟用"/>}

const endpoints:Record<string,{title:string;path:string;icon:any}>={contracts:{title:"承攬合約",path:"/api/owner/contracts",icon:FileText},projects:{title:"網站建置",path:"/api/owner/projects",icon:Globe},services:{title:"功能服務",path:"/api/owner/services",icon:CirclesFour},receivables:{title:"收款管理",path:"/api/owner/receivables",icon:CurrencyDollar},tasks:{title:"工作進度",path:"/api/owner/tasks",icon:CheckSquare},documents:{title:"文件中心",path:"/api/owner/documents",icon:ClipboardText},monitors:{title:"系統監控",path:"/api/owner/monitors",icon:Monitor},audit:{title:"操作紀錄",path:"/api/owner/audit",icon:ClockCounterClockwise}};
export function OwnerModulePage({kind}:{kind:string}){const config=endpoints[kind];const{data,error,reload}=useData(config.path);return <Page title={config.title} subtitle="Production 實際資料；缺少欄位顯示尚未填寫">{kind==="tasks"?<TaskForm reload={reload}/>:['contracts','projects','services','receivables'].includes(kind)&&<ModuleCreateForm kind={kind} reload={reload}/>} {error?<ErrorBox text={error}/>:!data?<Loading/>:<Records items={data.items} type={kind}/>}</Page>}
function TaskForm({reload}:{reload:()=>void}){const[title,setTitle]=useState(""),[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await ownerApi("/api/owner/tasks",{method:"POST",body:JSON.stringify({title,priority:"NORMAL"})});setTitle("");reload();}finally{setBusy(false);}};return <form className="owner-quick-form" onSubmit={submit}><input required placeholder="新增待辦事項" value={title} onChange={e=>setTitle(e.target.value)}/><button disabled={busy}>{busy?"建立中…":"新增待辦"}</button></form>}
function ModuleCreateForm({kind,reload}:{kind:string;reload:()=>void}){const[merchants,setMerchants]=useState<Json[]>([]),[merchantId,setMerchantId]=useState(""),[name,setName]=useState(""),[amount,setAmount]=useState(""),[service,setService]=useState("website"),[status,setStatus]=useState("ACTIVE"),[dueDate,setDueDate]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{ownerApi("/api/owner/merchants").then(d=>{setMerchants(d.items||[]);setMerchantId(d.items?.[0]?.merchant_id||"");}).catch(()=>setNotice("無法讀取商家清單。"));},[]);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setNotice("");try{if(kind==="projects")await ownerApi("/api/owner/projects",{method:"POST",body:JSON.stringify({merchant_id:merchantId})});if(kind==="contracts")await ownerApi("/api/owner/contracts",{method:"POST",body:JSON.stringify({merchant_id:merchantId,contract_name:name,contract_amount:Math.round(Number(amount)*100)})});if(kind==="receivables")await ownerApi("/api/owner/receivables",{method:"POST",body:JSON.stringify({merchant_id:merchantId,amount_due:Math.round(Number(amount)*100),due_date:dueDate||null})});if(kind==="services")await ownerApi(`/api/owner/services/${encodeURIComponent(merchantId)}/${service}`,{method:"PUT",body:JSON.stringify({status})});setName("");setAmount("");setNotice("已寫入 Production 資料並建立操作紀錄。");reload();}catch(err){setNotice(err instanceof Error?err.message:"儲存失敗。");}finally{setBusy(false);}};return <form className="owner-create-form" onSubmit={submit}><select required value={merchantId} onChange={e=>setMerchantId(e.target.value)}><option value="">選擇商家</option>{merchants.map(x=><option value={x.merchant_id} key={x.merchant_id}>{x.business_name}</option>)}</select>{kind==="contracts"&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="合約名稱"/>}{['contracts','receivables'].includes(kind)&&<input required min="0" step="1" type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={kind==="contracts"?"合約金額（元）":"應收金額（元）"}/>} {kind==="receivables"&&<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/>} {kind==="services"&&<><select value={service} onChange={e=>setService(e.target.value)}>{['website','ai_customer_service','line_oa','membership','website_booking','posless_ordering','contract_system','payment','inventory','other'].map(x=><option value={x} key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}>{['NOT_ENABLED','SETUP','TESTING','ACTIVE','PAUSED'].map(x=><option value={x} key={x}>{show(x)}</option>)}</select></>}<button disabled={busy||!merchantId}>{busy?"儲存中…":"新增"}</button>{notice&&<small>{notice}</small>}</form>}
export function OwnerStaticPage({kind}:{kind:string}){const content:Record<string,[string,string]>={reports:["營運報表","V1 報表由 Dashboard 與各模組的 Production 資料即時計算。"],alerts:["異常／提醒","異常資料集中於系統監控；沒有建立假的告警。"],settings:["系統設定","高風險設定與 Production 操作尚未開放，避免建立無效控制。"],security:["管理員安全","角色為 OWNER_ADMIN；Session 使用 Secure、HttpOnly、SameSite Cookie，所有寫入均檢查 CSRF 並寫入 Audit Log。Passkey 資料欄位已預留。"]};const[t,d]=content[kind];return <Page title={t} subtitle={d}><Panel title="V1 狀態"><p>{d}</p></Panel></Page>}

function Page({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <><header className="owner-page-head"><div><span>BAIYE OWNER ADMIN</span><h1>{title}</h1><p>{subtitle}</p></div></header>{children}</>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="owner-panel"><h2>{title}</h2>{children}</section>}
function Loading(){return <div className="owner-empty">正在讀取 Production 資料…</div>}
function ErrorBox({text}:{text:string}){return <div className="owner-error">{text}</div>}
function KeyValues({data}:{data:Json}){return <dl className="owner-kv">{Object.entries(data).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}</dl>}
function Records({items,type}:{items:any[];type?:string}){if(!items?.length)return <Empty/>;return <div className="owner-records">{items.map((x,i)=><article key={x.id||i}><header><strong>{show(x.merchant_name||x.contract_name||x.title||x.filename||x.service_code||x.action||x.item_code||x.id)}</strong>{(x.status||x.contract_status||x.payment_status||x.health_status)&&<Badge value={x.status||x.contract_status||x.payment_status||x.health_status}/>}</header><div>{Object.entries(x).filter(([k])=>!["id","merchant_name","title","status","contract_status","payment_status","health_status"].includes(k)).slice(0,8).map(([k,v])=><span key={k}><b>{k}</b>{type==="money"&&k.includes("amount")?money(v):show(v)}</span>)}</div></article>)}</div>}
