import { useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { QRCodeSVG } from "qrcode.react";

const API = "https://chuang-baiye-ai.baiye-platform.workers.dev";
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat("zh-TW", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const money = (value: unknown) => new Intl.NumberFormat("zh-TW", { style: "currency", currency: "TWD", maximumFractionDigits: 0 }).format(Number(value || 0));
function errorText(value: unknown) { return value instanceof Error && value.message ? value.message : "系統暫時無法完成此操作，請稍後再試。"; }
async function api(path: string, init: RequestInit = {}) {
  const response = await fetch(`${API}${path}`, { credentials: "include", ...init, headers: { "content-type": "application/json", ...init.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || "系統暫時無法完成此操作，請稍後再試。");
  return data;
}
async function adminApi(path: string, token: string, init: RequestInit = {}) { return api(path, { ...init, headers: { authorization: `Bearer ${token}`, ...init.headers } }); }
function copyText(value: string) { return navigator.clipboard?.writeText(value); }

export function PartnerLanding() {
  return <main className="partner-shell"><section className="partner-hero"><p>創百業智慧鏈｜夥伴中心</p><h1>以成果合作，共創百業數位升級</h1><p>獨立承攬／居間合作夥伴計畫，不設打卡、工時、排班或工作地點管理。</p><Link className="btn btn-primary" to="/partner/apply">加入合作夥伴</Link> <Link className="btn btn-outline" to="/partner/login">夥伴登入</Link></section></main>;
}

export function PartnerApply() {
  const [form, setForm] = useState<any>({ legal_name: "", display_name: "", email: "", phone: "", company_name: "", tax_id: "", note: "", consent: false });
  const [message, setMessage] = useState(""); const [duplicate, setDuplicate] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); setDuplicate(false); try { const result = await api("/api/partner/apply", { method: "POST", body: JSON.stringify(form) }); setMessage(`申請已送出，合作夥伴編號 ${result.partner_code}。我們會在完成審核後通知您。`); } catch (error) { const text = errorText(error); setMessage(text); setDuplicate(text.includes("已申請過")); } };
  return <main className="partner-shell partner-form"><h1>業務合作申請</h1><p>送出後由平台管理員審核；核准後會收到安全啟用連結。</p><form onSubmit={submit}>{[["legal_name", "法定姓名"], ["display_name", "顯示名稱"], ["email", "Email"], ["phone", "手機"], ["company_name", "公司／行號（選填）"], ["tax_id", "統編（選填）"], ["note", "合作經驗／備註（選填）"]].map(([key, label]) => <label key={key}>{label}<input required={!key.includes("company") && !key.includes("tax") && !key.includes("note")} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label className="partner-consent"><input type="checkbox" required checked={form.consent} onChange={(event) => setForm({ ...form, consent: event.target.checked })} />我了解本合作屬獨立承攬／居間合作，非甲方僱員。</label><button className="btn btn-primary">送出申請</button></form>{message && <section className="partner-message"><p>{message}</p>{duplicate && <p><Link className="btn btn-primary btn-sm" to="/partner/login">前往夥伴登入</Link> <Link className="btn btn-outline btn-sm" to="/partner">返回夥伴中心</Link></p>}</section>}</main>;
}

export function PartnerActivate() {
  const [params] = useSearchParams(); const token = params.get("token") || "";
  const [profile, setProfile] = useState<any>(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!token) { setMessage("缺少啟用連結。請向管理員索取新的啟用通知。"); setLoading(false); return; } api("/api/partner/invite/validate", { method: "POST", body: JSON.stringify({ token }) }).then(setProfile).catch((error) => setMessage(errorText(error))).finally(() => setLoading(false)); }, [token]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); if (password.length < 12) return setMessage("密碼至少需要 12 個字元。"); if (password !== confirm) return setMessage("兩次輸入的密碼不一致。"); try { await api("/api/partner/accept-invite", { method: "POST", body: JSON.stringify({ token, password }) }); setMessage("帳號已成功啟用。請使用您的 Email 與新密碼登入夥伴中心。"); setProfile(undefined); } catch (error) { setMessage(errorText(error)); } };
  return <main className="partner-shell partner-form"><h1>啟用合作夥伴帳號</h1>{loading && <p>正在驗證啟用連結…</p>}{profile && <><section className="partner-info"><strong>{profile.display_name}</strong><span>{profile.legal_name} · {profile.email}</span><small>此連結有效至 {formatDate(profile.expires_at)}</small></section><form onSubmit={submit}><label>設定密碼<input type="password" minLength={12} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><label>再次確認密碼<input type="password" minLength={12} autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} required /></label><small>密碼至少 12 個字元，請勿與其他服務共用。</small><button className="btn btn-primary">完成啟用</button></form></>}{message && <section className="partner-message"><p>{message}</p>{!profile && message.includes("成功啟用") && <Link className="btn btn-primary btn-sm" to="/partner/login">前往夥伴登入</Link>}</section>}</main>;
}

export function PartnerReferralJoin() {
  const [params] = useSearchParams(), referral = params.get("ref") || ""; const [form, setForm] = useState({ lead_name: "", lead_email: "", lead_phone: "" }); const [message, setMessage] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api("/api/partner/attribution", { method: "POST", body: JSON.stringify({ ...form, referral_code: referral }) }); setMessage("已收到您的需求，專屬合作夥伴將協助您確認。"); } catch (error) { setMessage(errorText(error)); } };
  return <main className="partner-shell partner-form"><h1>開始您的數位升級</h1><p>留下聯絡方式後，我們會由專屬合作夥伴協助了解需求。</p><form onSubmit={submit}><label>姓名<input required value={form.lead_name} onChange={(event) => setForm({ ...form, lead_name: event.target.value })} /></label><label>Email<input type="email" value={form.lead_email} onChange={(event) => setForm({ ...form, lead_email: event.target.value })} /></label><label>手機<input value={form.lead_phone} onChange={(event) => setForm({ ...form, lead_phone: event.target.value })} /></label><button className="btn btn-primary">送出需求</button></form>{message && <p className="partner-message">{message}</p>}</main>;
}

export function PartnerLogin() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); try { await api("/api/partner/login", { method: "POST", body: JSON.stringify({ email, password }) }); window.location.hash = "#/partner/dashboard"; } catch (error) { setMessage(errorText(error)); } };
  return <main className="partner-shell partner-form"><h1>夥伴登入</h1><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>密碼<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="btn btn-primary">登入夥伴中心</button></form>{message && <section className="partner-message"><p>{message}</p><Link to="/partner/apply">尚未申請？前往業務合作申請</Link></section>}</main>;
}

export function PartnerDashboard() {
  const [data, setData] = useState<any>(); const [message, setMessage] = useState("");
  const load = () => api("/api/partner/dashboard").then(setData).catch((error) => setMessage(errorText(error)));
  useEffect(() => { void load(); }, []);
  const download = async () => { if (!data?.contract?.signature_id) return; try { const response = await fetch(`${API}/api/partner/contracts/${data.contract.signature_id}/pdf`, { credentials: "include" }); if (!response.ok) throw new Error((await response.json()).error); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `已簽合作契約-${data.contract.version || ""}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { setMessage(errorText(error)); } };
  if (message && !data) return <main className="partner-shell"><section className="partner-message"><p>{message}</p><Link className="btn btn-primary" to="/partner/login">前往夥伴登入</Link></section></main>;
  if (!data) return <main className="partner-shell">載入中…</main>;
  const referral = `https://baiyeconnect.com/#/join?ref=${data.partner.referral_code}`;
  return <main className="partner-shell"><h1>{data.partner.display_name} 的合作儀表板</h1>{data.contract?.signed ? <section className="partner-status success"><strong>契約已簽署</strong><span>{data.contract.version} · {formatDate(data.contract.signed_at)}</span><button className="btn btn-outline btn-sm" onClick={download}>下載我的已簽契約 PDF</button></section> : <section className="partner-status warning"><strong>您尚未完成合作契約簽署</strong><span>完成簽署後，您可保留完整且可查驗的電子契約與 PDF。</span><Link className="btn btn-primary btn-sm" to="/partner/contract">立即簽署合作契約</Link></section>}<section className="partner-cards">{[["累計有效成交", data.partner.total_valid_sales], ["累計成交金額", money(data.partner.total_sales_amount)], ["目前級距", money(data.current_tier)], ["可結算獎金", money(data.commissions.payable)]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="partner-detail"><div><h2>專屬推薦連結</h2><input readOnly value={referral} /><button className="btn btn-outline" onClick={() => void copyText(referral)}>複製</button></div><QRCodeSVG value={referral} size={150} /></section>{message && <p className="partner-message">{message}</p>}</main>;
}

export function PartnerContract() {
  const [contract, setContract] = useState<any>(); const [name, setName] = useState(""); const [checks, setChecks] = useState([false, false, false]); const [message, setMessage] = useState(""); const canvas = useRef<HTMLCanvasElement>(null); const strokes = useRef<number[][][]>([]); const drawing = useRef(false);
  useEffect(() => { api("/api/partner/contract/current").then(setContract).catch((error) => setMessage(errorText(error))); }, []);
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => [Math.round(event.nativeEvent.offsetX), Math.round(event.nativeEvent.offsetY)];
  const sign = async () => { setMessage(""); try { const result = await api("/api/partner/contract/sign", { method: "POST", body: JSON.stringify({ legal_name: name, read: checks[0], electronic: checks[1], independent: checks[2], signature: JSON.stringify({ strokes: strokes.current }) }) }); setMessage(`合作契約已簽署並保存私有 PDF。文件雜湊：${result.document_hash}`); } catch (error) { setMessage(errorText(error)); } };
  return <main className="partner-shell partner-contract"><h1>線上合作契約</h1>{contract && <><article dangerouslySetInnerHTML={{ __html: contract.content_html }} /><label>重新輸入法定姓名<input value={name} onChange={(event) => setName(event.target.value)} /></label>{["本人已閱讀並理解本合作契約全部內容。", "本人同意以電子方式簽署本契約。", "本人了解本合作為獨立承攬／居間合作，非僱傭關係。"].map((text, index) => <label className="partner-consent" key={text}><input type="checkbox" checked={checks[index]} onChange={(event) => setChecks(checks.map((value, itemIndex) => itemIndex === index ? event.target.checked : value))} />{text}</label>)}<p>手寫簽名</p><canvas ref={canvas} width="420" height="140" onPointerDown={(event) => { drawing.current = true; strokes.current.push([point(event)]); canvas.current?.setPointerCapture(event.pointerId); }} onPointerMove={(event) => { if (!drawing.current) return; const current = point(event), stroke = strokes.current.at(-1); stroke?.push(current); const context = canvas.current?.getContext("2d"); if (stroke && stroke.length > 1) { const previous = stroke.at(-2)!; context?.beginPath(); context?.moveTo(previous[0], previous[1]); context?.lineTo(current[0], current[1]); context?.stroke(); } }} onPointerUp={() => { drawing.current = false; }} onPointerCancel={() => { drawing.current = false; }} /><button className="btn btn-primary" onClick={sign}>確認電子簽署</button></>}{message && <section className="partner-message"><p>{message}</p>{message.includes("已簽署") && <Link className="btn btn-primary btn-sm" to="/partner/dashboard">返回合作儀表板</Link>}</section>}</main>;
}

type Partner = { id: string; partner_code: string; legal_name: string; display_name: string; email: string; phone: string; company_name?: string; tax_id?: string; status: string; approved_at?: string; contract_status: string; contract_signed_at?: string; total_valid_sales: number; total_sales_amount: number; created_at: string };
const statusLabel = (partner: Partner) => partner.status === "pending_contract" ? partner.approved_at ? "已核准，等待啟用" : "待審核" : ({ active: "已啟用", suspended: "已暫停", terminated: "已終止", rejected: "已拒絕" }[partner.status] || partner.status);
export function AdminPartners() {
  const [token, setToken] = useState(() => sessionStorage.getItem("baiye_finance_session") || ""); const [password, setPassword] = useState(""); const [partners, setPartners] = useState<Partner[]>([]); const [message, setMessage] = useState(""); const [invite, setInvite] = useState<{ name: string; url: string; expires_at: string } | null>(null);
  const load = async () => { try { const result = await adminApi("/api/admin/partners", token); setPartners(result.items); } catch (error) { setMessage(errorText(error)); } };
  useEffect(() => { if (token) void load(); }, [token]);
  const login = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); try { const result = await fetch(`${API}/api/finance/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const data = await result.json(); if (!result.ok) throw new Error(data.error || "財務管理員登入失敗。" ); sessionStorage.setItem("baiye_finance_session", data.token); setPassword(""); setToken(data.token); } catch (error) { setMessage(errorText(error)); } };
  const action = async (partner: Partner, name: string) => { setMessage(""); try { const result = await adminApi(`/api/admin/partners/${partner.id}`, token, { method: "PATCH", body: JSON.stringify({ action: name }) }); setMessage(`${partner.display_name}：${statusLabel({ ...partner, status: result.status, approved_at: result.approved_at || partner.approved_at })}`); await load(); } catch (error) { setMessage(errorText(error)); } };
  const createInvite = async (partner: Partner) => { setMessage(""); try { const result = await adminApi(`/api/admin/partners/${partner.id}/invite`, token, { method: "POST" }); setInvite({ name: partner.display_name, url: result.invite_url, expires_at: result.expires_at }); await load(); } catch (error) { setMessage(errorText(error)); } };
  if (!token) return <main className="partner-shell partner-form"><h1>合作夥伴管理</h1><p>請以財務管理員密碼完成後端授權；密碼不會寫入前端程式或保存於瀏覽器。</p><form onSubmit={login}><label>財務管理員密碼<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="btn btn-primary">安全登入合作夥伴管理</button></form>{message && <p className="partner-message">{message}</p>}</main>;
  return <main className="partner-shell partner-admin"><header><div><h1>合作夥伴管理</h1><p>審核、啟用與契約狀態均寫入後端稽核紀錄。</p></div><button className="btn btn-outline btn-sm" onClick={() => { sessionStorage.removeItem("baiye_finance_session"); setToken(""); }}>登出管理授權</button></header>{message && <p className="partner-message">{message}</p>}{invite && <section className="partner-invite"><strong>{invite.name} 的啟用邀請已建立</strong><span>有效至 {formatDate(invite.expires_at)}</span><input readOnly value={invite.url} /><button className="btn btn-primary btn-sm" onClick={() => void copyText(invite.url)}>複製完整啟用網址</button></section>}<div className="partner-table"><div className="partner-table-head"><span>合作夥伴</span><span>聯絡／公司</span><span>申請／狀態</span><span>契約／業績</span><span>操作</span></div>{partners.map((partner) => <article key={partner.id}><div><strong>{partner.display_name}</strong><small>{partner.partner_code} · 法定姓名：{partner.legal_name}</small><small>{partner.email} · {partner.phone}</small></div><div><span>{partner.company_name || "—"}</span><small>統編：{partner.tax_id || "—"}</small></div><div><span>{formatDate(partner.created_at)}</span><b className={`partner-badge status-${partner.status}`}>{statusLabel(partner)}</b></div><div><span>{partner.contract_status === "signed" ? "契約已簽署" : "尚未簽署"}</span><small>{formatDate(partner.contract_signed_at)} · 有效成交 {partner.total_valid_sales} · {money(partner.total_sales_amount)}</small></div><div className="partner-actions">{partner.status === "pending_contract" && !partner.approved_at && <button className="btn btn-primary btn-sm" onClick={() => void action(partner, "approve")}>核准</button>}{partner.status === "pending_contract" && partner.approved_at && <button className="btn btn-primary btn-sm" onClick={() => void createInvite(partner)}>產生啟用邀請</button>}{partner.status === "pending_contract" && <button className="btn btn-outline btn-sm" onClick={() => void action(partner, "reject")}>拒絕</button>}{partner.status === "active" && <button className="btn btn-outline btn-sm" onClick={() => void action(partner, "suspended")}>暫停</button>}{["pending_contract", "active", "suspended"].includes(partner.status) && <button className="btn btn-danger btn-sm" onClick={() => void action(partner, "terminated")}>終止</button>}</div></article>)}</div></main>;
}
