import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import { merchantOrderingApi } from "../qr-ordering-client";

type Session = { user: { merchant_id: string; name: string }; merchant?: { name: string; operation_locked?: boolean }; permissions: string[] };
type Item = { id: string; category_id: string; name: string; price_minor: number; status: string; available: number };
type Option = { id: string; group_id: string; name: string; price_delta_minor: number };
type Group = { id: string; name: string; min_select: number; max_select: number; selection_type: string };
type CartLine = { item: Item; quantity: number; optionIds: string[]; note: string };
const ntd = (minor = 0) => new Intl.NumberFormat("zh-TW", { style: "currency", currency: "TWD", maximumFractionDigits: 0 }).format(minor / 100);

function useMerchantSession() {
  const [session, setSession] = useState<Session | null>(null); const [ready, setReady] = useState(false);
  useEffect(() => { void merchantOrderingApi<Session>("/api/merchant-auth/session").then(setSession).catch(() => setSession(null)).finally(() => setReady(true)); }, []);
  return { session, ready };
}

function Shell({ children }: { children: ReactNode }) {
  const { session, ready } = useMerchantSession();
  if (!ready) return <main className="soft-pos-shell"><p>正在載入商家營運中心…</p></main>;
  if (!session) return <main className="soft-pos-shell"><section className="soft-pos-card"><h1>商家營運中心</h1><p>請先使用已授權的商家帳號登入。</p><Link className="btn btn-primary" to="/merchant-admin/ordering">前往商家登入</Link></section></main>;
  if (session.merchant?.operation_locked) return <main className="soft-pos-shell"><section className="soft-pos-card"><h1>商家營運中心</h1><p>完成商家平台服務契約後，才能使用接單、收款與庫存等正式營運功能。</p><Link className="btn btn-primary" to="/merchant/contract">前往完成契約</Link></section></main>;
  return <>{children}</>;
}

export function MerchantPosHome() {
  const { session, ready } = useMerchantSession(); const [data, setData] = useState<any>(null); const [error, setError] = useState("");
  useEffect(() => { if (!ready || !session) return; void merchantOrderingApi<any>("/api/merchant-pos/overview").then(setData).catch((e) => setError(e.message)); }, [ready, session]);
  if (!ready) return <main className="soft-pos-shell"><p>正在載入…</p></main>;
  if (!session) return <Shell><span /></Shell>;
  if (session.merchant?.operation_locked) return <Shell><span /></Shell>;
  const today = data?.today;
  return <main className="soft-pos-shell"><header className="soft-pos-header"><div><p>商家營運中心</p><h1>{session.merchant?.name || "手機就是你的營運後台"}</h1><small>Web Soft‑POS｜免專用 POS 主機</small></div><Link className="btn btn-primary" to="/merchant/pos/new-order">立即開單</Link></header>{error && <p className="soft-pos-error">{error}</p>}<section className="soft-pos-metrics">{[["今日營收",ntd(today?.revenue_minor)],["今日訂單",today?.orders || 0],["待處理訂單",today?.pending || 0],["已完成訂單",today?.completed || 0],["現金收入",ntd(today?.cash_minor)],["其他付款",ntd(today?.other_minor)],["今日預約",today?.bookings || 0]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="soft-pos-actions"><Link to="/merchant/pos/new-order">立即開單</Link><Link to="/merchant-admin/ordering">掃碼點餐</Link><Link to="/merchant-admin/ordering">新增商品</Link><Link to="/merchant/pos/kitchen">今日訂單／KDS</Link><Link to="/merchant-admin/ordering">桌號 QR</Link></section><section className="soft-pos-columns"><article><h2>熱門商品</h2>{data?.hot_items?.length ? <ol>{data.hot_items.map((x:any)=><li key={x.name}>{x.name}<strong>×{x.quantity}</strong></li>)}</ol> : <p>尚無今日銷售資料。</p>}</article><article><h2>低庫存</h2>{data?.low_stock?.length ? <ul>{data.low_stock.map((x:any)=><li key={x.id}>{x.name}<strong>{x.quantity_minor}</strong></li>)}</ul> : <p>目前沒有低庫存提醒。</p>}</article></section></main>;
}

export function MerchantPosNewOrder() {
  const { session, ready } = useMerchantSession(); const nav=useNavigate(); const [catalog,setCatalog]=useState<any>(null); const [cart,setCart]=useState<CartLine[]>([]); const [selected,setSelected]=useState<Item|null>(null); const [selectedOptions,setSelectedOptions]=useState<string[]>([]); const [method,setMethod]=useState("cash"); const [table,setTable]=useState(""); const [processing,setProcessing]=useState(false); const [message,setMessage]=useState(""); const key=useRef(crypto.randomUUID());
  useEffect(()=>{if(ready&&session)void merchantOrderingApi<any>("/api/merchant-pos/catalog").then(setCatalog).catch(e=>setMessage(e.message));},[ready,session]);
  const optionsFor=(item:Item)=>{const ids=(catalog?.item_option_groups||[]).filter((x:any)=>x.menu_item_id===item.id).map((x:any)=>x.option_group_id); return {groups:(catalog?.option_groups||[]).filter((x:Group)=>ids.includes(x.id)),values:(catalog?.option_values||[]).filter((x:Option)=>ids.includes(x.group_id))};};
  const add=(item:Item, optionIds:string[]=[] )=>{setCart((old)=>{const found=old.find(x=>x.item.id===item.id&&x.optionIds.join(",")===optionIds.join(","));return found?old.map(x=>x===found?{...x,quantity:x.quantity+1}:x):[...old,{item,quantity:1,optionIds,note:""}];});setSelected(null);setSelectedOptions([]);};
  const total=useMemo(()=>cart.reduce((sum,line)=>sum+(line.item.price_minor+(catalog?.option_values||[]).filter((x:Option)=>line.optionIds.includes(x.id)).reduce((v:number,x:Option)=>v+x.price_delta_minor,0))*line.quantity,0),[cart,catalog]);
  const checkout=async()=>{if(!cart.length||processing)return;setProcessing(true);setMessage("");try{const result=await merchantOrderingApi<any>("/api/merchant-pos/orders",{method:"POST",headers:{"idempotency-key":key.current},body:JSON.stringify({items:cart.map(x=>({item_id:x.item.id,quantity:x.quantity,option_value_ids:x.optionIds,note:x.note})),payment_method:method,confirm_payment:true,order_type:table?"dine_in":"takeaway",table_label:table})});setMessage(`訂單 ${result.order_code} 已建立。`);setCart([]);key.current=crypto.randomUUID();}catch(e){setMessage(e instanceof Error?e.message:"無法建立訂單。");}finally{setProcessing(false)}};
  if(!ready)return <main className="soft-pos-shell"><p>正在載入…</p></main>; if(!session)return <Shell><span/></Shell>; if(session.merchant?.operation_locked)return <Shell><span/></Shell>;
  const active=selected?optionsFor(selected):null;
  return <main className="soft-pos-shell soft-pos-order"><header className="soft-pos-header"><div><Link to="/merchant/pos">← 商家營運中心</Link><h1>手機快速開單</h1></div><input aria-label="桌號或取餐號" placeholder="桌號（內用選填）" value={table} onChange={e=>setTable(e.target.value)}/></header>{message&&<p className="soft-pos-message">{message}</p>}<section className="soft-pos-product-grid">{catalog?.items?.map((item:Item)=><button key={item.id} onClick={()=>optionsFor(item).groups.length?setSelected(item):add(item)}><span>{item.name}</span><strong>{ntd(item.price_minor)}</strong></button>)||<p>正在載入商品…</p>}</section><aside className="soft-pos-cart"><h2>購物車</h2>{cart.length?<>{cart.map((line,index)=><div className="soft-pos-cart-line" key={`${line.item.id}-${index}`}><span>{line.item.name} × {line.quantity}</span><button aria-label={`減少 ${line.item.name}`} onClick={()=>setCart(c=>c.flatMap((x,i)=>i!==index?[x]:x.quantity>1?[{...x,quantity:x.quantity-1}]:[]))}>−</button><button aria-label={`增加 ${line.item.name}`} onClick={()=>setCart(c=>c.map((x,i)=>i===index?{...x,quantity:x.quantity+1}:x))}>＋</button></div>)}<label>付款方式<select value={method} onChange={e=>setMethod(e.target.value)}>{["cash","counter","card","line_pay","easycard_terminal","bank_transfer","other"].map(x=><option key={x} value={x}>{x}</option>)}</select></label><button className="btn btn-primary" disabled={processing} onClick={()=>void checkout()}>{processing?"建立訂單中…":`結帳 ${ntd(total)}`}</button></>:<p>點選商品即可加入。</p>}</aside>{selected&&active&&<div className="soft-pos-modal" role="dialog" aria-modal="true"><section><h2>{selected.name}</h2>{active.groups.map((group:Group)=><fieldset key={group.id}><legend>{group.name}{group.min_select?"（必選）":""}</legend>{active.values.filter((v:Option)=>v.group_id===group.id).map((value:Option)=><label key={value.id}><input type={group.selection_type==="single"?"radio":"checkbox"} name={group.id} checked={selectedOptions.includes(value.id)} onChange={()=>setSelectedOptions(old=>group.selection_type==="single"?[...old.filter(id=>!active.values.filter((v:Option)=>v.group_id===group.id).some((v:Option)=>v.id===id)),value.id]:old.includes(value.id)?old.filter(id=>id!==value.id):[...old,value.id])}/>{value.name} +{ntd(value.price_delta_minor)}</label>)}</fieldset>)}<button className="btn btn-primary" onClick={()=>add(selected,selectedOptions)}>加入購物車</button><button className="btn btn-outline" onClick={()=>setSelected(null)}>取消</button></section></div>}</main>;
}

export function MerchantPosKitchen() {
  const {session,ready}=useMerchantSession();const [orders,setOrders]=useState<any[]>([]);const [message,setMessage]=useState(""); const refresh=()=>merchantOrderingApi<any>("/api/merchant-pos/orders").then(x=>setOrders(x.items||[])).catch(e=>setMessage(e.message)); useEffect(()=>{if(ready&&session){void refresh();const id=window.setInterval(refresh,8000);return()=>window.clearInterval(id);}},[ready,session]); const advance=async(order:any,next:string)=>{try{await merchantOrderingApi(`/api/merchant-pos/orders/${encodeURIComponent(order.order_code)}/status`,{method:"POST",headers:{"idempotency-key":crypto.randomUUID()},body:JSON.stringify({status:next})});void refresh();}catch(e){setMessage(e instanceof Error?e.message:"操作失敗");}}; if(!ready)return <main className="soft-pos-shell"><p>載入中…</p></main>;if(!session)return <Shell><span/></Shell>;if(session.merchant?.operation_locked)return <Shell><span/></Shell>;const columns=[["新單","submitted","accepted"],["製作中","preparing","ready"],["完成","ready","served"]];return <main className="soft-pos-shell"><header className="soft-pos-header"><div><Link to="/merchant/pos">← 商家營運中心</Link><h1>Web KDS</h1></div><button onClick={()=>window.print()}>列印目前清單</button></header>{message&&<p className="soft-pos-error">{message}</p>}<section className="soft-pos-kds">{columns.map(([title,status,next])=><article key={String(status)}><h2>{title}</h2>{orders.filter(o=>o.status===status).map(order=><div className="soft-pos-ticket" key={order.id}><strong>{order.order_code}</strong><span>{order.table_label||"外帶"}</span><small>{new Date(order.created_at).toLocaleTimeString("zh-TW")}</small><button className="btn btn-primary" onClick={()=>void advance(order,String(next))}>{String(next)==="accepted"?"接單":String(next)==="ready"?"完成製作":"通知出餐"}</button></div>)}</article>)}</section></main>;
}
