import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { ADVISOR_TIERS, advisorCommissionSnapshot, advisorPaymentReadiness, advisorRefundReversalSnapshot, advisorSettlementStageForDay, advisorStarLevel, moderateAdvisorContent } from "../src/advisor-core.js";
import { createAdvisorBooking, createAdvisorSettlementDraft, recordAdvisorCommission, reverseAdvisorCommission } from "../src/advisor.js";

class Statement { constructor(statement){this.statement=statement;this.values=[]} bind(...values){this.values=values;return this} async run(){const result=this.statement.run(...this.values);return{meta:{changes:Number(result.changes||0)}}} async first(){return this.statement.get(...this.values)||null} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");this.sqlite.exec("PRAGMA foreign_keys=ON");for(const file of readdirSync(new URL("../migrations",import.meta.url)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));this.sqlite.exec(readFileSync(new URL("../staging/seed-advisor-marketplace-v1.sql",import.meta.url),"utf8"))} prepare(sql){return new Statement(this.sqlite.prepare(sql))} async batch(statements){this.sqlite.exec("BEGIN IMMEDIATE");try{const out=[];for(const statement of statements)out.push(await statement.run());this.sqlite.exec("COMMIT");return out}catch(error){this.sqlite.exec("ROLLBACK");throw error}} }

test("migration creates a separate Advisor domain and ten configurable categories",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_categories").get().c,10);assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='advisors'").get());assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchants WHERE id LIKE 'advisor_%'").get().c,0)});
test("staging seed contains exactly five clearly-labelled test advisors",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisors WHERE id LIKE 'advisor_test_%'").get().c,5);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_profiles WHERE display_name NOT LIKE 'TEST ADVISOR%'").get().c,0)});
test("contract and consumer terms retain the legal review gate",()=>{const db=new D1();const contract=db.sqlite.prepare("SELECT * FROM advisor_contract_versions WHERE version='advisor_partner_v1_0'").get(),terms=db.sqlite.prepare("SELECT * FROM advisor_consumer_terms_versions WHERE version='advisor_consumer_service_terms_v1_0'").get();assert.equal(contract.version,"advisor_partner_v1_0");assert.equal(contract.legal_review_status,"pending_review");assert.equal(terms.legal_review_status,"pending_review")});
test("real payment and payout remain disabled without all readiness approvals",()=>{const gate=advisorPaymentReadiness({APP_MODE:"staging",REAL_ADVISOR_PAYMENT_ENABLED:"false",REAL_ADVISOR_PAYOUT_ENABLED:"false"});assert.equal(gate.realPaymentEnabled,false);assert.equal(gate.realPayoutEnabled,false);assert.equal(gate.paymentProvider,"TEST_PROVIDER")});
test("commercial policy V1.0 remains a three-review draft",()=>{const db=new D1(),row=db.sqlite.prepare("SELECT * FROM advisor_commercial_policies WHERE version='advisor_commercial_policy_v1_0'").get();assert.equal(row.status,"draft");assert.equal(row.legal_review_status,"pending_review");assert.equal(row.finance_review_status,"pending_review");assert.equal(row.accounting_review_status,"pending_review");assert.equal(row.tax_mode,"disabled");assert.equal(row.withholding_mode,"manual_review")});
test("V1.1 contract and consumer terms are new inactive immutable drafts",()=>{const db=new D1(),oldContract=db.sqlite.prepare("SELECT content_hash FROM advisor_contract_versions WHERE version='advisor_partner_v1_0'").get(),contract=db.sqlite.prepare("SELECT * FROM advisor_contract_versions WHERE version='advisor_partner_v1_1_draft'").get(),terms=db.sqlite.prepare("SELECT * FROM advisor_consumer_terms_versions WHERE version='advisor_consumer_service_terms_v1_1_draft'").get();assert.equal(oldContract.content_hash,"4e10d583a048c3c857aee4009dccd3362a7d221f11f823b944200486ee7b9878");assert.equal(contract.legal_review_status,"pending_review");assert.equal(contract.is_active,0);assert.equal(contract.approved_content_hash,null);assert.equal(terms.legal_review_status,"pending_review");assert.equal(terms.is_active,0);assert.throws(()=>db.sqlite.prepare("DELETE FROM advisor_contract_versions WHERE id='advisor_partner_v1_1_draft'").run(),/IMMUTABLE/)});
test("lead source is scoped to booking without duplicating canonical members",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members WHERE id='advisor_test_member_1'").get().c,1);assert.throws(()=>db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,service_price_minor,lead_source) VALUES('bad-source','BAD','advisor_test_ziwei','advisor_service_ziwei','advisor_test_member_1','2099-01-01','2099-01-01','2099-01-01','2099-01-01','online',1,'duplicate_member')").run(),/CHECK/)});

for(const [count,rate] of [[1,5000],[30,5000],[31,5200],[60,5200],[61,5300],[99,5300],[100,5500],[199,5500],[200,6000]])test(`commission tier ${count} uses ${rate} basis points`,()=>{const snapshot=advisorCommissionSnapshot({servicePriceMinor:150000,monthlyCompletedCount:count,providerFeePolicy:"platform_absorbs"});assert.equal(snapshot.advisorRateBp,rate);assert.equal(snapshot.advisorShareMinor+snapshot.platformShareMinor,150000);assert.ok(Number.isInteger(snapshot.advisorShareMinor))});
test("commission tiers are configured as progressive, non-retroactive snapshots",()=>{assert.equal(ADVISOR_TIERS.length,5);assert.equal(advisorCommissionSnapshot({servicePriceMinor:99999,monthlyCompletedCount:31,providerFeePolicy:"platform_absorbs"}).commissionApplicationMode,"progressive_nonretroactive")});
test("provider fee is deducted before split with platform remainder",()=>{const snapshot=advisorCommissionSnapshot({servicePriceMinor:150000,providerFeeMinor:4500,providerFeeEstimatedMinor:4500,providerFeeSource:"test_estimate",monthlyCompletedCount:1});assert.equal(snapshot.commissionBaseMinor,145500);assert.equal(snapshot.advisorShareMinor,72750);assert.equal(snapshot.platformShareMinor,72750);assert.equal(snapshot.roundingPolicy,"platform_remainder");const odd=advisorCommissionSnapshot({servicePriceMinor:101,providerFeeMinor:0,monthlyCompletedCount:1});assert.equal(odd.advisorShareMinor,50);assert.equal(odd.platformShareMinor,51)});
test("full and partial refund snapshots use immutable original rates",()=>{const original={grossAmountMinor:150000,commissionBaseMinor:145500,advisorRateBp:5000,roundingPolicy:"platform_remainder",refundPolicyVersion:"advisor_cancellation_policy_v1_0"};const full=advisorRefundReversalSnapshot(original,150000),partial=advisorRefundReversalSnapshot(original,75000);assert.equal(full.advisorReversalMinor,72750);assert.equal(full.platformReversalMinor,72750);assert.equal(partial.reversalBaseMinor,72750);assert.equal(partial.advisorReversalMinor,36375)});
for(const [day,stage] of [[1,"draft_created"],[5,"reconciliation_buffer"],[10,"lock_target"],[15,"payout_target"]])test(`settlement day ${day} maps to ${stage}`,()=>assert.equal(advisorSettlementStageForDay(day),stage));
for(const [count,level] of [[199,"standard"],[200,"gold"],[499,"gold"],[500,"platinum"],[999,"platinum"],[1000,"principal"]])test(`platform service level at ${count}`,()=>assert.equal(advisorStarLevel(count)?.level||null,level));

for(const copy of ["保證治癒癌症","不用吃藥就會好","100% 投資獲利","用死亡災禍逼你加購"])test(`unsafe copy is blocked: ${copy}`,()=>assert.equal(moderateAdvisorContent(copy).status,"blocked"));
test("guaranteed relationship outcome requires review",()=>assert.equal(moderateAdvisorContent("保證復合").status,"review_required"));
test("ordinary cultural exploration copy enters review flow",()=>assert.equal(moderateAdvisorContent("紫微斗數年度人生方向探索").status,"pending_review"));

test("database guard permits one concurrent booking and rejects the second",()=>{const db=new D1(),advisor="advisor_test_ziwei",service="advisor_service_ziwei",member="advisor_test_member_1",start="2099-01-10T02:00:00.000Z",end="2099-01-10T03:00:00.000Z";const insert=(id)=>db.sqlite.prepare(`INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) SELECT ?,?,?,?,?,?,?,?,?,?,'CONFIRMED',150000,'PAID','TEST_PROVIDER',1,'advisor_consumer_service_terms_v1_0','hash' WHERE (SELECT COUNT(*) FROM advisor_bookings WHERE advisor_id=? AND status IN('SLOT_HELD','PAYMENT_PENDING','CONFIRMED','IN_SERVICE') AND blocked_start_at<? AND blocked_end_at>?)<1`).run(id,id,advisor,service,member,start,end,start,end,"online",advisor,end,start);assert.equal(insert("slot-a").changes,1);assert.equal(insert("slot-b").changes,0);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_bookings WHERE id LIKE 'slot-%'").get().c,1)});
test("checkout stores lead source and accepted cancellation policy before Test Provider payment",async()=>{const db=new D1(),date="2099-01-05",request=new Request("https://staging.test/api/advisor/bookings",{method:"POST",headers:{"user-agent":"test","cf-connecting-ip":"127.0.0.1"}}),member={id:"advisor_test_member_1",session_id:"member-session"};const result=await createAdvisorBooking(db,request,{advisor_id:"advisor_test_ziwei",service_id:"advisor_service_ziwei",date,time:"09:00",lead_source:"platform_referred",accept_terms:true,accept_service:true,accept_price:true,accept_cancellation:true,accept_disclaimer:true},member,{APP_MODE:"staging",REAL_ADVISOR_PAYMENT_ENABLED:"false",REAL_ADVISOR_PAYOUT_ENABLED:"false"});assert.equal(result.status,201);const booking=db.sqlite.prepare("SELECT * FROM advisor_bookings WHERE id=?").get(result.booking.id),acceptance=db.sqlite.prepare("SELECT * FROM advisor_consumer_terms_acceptances WHERE booking_id=?").get(result.booking.id);assert.equal(booking.lead_source,"platform_referred");assert.equal(booking.terms_version,"advisor_consumer_service_terms_v1_1_draft");assert.equal(booking.cancellation_policy_version,"advisor_cancellation_policy_v1_0");assert.match(acceptance.consent_json,/cancellation_policy_hash/)});
test("completed paid non-test service creates immutable commission and one reversal",async()=>{const db=new D1(),member="advisor_test_member_1";db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,completed_at,terms_version,terms_hash) VALUES('finance-booking','FIN','advisor_test_ziwei','advisor_service_ziwei',?,'2026-09-01','2026-09-01','2026-09-01','2026-09-01','online','COMPLETED',150000,'PAID','TEST_PROVIDER',0,'2026-09-01','terms','hash')").run(member);const commission=await recordAdvisorCommission(db,"finance-booking");assert.equal(commission.created,true);await reverseAdvisorCommission(db,"finance-booking","refund-once");await reverseAdvisorCommission(db,"finance-booking","refund-once");assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_commission_ledger WHERE booking_id='finance-booking'").get().c,2);assert.throws(()=>db.sqlite.prepare("DELETE FROM advisor_commission_ledger").run(),/IMMUTABLE/)});
test("partial refund reversal is proportional and duplicate-safe",async()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,completed_at,terms_version,terms_hash) VALUES('partial-booking','PART','advisor_test_ziwei','advisor_service_ziwei','advisor_test_member_1','2026-09-01','2026-09-01','2026-09-01','2026-09-01','online','COMPLETED',150000,'PAID','TEST_PROVIDER',0,'2026-09-01','terms','hash')").run();await recordAdvisorCommission(db,"partial-booking",{providerFeeMinor:4500,providerFeeEstimatedMinor:4500,providerFeeSource:"test_estimate"});const first=await reverseAdvisorCommission(db,"partial-booking","partial-refund",75000),replay=await reverseAdvisorCommission(db,"partial-booking","partial-refund",75000),row=db.sqlite.prepare("SELECT * FROM advisor_commission_ledger WHERE booking_id='partial-booking' AND entry_type='REFUND_REVERSAL'").get();assert.equal(first.created,true);assert.equal(replay.created,false);assert.equal(row.reversal_amount_minor,75000);assert.equal(row.advisor_share_minor,-36375)});
test("settlement stays draft and payout-blocked",async()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,completed_at,terms_version,terms_hash) VALUES('settle-booking','SET','advisor_test_ziwei','advisor_service_ziwei','advisor_test_member_1','2026-09-01','2026-09-01','2026-09-01','2026-09-01','online','COMPLETED',100000,'PAID','TEST_PROVIDER',0,'2026-09-01','terms','hash')").run();await recordAdvisorCommission(db,"settle-booking");const row=await createAdvisorSettlementDraft(db,"advisor_test_ziwei","2026-01-01","2027-01-01");assert.equal(row.status,"draft");assert.equal(row.payout_block_reason,"PAYOUT_BLOCKED_POLICY_REQUIRED")});
test("reviews are limited to one per completed paid booking",()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) VALUES('review-booking','REV','advisor_test_tarot','advisor_service_tarot','advisor_test_member_2','2099-01-01','2099-01-01','2099-01-01','2099-01-01','online','COMPLETED',80000,'PAID','TEST_PROVIDER',1,'terms','hash')").run();db.sqlite.prepare("INSERT INTO advisor_reviews(id,booking_id,advisor_id,platform_member_id,rating,moderation_status) VALUES('r1','review-booking','advisor_test_tarot','advisor_test_member_2',5,'pending_review')").run();assert.throws(()=>db.sqlite.prepare("INSERT INTO advisor_reviews(id,booking_id,advisor_id,platform_member_id,rating,moderation_status) VALUES('r2','review-booking','advisor_test_tarot','advisor_test_member_2',5,'pending_review')").run(),/UNIQUE/)});
test("cross-advisor scoped query cannot read another advisor booking",()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) VALUES('private-booking','PRI','advisor_test_tarot','advisor_service_tarot','advisor_test_member_2','2099-01-01','2099-01-01','2099-01-01','2099-01-01','online','CONFIRMED',80000,'PAID','TEST_PROVIDER',1,'terms','hash')").run();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_bookings WHERE id='private-booking' AND advisor_id='advisor_test_ziwei'").get().c,0)});
test("advisor identities reuse canonical platform members and do not grant merchant/admin roles",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members WHERE id='advisor_test_member_1'").get().c,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisors WHERE platform_member_id='advisor_test_member_1'").get().c,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_owner_links WHERE platform_member_id='advisor_test_member_1'").get().c,0);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM admin_users WHERE email LIKE '%advisor%'").get().c,0)});

