import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { ADVISOR_TIERS, advisorCommissionSnapshot, advisorPaymentReadiness, advisorStarLevel, moderateAdvisorContent } from "../src/advisor-core.js";
import { createAdvisorSettlementDraft, recordAdvisorCommission, reverseAdvisorCommission } from "../src/advisor.js";

class Statement { constructor(statement){this.statement=statement;this.values=[]} bind(...values){this.values=values;return this} async run(){const result=this.statement.run(...this.values);return{meta:{changes:Number(result.changes||0)}}} async first(){return this.statement.get(...this.values)||null} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");this.sqlite.exec("PRAGMA foreign_keys=ON");for(const file of readdirSync(new URL("../migrations",import.meta.url)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));this.sqlite.exec(readFileSync(new URL("../staging/seed-advisor-marketplace-v1.sql",import.meta.url),"utf8"))} prepare(sql){return new Statement(this.sqlite.prepare(sql))} async batch(statements){this.sqlite.exec("BEGIN IMMEDIATE");try{const out=[];for(const statement of statements)out.push(await statement.run());this.sqlite.exec("COMMIT");return out}catch(error){this.sqlite.exec("ROLLBACK");throw error}} }

test("migration creates a separate Advisor domain and ten configurable categories",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_categories").get().c,10);assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='advisors'").get());assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchants WHERE id LIKE 'advisor_%'").get().c,0)});
test("staging seed contains exactly five clearly-labelled test advisors",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisors WHERE id LIKE 'advisor_test_%'").get().c,5);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_profiles WHERE display_name NOT LIKE 'TEST ADVISOR%'").get().c,0)});
test("contract and consumer terms retain the legal review gate",()=>{const db=new D1();const contract=db.sqlite.prepare("SELECT * FROM advisor_contract_versions WHERE version='advisor_partner_v1_0'").get(),terms=db.sqlite.prepare("SELECT * FROM advisor_consumer_terms_versions WHERE version='advisor_consumer_service_terms_v1_0'").get();assert.equal(contract.version,"advisor_partner_v1_0");assert.equal(contract.legal_review_status,"pending_review");assert.equal(terms.legal_review_status,"pending_review")});
test("real payment and payout remain disabled without all readiness approvals",()=>{const gate=advisorPaymentReadiness({APP_MODE:"staging",REAL_ADVISOR_PAYMENT_ENABLED:"false",REAL_ADVISOR_PAYOUT_ENABLED:"false"});assert.equal(gate.realPaymentEnabled,false);assert.equal(gate.realPayoutEnabled,false);assert.equal(gate.paymentProvider,"TEST_PROVIDER")});

for(const [count,rate] of [[1,5000],[30,5000],[31,5200],[60,5200],[61,5300],[99,5300],[100,5500],[199,5500],[200,6000]])test(`commission tier ${count} uses ${rate} basis points`,()=>{const snapshot=advisorCommissionSnapshot({servicePriceMinor:150000,monthlyCompletedCount:count,providerFeePolicy:"platform_absorbs"});assert.equal(snapshot.advisorRateBp,rate);assert.equal(snapshot.advisorShareMinor+snapshot.platformShareMinor,150000);assert.ok(Number.isInteger(snapshot.advisorShareMinor))});
test("commission tiers are configured as progressive, non-retroactive snapshots",()=>{assert.equal(ADVISOR_TIERS.length,5);assert.equal(advisorCommissionSnapshot({servicePriceMinor:99999,monthlyCompletedCount:31,providerFeePolicy:"platform_absorbs"}).commissionApplicationMode,"progressive_nonretroactive")});
for(const [count,level] of [[199,"standard"],[200,"gold"],[499,"gold"],[500,"platinum"],[999,"platinum"],[1000,"principal"]])test(`platform service level at ${count}`,()=>assert.equal(advisorStarLevel(count)?.level||null,level));

for(const copy of ["保證治癒癌症","不用吃藥就會好","100% 投資獲利","用死亡災禍逼你加購"])test(`unsafe copy is blocked: ${copy}`,()=>assert.equal(moderateAdvisorContent(copy).status,"blocked"));
test("guaranteed relationship outcome requires review",()=>assert.equal(moderateAdvisorContent("保證復合").status,"review_required"));
test("ordinary cultural exploration copy enters review flow",()=>assert.equal(moderateAdvisorContent("紫微斗數年度人生方向探索").status,"pending_review"));

test("database guard permits one concurrent booking and rejects the second",()=>{const db=new D1(),advisor="advisor_test_ziwei",service="advisor_service_ziwei",member="advisor_test_member_1",start="2099-01-10T02:00:00.000Z",end="2099-01-10T03:00:00.000Z";const insert=(id)=>db.sqlite.prepare(`INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) SELECT ?,?,?,?,?,?,?,?,?,?,'CONFIRMED',150000,'PAID','TEST_PROVIDER',1,'advisor_consumer_service_terms_v1_0','hash' WHERE (SELECT COUNT(*) FROM advisor_bookings WHERE advisor_id=? AND status IN('SLOT_HELD','PAYMENT_PENDING','CONFIRMED','IN_SERVICE') AND blocked_start_at<? AND blocked_end_at>?)<1`).run(id,id,advisor,service,member,start,end,start,end,"online",advisor,end,start);assert.equal(insert("slot-a").changes,1);assert.equal(insert("slot-b").changes,0);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_bookings WHERE id LIKE 'slot-%'").get().c,1)});
test("completed paid non-test service creates immutable commission and one reversal",async()=>{const db=new D1(),member="advisor_test_member_1";db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,completed_at,terms_version,terms_hash) VALUES('finance-booking','FIN','advisor_test_ziwei','advisor_service_ziwei',?,'2026-09-01','2026-09-01','2026-09-01','2026-09-01','online','COMPLETED',150000,'PAID','TEST_PROVIDER',0,'2026-09-01','terms','hash')").run(member);const commission=await recordAdvisorCommission(db,"finance-booking");assert.equal(commission.created,true);await reverseAdvisorCommission(db,"finance-booking","refund-once");await reverseAdvisorCommission(db,"finance-booking","refund-once");assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_commission_ledger WHERE booking_id='finance-booking'").get().c,2);assert.throws(()=>db.sqlite.prepare("DELETE FROM advisor_commission_ledger").run(),/IMMUTABLE/)});
test("settlement stays draft and payout-blocked",async()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,completed_at,terms_version,terms_hash) VALUES('settle-booking','SET','advisor_test_ziwei','advisor_service_ziwei','advisor_test_member_1','2026-09-01','2026-09-01','2026-09-01','2026-09-01','online','COMPLETED',100000,'PAID','TEST_PROVIDER',0,'2026-09-01','terms','hash')").run();await recordAdvisorCommission(db,"settle-booking");const row=await createAdvisorSettlementDraft(db,"advisor_test_ziwei","2026-01-01","2027-01-01");assert.equal(row.status,"draft");assert.equal(row.payout_block_reason,"PAYOUT_BLOCKED_POLICY_REQUIRED")});
test("reviews are limited to one per completed paid booking",()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) VALUES('review-booking','REV','advisor_test_tarot','advisor_service_tarot','advisor_test_member_2','2099-01-01','2099-01-01','2099-01-01','2099-01-01','online','COMPLETED',80000,'PAID','TEST_PROVIDER',1,'terms','hash')").run();db.sqlite.prepare("INSERT INTO advisor_reviews(id,booking_id,advisor_id,platform_member_id,rating,moderation_status) VALUES('r1','review-booking','advisor_test_tarot','advisor_test_member_2',5,'pending_review')").run();assert.throws(()=>db.sqlite.prepare("INSERT INTO advisor_reviews(id,booking_id,advisor_id,platform_member_id,rating,moderation_status) VALUES('r2','review-booking','advisor_test_tarot','advisor_test_member_2',5,'pending_review')").run(),/UNIQUE/)});
test("cross-advisor scoped query cannot read another advisor booking",()=>{const db=new D1();db.sqlite.prepare("INSERT INTO advisor_bookings(id,booking_code,advisor_id,service_id,platform_member_id,start_at,end_at,blocked_start_at,blocked_end_at,service_mode,status,service_price_minor,payment_status,payment_provider,test_data,terms_version,terms_hash) VALUES('private-booking','PRI','advisor_test_tarot','advisor_service_tarot','advisor_test_member_2','2099-01-01','2099-01-01','2099-01-01','2099-01-01','online','CONFIRMED',80000,'PAID','TEST_PROVIDER',1,'terms','hash')").run();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisor_bookings WHERE id='private-booking' AND advisor_id='advisor_test_ziwei'").get().c,0)});
test("advisor identities reuse canonical platform members and do not grant merchant/admin roles",()=>{const db=new D1();assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members WHERE id='advisor_test_member_1'").get().c,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM advisors WHERE platform_member_id='advisor_test_member_1'").get().c,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_owner_links WHERE platform_member_id='advisor_test_member_1'").get().c,0);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM admin_users WHERE email LIKE '%advisor%'").get().c,0)});

