import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import {
  ContractError,
  STANDARD_ASSURANCE,
  assertContractSignable,
  beginContractOperation,
  buildSignedAgreement,
  completeContractOperation,
  hashCanonical,
  parseAndValidateSignature,
  publicVerificationRecord,
  stableStringify,
  storePrivateAgreementArtifacts,
} from "../src/contract-engine.js";
import { createSignedAgreementPdf, createSignedContractPdf, sha256 } from "../src/contract-pdf.js";
import { handleMerchantContractAdmin, handleMerchantContractPublic, handleMerchantContractRequest, handlePublicContractVerification } from "../src/merchant-contracts.js";
import { handlePartnerRequest } from "../src/partner.js";
import { encryptPartnerIdNumber, hashPartnerIdNumber } from "../src/partner-identity.js";

class Statement {
  constructor(statement) { this.statement = statement; this.values = []; }
  bind(...values) { this.values = values; return this; }
  async run() { const result = this.statement.run(...this.values); return { meta: { changes: Number(result.changes || 0), last_row_id: result.lastInsertRowid } }; }
  async first() { return this.statement.get(...this.values) || null; }
  async all() { return { results: this.statement.all(...this.values) }; }
}
class D1 {
  constructor() {
    this.sqlite = new DatabaseSync(":memory:");
    const files = readdirSync(new URL("../migrations", import.meta.url)).filter((name) => /^\d+.*\.sql$/.test(name)).sort();
    for (const file of files) this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`, import.meta.url), "utf8"));
  }
  prepare(sql) { return new Statement(this.sqlite.prepare(sql)); }
  async batch(statements) { return Promise.all(statements.map((statement) => statement.run())); }
}
class R2 {
  objects = new Map();
  async put(key, value, options = {}) { this.objects.set(key, { bytes: value instanceof Uint8Array ? value : new Uint8Array(value), options }); }
  async get(key) { const item = this.objects.get(key); return item ? { body: item.bytes } : null; }
  async delete(key) { this.objects.delete(key); }
}

const signature = { strokes: [[[12, 20], [25, 26], [35, 30], [58, 27], [80, 22], [110, 48]], [[20, 60], [38, 65], [55, 70], [82, 68], [105, 64], [120, 62]]] };
const contract = { id: "v", version: "v1", content_html: "<h1>契約</h1><p>本文</p>", content_hash: "hash", is_active: 1, legal_review_status: "approved", approved_content_hash: "hash" };
const cors = { "access-control-allow-origin": "https://staging.example" };
const request = (path, method = "GET", data = undefined, headers = {}) => new Request(`https://worker.test${path}`, { method, headers: { ...(data ? { "content-type": "application/json" } : {}), ...headers }, ...(data ? { body: JSON.stringify(data) } : {}) });

function expectContractError(fn, code) {
  assert.throws(fn, (error) => error instanceof ContractError && error.code === code);
}

test("C01 signature rejects invalid JSON", () => expectContractError(() => parseAndValidateSignature("{"), "SIGNATURE_INVALID"));
test("C02 signature rejects missing strokes", () => expectContractError(() => parseAndValidateSignature({}), "SIGNATURE_REQUIRED"));
test("C03 signature rejects blank strokes", () => expectContractError(() => parseAndValidateSignature({ strokes: [] }), "SIGNATURE_TOO_SHORT"));
test("C04 signature rejects a single point", () => expectContractError(() => parseAndValidateSignature({ strokes: [[[1, 1]]] }), "SIGNATURE_TOO_SHORT"));
test("C05 signature rejects too few total points", () => expectContractError(() => parseAndValidateSignature({ strokes: [[[1, 1], [2, 2]]] }), "SIGNATURE_TOO_SHORT"));
test("C06 signature accepts touch/pointer strokes", () => assert.equal(parseAndValidateSignature(signature).pointCount, 12));
test("C07 signature normalization is deterministic", () => assert.equal(parseAndValidateSignature(signature).serialized, parseAndValidateSignature(signature).serialized));
test("C08 signature hash changes with strokes", async () => assert.notEqual(await sha256(parseAndValidateSignature(signature).serialized), await sha256(parseAndValidateSignature({ strokes: [[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]]] }).serialized)));
test("C09 standard assurance is the only V1 assurance", () => assert.equal(STANDARD_ASSURANCE, "standard_electronic_agreement_evidence"));
test("C10 stable JSON ignores object key order", () => assert.equal(stableStringify({ b: 2, a: 1 }), stableStringify({ a: 1, b: 2 })));
test("C11 canonical commercial terms hash is deterministic", async () => assert.equal(await hashCanonical({ plan: "x", amount: 1800000 }), await hashCanonical({ amount: 1800000, plan: "x" })));
test("C12 inactive contract cannot sign", () => expectContractError(() => assertContractSignable({ ...contract, is_active: 0 }), "CONTRACT_NOT_ACTIVE"));
test("C13 revoked contract cannot sign", () => expectContractError(() => assertContractSignable({ ...contract, legal_review_status: "revoked" }), "CONTRACT_REVOKED"));
test("C14 pending legal review cannot Production sign", () => expectContractError(() => assertContractSignable({ ...contract, legal_review_status: "pending_review", approved_content_hash: null }), "LEGAL_REVIEW_REQUIRED"));
test("C15 pending legal review can isolated Staging sign", () => assert.equal(assertContractSignable({ ...contract, legal_review_status: "pending_review" }, { CONTRACT_SIGNING_MODE: "staging" }).staging, true));
test("C16 approved hash mismatch blocks signing", () => expectContractError(() => assertContractSignable({ ...contract, approved_content_hash: "other" }), "APPROVED_HASH_MISMATCH"));
test("C17 approved matching hash signs", () => assert.equal(assertContractSignable(contract).staging, false));
test("C18 partner missing read consent is rejected", async () => assert.rejects(() => buildSignedAgreement({ title: "x", documentId: "x", contract, partyType: "partner", partyId: "p", partyLabel: "p", signatory: "王小明", signatoryRole: "承攬夥伴", signature, consents: { electronic: true, independent: true }, consentVersion: "v" }), (error) => error.code === "CONSENT_REQUIRED"));
test("C19 merchant missing authority consent is rejected", async () => assert.rejects(() => buildSignedAgreement({ title: "x", documentId: "x", contract, partyType: "merchant", partyId: "m", partyLabel: "m", signatory: "王小明", signatoryRole: "legal_representative", signature, consents: { read: true, electronic: true, commercial_terms: true, signature_evidence: true }, consentVersion: "v" }), (error) => error.code === "CONSENT_REQUIRED"));
test("C20 agreement hash chain includes signature and content", async () => { const result = await buildSignedAgreement({ title: "契約", documentId: "x", publicId: "PUB", contract, partyType: "partner", partyId: "p", partyLabel: "甲乙", signatory: "王小明", signatoryRole: "承攬夥伴", signature, consents: { read: true, electronic: true, independent: true }, consentVersion: "v" }); assert.ok(result.signatureHash); assert.ok(result.documentHash); assert.ok(result.pdfHash); assert.notEqual(result.signatureHash, result.documentHash); });

test("C21 migration creates five required merchant contract tables", () => { const db = new D1(); for (const name of ["merchant_contract_versions","merchant_contract_signatures","merchant_contract_artifacts","merchant_contract_invites","merchant_contract_events"]) assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name)); });
test("C22 migration creates immutable commercial terms", () => { const db = new D1(); assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_contract_commercial_terms'").get()); });
test("C23 contractor v1.4 stays pending review and inactive", () => { const db = new D1(); const row=db.sqlite.prepare("SELECT * FROM contract_versions WHERE id='contractor_partner_v1_4'").get(); assert.equal(row.legal_review_status,"pending_review"); assert.equal(row.is_active,0); });
test("C24 merchant v1.0 stays pending review and inactive", () => { const db = new D1(); const row=db.sqlite.prepare("SELECT * FROM merchant_contract_versions WHERE id='merchant_service_v1_0'").get(); assert.equal(row.legal_review_status,"pending_review"); assert.equal(row.is_active,0); });
test("C25 existing partner v1.3 is not falsely approved", () => { const db=new D1(); assert.equal(db.sqlite.prepare("SELECT legal_review_status FROM contract_versions WHERE id='contract_v1_3'").get().legal_review_status,"pending_review"); });
test("C26 signed partner row is immutable", () => { const db=new D1(); db.sqlite.prepare("INSERT INTO partners(id,partner_code,legal_name,display_name,email,phone,status,referral_code) VALUES('p','P','王','王','p@x.test','0900','active','R')").run(); db.sqlite.prepare("INSERT INTO contract_signatures(id,partner_id,contract_version_id,legal_name,signed_at,contract_content_hash,signature_hash,consent_version) VALUES('s','p','contract_v1_3','王',CURRENT_TIMESTAMP,'h','h','v')").run(); assert.throws(()=>db.sqlite.prepare("UPDATE contract_signatures SET legal_name='改' WHERE id='s'").run(),/IMMUTABLE/); });
test("C27 signed partner row cannot be deleted", () => { const db=new D1(); db.sqlite.prepare("INSERT INTO partners(id,partner_code,legal_name,display_name,email,phone,status,referral_code) VALUES('p','P','王','王','p@x.test','0900','active','R')").run(); db.sqlite.prepare("INSERT INTO contract_signatures(id,partner_id,contract_version_id,legal_name,signed_at,contract_content_hash,signature_hash,consent_version) VALUES('s','p','contract_v1_3','王',CURRENT_TIMESTAMP,'h','h','v')").run(); assert.throws(()=>db.sqlite.prepare("DELETE FROM contract_signatures WHERE id='s'").run(),/IMMUTABLE/); });
test("C28 signed merchant row is immutable", () => { const fixture=seedSignedMerchant(); assert.throws(()=>fixture.db.sqlite.prepare("UPDATE merchant_contract_signatures SET company_name='改' WHERE id='sig'").run(),/IMMUTABLE/); });
test("C29 signed merchant row cannot be deleted", () => { const fixture=seedSignedMerchant(); assert.throws(()=>fixture.db.sqlite.prepare("DELETE FROM merchant_contract_signatures WHERE id='sig'").run(),/IMMUTABLE/); });
test("C30 merchant artifact cannot be updated", () => { const fixture=seedSignedMerchant(); assert.throws(()=>fixture.db.sqlite.prepare("UPDATE merchant_contract_artifacts SET sha256='x' WHERE id='art'").run(),/IMMUTABLE/); });
test("C31 merchant artifact cannot be deleted", () => { const fixture=seedSignedMerchant(); assert.throws(()=>fixture.db.sqlite.prepare("DELETE FROM merchant_contract_artifacts WHERE id='art'").run(),/IMMUTABLE/); });
test("C32 approved commercial terms cannot be edited", async () => { const {db}=await seedMerchant(); assert.throws(()=>db.sqlite.prepare("UPDATE merchant_contract_commercial_terms SET discount_price_minor=1 WHERE id='terms'").run(),/IMMUTABLE/); });
test("C33 approved contract content cannot be overwritten", () => { const db=new D1(); db.sqlite.prepare("UPDATE merchant_contract_versions SET legal_review_status='approved',approved_content_hash=content_hash WHERE id='merchant_service_v1_0'").run(); assert.throws(()=>db.sqlite.prepare("UPDATE merchant_contract_versions SET content_html='changed' WHERE id='merchant_service_v1_0'").run(),/IMMUTABLE/); });
test("C34 partner public verification never returns PII", () => { const row={public_id:"PUB",signed_at:"2026",status:"VALID",document_hash:"HASH",legal_name:"秘密",ip_address:"1.2.3.4"}; const result=publicVerificationRecord(row,"CONTRACTOR_PARTNER","v1.4"); assert.equal(result.document_id,"PUB"); assert.equal("legal_name" in result,false); assert.equal("ip_address" in result,false); });
test("C35 certificate digital signature is not claimed in evidence", async () => { const agreement=await sampleAgreement(); assert.equal(agreement.evidence.signature_assurance_level,STANDARD_ASSURANCE); assert.doesNotMatch(new TextDecoder().decode(agreement.bytes),/政府認證電子簽章/); });

function termsSnapshot() { return { plan_code:"AI_DIGITAL_PROMOTION_2026",plan_name:"創百業智慧鏈｜AI 行銷推廣及數位服務方案",list_price_minor:3000000,discount_price_minor:1800000,currency:"TWD",contract_term_months:24,payment_plan:"upfront_18000",upfront_amount_minor:1800000,offset_target_amount_minor:0,tax_reserve_enabled:0,withholding_enabled:0,included_services:["網站","AI"],excluded_services:["客製另報價"],attachments:{acceptance:"逐項驗收",third_party:"第三方為準"},start_date:"2026-09-01",service_period_end:"2028-08-31",renewal_terms:"續約另議",custom_quote_reference:null}; }
function seedMerchant() {
  const db=new D1();
  db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,contact_name,phone,email,status) VALUES('merchant-a','MA','商家甲','王小明','0911222333','owner@merchant.test','pending_contract')").run();
  const snapshot=termsSnapshot();
  return hashCanonical(snapshot).then((hash)=>{ db.sqlite.prepare("INSERT INTO merchant_contract_commercial_terms(id,merchant_id,plan_code,plan_name,list_price_minor,discount_price_minor,currency,contract_term_months,payment_plan,upfront_amount_minor,offset_target_amount_minor,tax_reserve_enabled,withholding_enabled,included_services_json,excluded_services_json,attachments_json,start_date,service_period_end,renewal_terms,status,created_by,approved_by,approved_at,terms_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("terms","merchant-a",snapshot.plan_code,snapshot.plan_name,snapshot.list_price_minor,snapshot.discount_price_minor,snapshot.currency,snapshot.contract_term_months,snapshot.payment_plan,snapshot.upfront_amount_minor,snapshot.offset_target_amount_minor,snapshot.tax_reserve_enabled,snapshot.withholding_enabled,JSON.stringify(snapshot.included_services),JSON.stringify(snapshot.excluded_services),JSON.stringify(snapshot.attachments),snapshot.start_date,snapshot.service_period_end,snapshot.renewal_terms,"approved","admin","admin",new Date().toISOString(),hash); return {db,hash,snapshot}; });
}
function seedSignedMerchant() {
  const db=new D1(); db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('m','M','商家','active')").run();
  db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,display_name) VALUES('u','m','u@x','h','s','王')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_commercial_terms(id,merchant_id,plan_code,plan_name,list_price_minor,discount_price_minor,contract_term_months,payment_plan,included_services_json,excluded_services_json,attachments_json,start_date,service_period_end,renewal_terms,status,created_by,approved_by,approved_at,terms_hash) VALUES('t','m','p','方案',1,1,1,'upfront_18000','[]','[]','{}','2026-01-01','2026-01-31','x','approved','a','a',CURRENT_TIMESTAMP,'h')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES('i','m','t','u@x','th','2099-01-01',CURRENT_TIMESTAMP,'a')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_signatures(id,public_id,merchant_id,merchant_user_id,contract_version_id,commercial_terms_id,signatory_legal_name,signatory_role,legal_representative_name,company_name,signed_at,contract_content_hash,commercial_terms_hash,signature_hash,signature_data,document_hash,pdf_hash,consent_version,invite_id,session_id_hash,r2_key,evidence_object_key) VALUES('sig','PUB','m','u','merchant_service_v1_0','t','王','legal_representative','王','商家',CURRENT_TIMESTAMP,'h','h','h','{}','h','h','v','i','h','k','e')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_artifacts(id,merchant_id,signature_id,artifact_type,object_key,sha256,content_type) VALUES('art','m','sig','signed_pdf','k','h','application/pdf')").run(); return {db};
}
async function sampleAgreement(staging=false) { return buildSignedAgreement({ title:"創百業智慧鏈｜承攬夥伴合作契約",documentId:"doc",publicId:"PUB",verificationUrl:"https://x/#/verify/PUB",contract,partyType:"partner",partyId:"p",partyLabel:"甲乙",signatory:"王小明",signatoryRole:"承攬夥伴",signature,consents:{read:true,electronic:true,independent:true},consentVersion:"v",staging }); }

test("C36 Partner generic PDF wrapper remains compatible", async () => { const pdf=await createSignedContractPdf({contractId:"old",version:"v1.3",contentHtml:"<p>舊契約</p>",contractHash:"h",signatureHash:"s",legalName:"王",signedAt:"2026",consentVersion:"v",signature:JSON.stringify(signature)}); assert.equal(new TextDecoder().decode(pdf.bytes).startsWith("%PDF-1.7"),true); });
test("C37 generic Merchant PDF includes commercial terms hash metadata", async () => { const pdf=await createSignedAgreementPdf({title:"商家平台服務契約",documentId:"d",publicId:"p",version:"v1",partyLabel:"商家",signatory:"王",signatoryRole:"legal_representative",signedAt:"2026",contentHtml:"<p>文</p>",contractHash:"c",commercialTermsHash:"terms",signatureHash:"s",documentHash:"d",consentVersion:"v",signature:JSON.stringify(signature)}); assert.ok(pdf.pdfHash); assert.ok(pdf.bytes.length>500); });
test("C38 private R2 stores PDF and evidence separately", async () => { const r2=new R2(),a=await sampleAgreement(); const stored=await storePrivateAgreementArtifacts(r2,"contracts/test",a); assert.ok(r2.objects.has(stored.pdfKey)); assert.ok(r2.objects.has(stored.evidenceKey)); });
test("C39 artifact cleanup removes uncommitted objects", async () => { const r2=new R2(),a=await sampleAgreement(); const stored=await storePrivateAgreementArtifacts(r2,"contracts/test",a); await stored.cleanup(); assert.equal(r2.objects.size,0); });
test("C40 Evidence JSON is private and contains session/invite hashes only", async () => { const a=await buildSignedAgreement({title:"x",documentId:"d",publicId:"p",contract,partyType:"partner",partyId:"p",partyLabel:"x",signatory:"王",signatoryRole:"承攬夥伴",signature,consents:{read:true,electronic:true,independent:true},consentVersion:"v",sessionEvidence:"session-hash",inviteEvidence:"invite-hash"}); assert.equal(a.evidence.session_evidence,"session-hash"); assert.equal(a.evidence.invite_evidence,"invite-hash"); });
test("C41 Staging PDF is visibly marked not real", async () => { const a=await sampleAgreement(true); assert.match(new TextDecoder().decode(a.bytes),/%PDF/); assert.equal(a.evidence.environment,"STAGING_NOT_A_REAL_CONTRACT"); });
test("C42 sign operation requires idempotency key", async () => { const db=new D1(); await assert.rejects(()=>beginContractOperation(db,{partyType:"partner",partyId:"p",operationType:"sign",idempotencyKey:""}),(error)=>error.code==="IDEMPOTENCY_KEY_REQUIRED"); });
test("C43 completed sign operation replays first result", async () => { const db=new D1(),input={partyType:"partner",partyId:"p",operationType:"sign",idempotencyKey:"123456789012"}; const first=await beginContractOperation(db,input); await completeContractOperation(db,first.operation.id,{signature_id:"s"}); const replay=await beginContractOperation(db,input); assert.equal(replay.replay,true); assert.equal(replay.result.signature_id,"s"); });
test("C44 in-progress duplicate sign is rejected", async () => { const db=new D1(),input={partyType:"partner",partyId:"p",operationType:"sign",idempotencyKey:"123456789012"}; await beginContractOperation(db,input); await assert.rejects(()=>beginContractOperation(db,input),(error)=>error.code==="OPERATION_IN_PROGRESS"); });
test("C45 same key for different parties is isolated", async () => { const db=new D1(),key="123456789012"; const a=await beginContractOperation(db,{partyType:"partner",partyId:"a",operationType:"sign",idempotencyKey:key}); const b=await beginContractOperation(db,{partyType:"partner",partyId:"b",operationType:"sign",idempotencyKey:key}); assert.notEqual(a.operation.id,b.operation.id); });

test("C46 Merchant invite invalid token is rejected", async () => { const env={FINANCE_DB:new D1()}; const response=await handleMerchantContractPublic(request("/api/merchant/contracts/invite/validate","POST",{token:"bad"}),env,new URL("https://x/api/merchant/contracts/invite/validate"),cors); assert.equal(response.status,401); });
test("C47 Merchant contract endpoint rejects unauthenticated", async () => { const response=await handleMerchantContractRequest(request("/api/merchant/contracts/current"),{FINANCE_DB:new D1()},new URL("https://x/api/merchant/contracts/current"),cors,{ok:false,status:401,error:"UNAUTHENTICATED"}); assert.equal(response.status,401); });
test("C48 non-owner Merchant cannot sign", async () => { const {db}=await seedMerchant(); db.sqlite.prepare("UPDATE merchant_contract_versions SET is_active=1 WHERE id='merchant_service_v1_0'").run(); const response=await handleMerchantContractRequest(request("/api/merchant/contracts/current"),{FINANCE_DB:db,CONTRACT_SIGNING_MODE:"staging"},new URL("https://x/api/merchant/contracts/current"),cors,{ok:true,session:{merchant_id:"merchant-a",roles:"staff",email:"owner@merchant.test"}}); assert.equal(response.status,403); });
test("C49 Commercial terms payment plans are mutually exclusive", () => { const db=new D1(); db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('m','M','商家','active')").run(); assert.throws(()=>db.sqlite.prepare("INSERT INTO merchant_contract_commercial_terms(id,merchant_id,plan_code,plan_name,list_price_minor,discount_price_minor,contract_term_months,payment_plan,upfront_amount_minor,offset_target_amount_minor,included_services_json,excluded_services_json,attachments_json,start_date,service_period_end,renewal_terms,created_by,terms_hash) VALUES('t','m','p','p',1,1,1,'upfront_18000',1,1,'[]','[]','{}','2026-01-01','2026-01-31','x','a','h')").run(),/CHECK/); });
test("C50 Tax reserve cannot be enabled without accounting review", async () => { const db=new D1();db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('m','M','商家','active')").run(); const req=request("/api/admin/merchants/m/commercial-terms","POST",{...termsSnapshot(),merchant_id:"m",tax_reserve_enabled:true,confirm_approved:true},{"idempotency-key":"terms-admin-0001"}); const response=await handleMerchantContractAdmin(req,{FINANCE_DB:db},new URL(req.url),cors,{admin_user_id:"admin"}); assert.equal(response.status,409); });
test("C51 Authorized representative must confirm authority", async () => { const {db}=await seedMerchant(); db.sqlite.prepare("UPDATE merchant_contract_versions SET is_active=1 WHERE id='merchant_service_v1_0'").run(); db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,display_name) VALUES('u','merchant-a','owner@merchant.test','h','s','王')").run();db.sqlite.prepare("INSERT INTO merchant_roles(id,merchant_id,code,name) VALUES('r','merchant-a','owner','Owner')").run();db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES('i','merchant-a','terms','owner@merchant.test','h','2099-01-01',CURRENT_TIMESTAMP,'a')").run(); const req=request("/api/merchant/contracts/sign","POST",{signatory_legal_name:"王",signatory_role:"authorized_representative",authorization_confirmed:false,read:true,electronic:true,commercial_terms:true,authority:true,signature_evidence:true,signature}, {"idempotency-key":"123456789012"}); const response=await handleMerchantContractRequest(req,{FINANCE_DB:db,CONTRACT_SIGNING_MODE:"staging",CONTRACTS_BUCKET:new R2()},new URL(req.url),cors,{ok:true,session:{merchant_id:"merchant-a",user_id:"u",email:"owner@merchant.test",display_name:"王",session_id:"sess",roles:"owner"}}); assert.equal(response.status,422); });
test("C52 Merchant signing writes immutable PDF and Evidence JSON", async () => { const {db}=await seedMerchant(); db.sqlite.prepare("UPDATE merchant_contract_versions SET is_active=1 WHERE id='merchant_service_v1_0'").run(); db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,display_name) VALUES('u','merchant-a','owner@merchant.test','h','s','王')").run();db.sqlite.prepare("INSERT INTO merchant_roles(id,merchant_id,code,name) VALUES('r','merchant-a','owner','Owner')").run();db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES('i','merchant-a','terms','owner@merchant.test','h','2099-01-01',CURRENT_TIMESTAMP,'a')").run(); const r2=new R2(); const req=request("/api/merchant/contracts/sign","POST",{signatory_legal_name:"王",signatory_role:"legal_representative",legal_representative_name:"王",read:true,electronic:true,commercial_terms:true,authority:true,signature_evidence:true,signature}, {"idempotency-key":"123456789012"}); const auth={ok:true,session:{merchant_id:"merchant-a",user_id:"u",email:"owner@merchant.test",display_name:"王",session_id:"sess",roles:"owner"}}; const response=await handleMerchantContractRequest(req,{FINANCE_DB:db,CONTRACT_SIGNING_MODE:"staging",CONTRACTS_BUCKET:r2},new URL(req.url),cors,auth); assert.equal(response.status,201); assert.equal(r2.objects.size,2); assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_contract_artifacts").get().c,2); });
test("C53 Merchant sign replay does not duplicate artifacts", async () => { const {db}=await seedMerchant(); db.sqlite.prepare("UPDATE merchant_contract_versions SET is_active=1 WHERE id='merchant_service_v1_0'").run(); db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,display_name) VALUES('u','merchant-a','owner@merchant.test','h','s','王')").run();db.sqlite.prepare("INSERT INTO merchant_roles(id,merchant_id,code,name) VALUES('r','merchant-a','owner','Owner')").run();db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES('i','merchant-a','terms','owner@merchant.test','h','2099-01-01',CURRENT_TIMESTAMP,'a')").run(); const r2=new R2(),data={signatory_legal_name:"王",signatory_role:"legal_representative",legal_representative_name:"王",read:true,electronic:true,commercial_terms:true,authority:true,signature_evidence:true,signature},headers={"idempotency-key":"123456789012"},auth={ok:true,session:{merchant_id:"merchant-a",user_id:"u",email:"owner@merchant.test",display_name:"王",session_id:"sess",roles:"owner"}},env={FINANCE_DB:db,CONTRACT_SIGNING_MODE:"staging",CONTRACTS_BUCKET:r2}; const first=request("/api/merchant/contracts/sign","POST",data,headers); await handleMerchantContractRequest(first,env,new URL(first.url),cors,auth); const second=request("/api/merchant/contracts/sign","POST",data,headers); const replay=await handleMerchantContractRequest(second,env,new URL(second.url),cors,auth); assert.equal(replay.status,200); assert.equal(r2.objects.size,2); assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_contract_signatures").get().c,1); });
test("C54 public verification discloses no Merchant PII", async () => { const {db}=seedSignedMerchant(); const response=await handlePublicContractVerification({FINANCE_DB:db},"PUB",cors); const data=await response.json(); assert.equal(data.document_id,"PUB"); assert.equal("signatory_legal_name" in data,false); assert.equal("company_name" in data,false); });
test("C55 cross Merchant PDF lookup is denied", async () => { const {db}=seedSignedMerchant(); db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('other','O','他店','active')").run(); const req=request("/api/merchant/contracts/sig/pdf"); const response=await handleMerchantContractRequest(req,{FINANCE_DB:db,CONTRACTS_BUCKET:new R2()},new URL(req.url),cors,{ok:true,session:{merchant_id:"other",user_id:"u2",email:"o@x",roles:"owner"}}); assert.equal(response.status,404); });

const b64url = (bytes) => btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
const partnerIdentityEnv={PARTNER_ID_FIELD_ENCRYPTION_KEY:"test-encryption-key-at-least-32-bytes",PARTNER_ID_HASH_SECRET:"test-hmac-secret-at-least-32-bytes"};
async function seedPartner() { const db=new D1(); const idNumber="A123456789",encrypted=await encryptPartnerIdNumber(idNumber,partnerIdentityEnv.PARTNER_ID_FIELD_ENCRYPTION_KEY),idHash=await hashPartnerIdNumber(idNumber,partnerIdentityEnv.PARTNER_ID_HASH_SECRET); db.sqlite.prepare("INSERT INTO partners(id,partner_code,legal_name,display_name,email,phone,status,referral_code,id_number_encrypted,id_number_hash,id_number_last4,identity_completion_required) VALUES('partner-stage','PS','王小明','王小明','p@stage.test','0922333444','active','REF',?,?,?,0)").run(encrypted,idHash,idNumber.slice(-4)); const token="partner-test-session-token"; const tokenHash=b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)))); db.sqlite.prepare("INSERT INTO partner_sessions(id,partner_id,token_hash,assurance_level,issued_via,expires_at) VALUES('ps','partner-stage',?,'activation_invite','activation_invite','2099-01-01T00:00:00.000Z')").run(tokenHash); db.sqlite.prepare("UPDATE contract_versions SET is_active=0").run(); db.sqlite.prepare("UPDATE contract_versions SET is_active=1 WHERE id='contractor_partner_v1_4'").run(); return {db,cookie:`partner_session=${token}`}; }

test("C56 Partner Production sign is blocked while legal review pending", async () => { const {db,cookie}=await seedPartner(); const req=request("/api/partner/contract/sign-preview","POST",{legal_name:"王小明"},{cookie}); const response=await handlePartnerRequest(req,{FINANCE_DB:db,PARTNER_SESSION_SECRET:"secret"},new URL(req.url),cors); assert.equal(response.status,423); assert.equal((await response.json()).code,"LEGAL_REVIEW_REQUIRED"); });
test("C57 Partner Staging preview shows final confirmation summary", async () => { const {db,cookie}=await seedPartner(); const req=request("/api/partner/contract/sign-preview","POST",{legal_name:"王小明",read:true,electronic:true,independent:true,identity:true,block_letter_signature:true,signature},{cookie}); const response=await handlePartnerRequest(req,{FINANCE_DB:db,PARTNER_SESSION_SECRET:"secret",CONTRACT_SIGNING_MODE:"staging",...partnerIdentityEnv},new URL(req.url),cors); const data=await response.json(); assert.equal(response.status,200); assert.equal(data.version,"v1.5"); assert.equal(data.contract_period.term_months,3); assert.ok(data.important_terms.length>=5); });
test("C58 Partner Staging sign stores private PDF and Evidence", async () => { const {db,cookie}=await seedPartner(),r2=new R2(); const req=request("/api/partner/contract/sign","POST",{legal_name:"王小明",read:true,electronic:true,independent:true,identity:true,block_letter_signature:true,signature},{cookie,"idempotency-key":"partner-sign-0001"}); const response=await handlePartnerRequest(req,{FINANCE_DB:db,PARTNER_SESSION_SECRET:"secret",CONTRACT_SIGNING_MODE:"staging",CONTRACTS_BUCKET:r2,...partnerIdentityEnv},new URL(req.url),cors); assert.equal(response.status,201); assert.equal(r2.objects.size,2); const row=db.sqlite.prepare("SELECT * FROM contract_signatures WHERE partner_id='partner-stage'").get(); assert.equal(row.signature_assurance_level,STANDARD_ASSURANCE); assert.equal(row.contract_term_months,3); assert.ok(row.evidence_object_key); });
test("C59 Partner sign replay does not duplicate signature", async () => { const {db,cookie}=await seedPartner(),r2=new R2(),env={FINANCE_DB:db,PARTNER_SESSION_SECRET:"secret",CONTRACT_SIGNING_MODE:"staging",CONTRACTS_BUCKET:r2,...partnerIdentityEnv},data={legal_name:"王小明",read:true,electronic:true,independent:true,identity:true,block_letter_signature:true,signature},headers={cookie,"idempotency-key":"partner-sign-0002"}; const first=request("/api/partner/contract/sign","POST",data,headers); await handlePartnerRequest(first,env,new URL(first.url),cors); const second=request("/api/partner/contract/sign","POST",data,headers); const response=await handlePartnerRequest(second,env,new URL(second.url),cors); assert.equal(response.status,200); assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM contract_signatures WHERE partner_id='partner-stage'").get().c,1); assert.equal(r2.objects.size,2); });
test("C60 Partner operation remains locked until approved effective version is signed", async () => { const {db,cookie}=await seedPartner(); const req=request("/api/partner/dashboard","GET",undefined,{cookie}); const response=await handlePartnerRequest(req,{FINANCE_DB:db,PARTNER_SESSION_SECRET:"secret"},new URL(req.url),cors); const data=await response.json(); assert.equal(data.operation_locked,true); assert.equal(data.operation_lock_code,"PARTNER_CONTRACT_REQUIRED"); });
