import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { handleMerchantAdmin } from "../src/merchant-admin.js";
import { merchantOverrideRequested } from "../src/index.js";
import { assignMerchantPlan } from "../src/merchant-plan-catalog.js";

class Statement { constructor(statement){this.statement=statement;this.values=[];} bind(...values){this.values=values;return this;} async run(){const r=this.statement.run(...this.values);return{meta:{changes:Number(r.changes||0)}};} async first(){return this.statement.get(...this.values)||null;} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");for(const name of readdirSync(new URL("../migrations",import.meta.url)).filter((x)=>/^\d+.*\.sql$/.test(x)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),"utf8"));} prepare(sql){return new Statement(this.sqlite.prepare(sql));} async batch(items){return Promise.all(items.map((x)=>x.run()));} }
const cors={};
const req=(path,method="GET",body)=>new Request(`https://worker.test${path}`,{method,headers:body?{"content-type":"application/json"}:{},...(body?{body:JSON.stringify(body)}:{})});
const auth=(merchantId="merchant-a")=>({session:{merchant_id:merchantId,user_id:`user-${merchantId}`,platform_member_id:`member-${merchantId}`,merchant_name:`${merchantId} 店`,merchant_status:"active",phone_normalized:merchantId==="merchant-a"?"0911111111":"0922222222",roles:"owner"}});
async function call(db,merchantId,path,method="GET",body){const request=req(path,method,body);return handleMerchantAdmin(request,{FINANCE_DB:db},new URL(request.url),cors,auth(merchantId));}

async function seed(db,id="merchant-a",active=false,editable=false){
  db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES(?,?,?,'contract_required')").run(id,id,`${id} 店`);
  db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,status,display_name,phone_normalized,auth_mode) VALUES(?,?,?,'PASSWORDLESS_DISABLED','','active','商家管理者',?,'passwordless_phone')").run(`user-${id}`,id,`${id}@test.invalid`,id==="merchant-a"?"0911111111":"0922222222");
  db.sqlite.prepare("INSERT INTO merchant_onboarding_states(merchant_id,registration_mode,state,operation_locked,commercial_terms_approval_required) VALUES(?,'standard_self_service','registered',1,0)").run(id);
  const assigned=await assignMerchantPlan(db,id,`user-${id}`,editable ? "baiye_commerce_ai_45000" : "baiye_standard_18000_addons",24);
  const terms=db.sqlite.prepare("SELECT * FROM merchant_contract_commercial_terms WHERE id=?").get(assigned.commercial_terms_id);
  if(active){
    db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES(?,?,?,?,?,'2099-01-01',CURRENT_TIMESTAMP,'test')").run(`invite-${id}`,id,terms.id,`${id}@test.invalid`,`hash-${id}`);
    db.sqlite.prepare(`INSERT INTO merchant_contract_signatures(id,public_id,merchant_id,merchant_user_id,contract_version_id,commercial_terms_id,signatory_legal_name,signatory_role,legal_representative_name,company_name,signed_at,contract_content_hash,commercial_terms_hash,signature_hash,signature_data,document_hash,pdf_hash,consent_version,invite_id,session_id_hash,r2_key,evidence_object_key,status) VALUES(?,?,?,?,?,?,'測試管理者','legal_representative','測試管理者',?,CURRENT_TIMESTAMP,'content','terms','signature','{}','document','pdf','v1',?,'session','private.pdf','private.json','VALID')`).run(`signature-${id}`,`public-${id}`,id,`user-${id}`,editable ? "merchant_commerce_ai_v1_0_45000" : "merchant_service_v1_2_18000_addons",terms.id,`${id} 店`,`invite-${id}`);
    db.sqlite.prepare("UPDATE merchant_onboarding_states SET state='active',operation_locked=0,contract_signed_at=CURRENT_TIMESTAMP WHERE merchant_id=?").run(id);
  }
}

test("MA01 migration preserves internal owner and adds administrator audit",()=>{const db=new D1();assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_owner_links'").get());assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_admin_audit_logs'").get());});
test("MA02 unsigned administrator is pending activation",async()=>{const db=new D1();await seed(db);const data=await (await call(db,"merchant-a","/api/merchant-admin/dashboard")).json();assert.equal(data.administrator.display_role,"管理者");assert.equal(data.administrator.internal_role,"merchant_owner");assert.equal(data.administrator.status,"PENDING_ACTIVATION");assert.equal(data.operation_locked,true);});
test("MA03 standard administrator cannot directly edit managed content",async()=>{const db=new D1();await seed(db);const response=await call(db,"merchant-a","/api/merchant-admin/profile","PATCH",{brand_name:"禁止"});assert.equal(response.status,403);assert.equal((await response.json()).code,"MERCHANT_CONTENT_EDIT_DISABLED");});
test("MA04 active commerce administrator can update content and audit before/after",async()=>{const db=new D1();await seed(db,"merchant-a",true,true);const response=await call(db,"merchant-a","/api/merchant-admin/profile","PATCH",{brand_name:"A 品牌",business_description:"介紹"});assert.equal(response.status,200);assert.equal(db.sqlite.prepare("SELECT brand_name FROM merchant_admin_profiles WHERE merchant_id='merchant-a'").get().brand_name,"A 品牌");const log=db.sqlite.prepare("SELECT action,role,after_json FROM merchant_admin_audit_logs").get();assert.equal(log.action,"merchant.profile.updated");assert.equal(log.role,"merchant_owner");assert.match(log.after_json,/A 品牌/);});
test("MA05 legal fields use a separate change flow",async()=>{const db=new D1();await seed(db,"merchant-a",true,true);const response=await call(db,"merchant-a","/api/merchant-admin/profile","PATCH",{tax_id:"12345678"});assert.equal(response.status,409);assert.equal((await response.json()).code,"LEGAL_PROFILE_CHANGE_REQUIRED");});
test("MA06 foreign merchant id is rejected",async()=>{const db=new D1();await seed(db,"merchant-a",true,true);await seed(db,"merchant-b",true,true);const response=await call(db,"merchant-a","/api/merchant-admin/profile","PATCH",{merchant_id:"merchant-b",brand_name:"攻擊"});assert.equal(response.status,403);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_admin_profiles WHERE merchant_id='merchant-b'").get().c,0);});
test("MA07 member list is tenant-scoped and phone masked",async()=>{const db=new D1();await seed(db,"merchant-a",true);await seed(db,"merchant-b",true);for(const id of ["merchant-a","merchant-b"]){db.sqlite.prepare("INSERT INTO merchant_ordering_settings(merchant_id,display_name) VALUES(?,?)").run(id,id);db.sqlite.prepare("INSERT INTO ordering_customers(id,display_name,phone_normalized,phone_display) VALUES(?,?,?,?)").run(`customer-${id}`,id,id==="merchant-a"?"0933333333":"0944444444","masked");db.sqlite.prepare("INSERT INTO merchant_ordering_memberships(id,merchant_id,customer_id,membership_no,consent_version,consented_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)").run(`rel-${id}`,id,`customer-${id}`,`MBR-${id}`,"v1");}const data=await(await call(db,"merchant-a","/api/merchant-admin/members")).json();assert.equal(data.members.length,1);assert.equal(data.members[0].id,"rel-merchant-a");assert.doesNotMatch(JSON.stringify(data),/0933333333|0944444444/);});
test("MA08 pricing comes from platform config rather than UI hardcode",async()=>{const db=new D1();await seed(db,"merchant-a",true);const data=await(await call(db,"merchant-a","/api/merchant-admin/pricing")).json();assert.deepEqual(data.items.map((x)=>x.amount_minor),[800000,1400000,2200000]);});
test("MA09 LINE endpoint never exposes provider secrets",async()=>{const db=new D1();await seed(db,"merchant-a",true);db.sqlite.prepare("INSERT INTO merchant_line_integrations(merchant_id,enabled,basic_id,display_name,add_friend_url) VALUES('merchant-a',1,'@demo','Demo LINE','https://lin.ee/demo')").run();const data=await(await call(db,"merchant-a","/api/merchant-admin/line")).json();assert.equal(data.secrets_exposed,false);assert.equal(data.integration.basic_id,"@demo");assert.equal("channel_secret" in data.integration,false);});
test("MA10 account exposes safe sessions only",async()=>{const db=new D1();await seed(db,"merchant-a",true);const data=await(await call(db,"merchant-a","/api/merchant-admin/account")).json();assert.equal(data.display_role,"管理者");assert.match(data.phone_masked,/\*/);assert.equal(JSON.stringify(data).includes("token_hash"),false);});
test("MA11 UI uses administrator display copy and mobile breakpoints",()=>{const page=readFileSync(new URL("../../src/pages/MerchantAdminPages.tsx",import.meta.url),"utf8"),styles=readFileSync(new URL("../../src/styles.css",import.meta.url),"utf8");assert.match(page,/商家管理中心/);assert.match(page,/管理者權限/);assert.doesNotMatch(page,/Merchant Owner|商家 Owner|商家擁有者/);assert.match(styles,/@media\(max-width:560px\).*merchant-admin-shell/s);});
test("MA12 coupon remains absent from administrator UI",()=>{const page=readFileSync(new URL("../../src/pages/MerchantAdminPages.tsx",import.meta.url),"utf8");assert.doesNotMatch(page,/優惠券|折價券|NT\$100|迎新券/);});
test("MA13 forged merchant query is rejected before tenant handler",async()=>{const request=req("/api/merchant-admin/profile?merchant_id=merchant-b");assert.equal(await merchantOverrideRequested(request,new URL(request.url),"merchant-a"),true);});
test("MA14 forged merchant mutation body is rejected before tenant handler",async()=>{const request=req("/api/merchant-admin/ordering/items/item-b","PATCH",{merchant_id:"merchant-b",price_minor:1});assert.equal(await merchantOverrideRequested(request,new URL(request.url),"merchant-a"),true);});
test("MA15 own merchant id remains accepted",async()=>{const request=req("/api/merchant-admin/profile","PATCH",{merchant_id:"merchant-a",brand_name:"A"});assert.equal(await merchantOverrideRequested(request,new URL(request.url),"merchant-a"),false);});
