import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { handleMerchantStandardAddons, handleMerchantStandardAddonsAdmin, priceAddon, STANDARD_ADDON_PLAN } from "../src/merchant-standard-addons.js";

class Statement { constructor(statement){this.statement=statement;this.values=[];} bind(...values){this.values=values;return this;} async run(){const r=this.statement.run(...this.values);return{meta:{changes:Number(r.changes||0)}};} async first(){return this.statement.get(...this.values)||null;} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");for(const name of readdirSync(new URL("../migrations",import.meta.url)).filter((x)=>/^\d+.*\.sql$/.test(x)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),"utf8"));} prepare(sql){return new Statement(this.sqlite.prepare(sql));} async batch(items){return Promise.all(items.map((x)=>x.run()));} }
class R2 { objects=new Map(); async put(key,value){this.objects.set(key,value);} async get(key){const value=this.objects.get(key);return value?{body:value}:null;} async delete(key){this.objects.delete(key);} }
const auth={session:{merchant_id:"merchant-addon",user_id:"merchant-owner",roles:"owner"}};
const admin={admin_user_id:"admin-1"};
const req=(path,method="GET",body)=>new Request(`https://worker.test${path}`,{method,headers:{"user-agent":"addon-v2-test",...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});
const merchantCall=(db,path,method="GET",body,bucket=new R2())=>{const request=req(path,method,body);return handleMerchantStandardAddons(request,{FINANCE_DB:db,CONTRACTS_BUCKET:bucket,CONTRACT_SIGNING_MODE:"staging"},new URL(request.url),{},auth);};
const adminCall=(db,path,method="GET",body)=>{const request=req(path,method,body);return handleMerchantStandardAddonsAdmin(request,{FINANCE_DB:db},new URL(request.url),{},admin);};

function seed(db,{signed=true}={}) {
  db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('merchant-addon','M-ADDON','美玲拼布','active')").run();
  db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,status,display_name) VALUES('merchant-owner','merchant-addon','owner@test.invalid','x','x','active','美玲')").run();
  if (!signed) return;
  db.sqlite.prepare("INSERT INTO merchant_contract_commercial_terms(id,merchant_id,plan_code,plan_name,list_price_minor,discount_price_minor,currency,contract_term_months,payment_plan,upfront_amount_minor,offset_target_amount_minor,tax_reserve_enabled,withholding_enabled,included_services_json,excluded_services_json,attachments_json,start_date,service_period_end,renewal_terms,status,created_by,approved_by,approved_at,terms_hash) VALUES('terms-addon','merchant-addon','baiye_standard_18000_addons','標準版',1800000,1800000,'TWD',24,'upfront_18000',1800000,0,0,0,'[]','[]','{}','2026-09-02','2028-09-01','依約','approved','admin','admin',CURRENT_TIMESTAMP,'terms-hash')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_invites(id,merchant_id,commercial_terms_id,email,token_hash,expires_at,used_at,created_by) VALUES('invite-addon','merchant-addon','terms-addon','owner@test.invalid','invite-hash','2099-01-01',CURRENT_TIMESTAMP,'admin')").run();
  db.sqlite.prepare("INSERT INTO merchant_contract_signatures(id,public_id,merchant_id,merchant_user_id,contract_version_id,commercial_terms_id,signatory_legal_name,signatory_role,legal_representative_name,company_name,signed_at,contract_content_hash,commercial_terms_hash,signature_hash,signature_data,document_hash,pdf_hash,consent_version,invite_id,session_id_hash,r2_key,evidence_object_key,status) VALUES('main-signature','MAIN-PUBLIC','merchant-addon','merchant-owner','merchant_service_v1_2_18000_addons','terms-addon','美玲','legal_representative','美玲','美玲拼布',CURRENT_TIMESTAMP,'content','terms-hash','signature','{}','document','pdf','v2','invite-addon','session','main.pdf','main.json','VALID')").run();
}

test("ADDON-V2-01 immutable plan preserves Meiling mode",()=>{const db=new D1();const plan=db.sqlite.prepare("SELECT * FROM platform_service_plans WHERE code='baiye_standard_18000_addons'").get();assert.equal(plan.base_price_minor,1800000);assert.equal(plan.service_months,24);assert.equal(plan.base_product_limit,20);assert.equal(plan.merchant_content_editable,0);assert.equal(plan.contract_version_id,"merchant_service_v1_2_18000_addons");});
test("ADDON-V2-02 existing v1.1 remains and v1.2 is a new immutable version",()=>{const db=new D1();assert.ok(db.sqlite.prepare("SELECT id FROM merchant_contract_versions WHERE id='merchant_service_v1_1_18000'").get());assert.ok(db.sqlite.prepare("SELECT id FROM merchant_contract_versions WHERE id='merchant_service_v1_2_18000_addons'").get());});
test("ADDON-V2-03 18k only renders no Annex B",()=>{const migration=readFileSync(new URL("../migrations/0025_contract_standard_addons.sql",import.meta.url),"utf8");assert.match(migration,/本次主契約沒有加購時，不產生附件 B|附件 B／補充協議/);assert.equal(STANDARD_ADDON_PLAN.baseAmountMinor,1800000);});
test("ADDON-V2-04 cart total is server-calculated NT$26,000",async()=>{const db=new D1();seed(db,{signed:false});const response=await adminCall(db,"/api/admin/addon-quotes","POST",{merchant_id:"merchant-addon",contract_total_minor:1,items:[{code:"simple_cart",quantity:1}]});const data=await response.json();assert.equal(response.status,201);assert.equal(data.addon_amount_minor,800000);assert.equal(data.contract_total_minor,2600000);});
test("ADDON-V2-05 checkout total is NT$32,000",()=>{const db=new D1();const c=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code='external_checkout_cart'").get();assert.equal(1800000+priceAddon(c,1).amountMinor,3200000);});
test("ADDON-V2-06 50-product request adds one NT$3,000 block after base 20",()=>{const db=new D1();const c=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code='bulk_products_50'").get();assert.equal(priceAddon(c,50).amountMinor,300000);});
test("ADDON-V2-07 payment API and custom items require an Admin quote",()=>{const db=new D1();for(const code of ["payment_api","custom_page"]){const c=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code=?").get(code);assert.throws(()=>priceAddon(c,1),/Admin/);}const payment=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code='payment_api'").get();assert.equal(priceAddon(payment,1,2500000).amountMinor,2500000);});
test("ADDON-V2-08 manual edit tiers and product minimum are centralized",()=>{const db=new D1();const manual=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code='manual_content_changes'").get();const products=db.sqlite.prepare("SELECT * FROM platform_addon_pricing_config WHERE code='new_product_listing'").get();assert.equal(priceAddon(manual,3).amountMinor,60000);assert.equal(priceAddon(manual,4).amountMinor,80000);assert.equal(priceAddon(products,1).amountMinor,60000);assert.equal(priceAddon(products,4).amountMinor,80000);});
test("ADDON-V2-09 merchant submits audited content change request",async()=>{const db=new D1();seed(db,{signed:false});const response=await merchantCall(db,"/api/merchant-admin/content-change-requests","POST",{items:"替換首頁照片",text:"新的介紹",images:["https://example.test/a.jpg"]});assert.equal(response.status,201);assert.equal(db.sqlite.prepare("SELECT status FROM merchant_content_change_requests").get().status,"SUBMITTED");assert.equal(db.sqlite.prepare("SELECT action FROM merchant_addon_audit_logs").get().action,"content_change_request.submitted");});
test("ADDON-V2-10 quote acceptance creates Annex B addendum without changing main signature",async()=>{const db=new D1();seed(db);const issued=await(await adminCall(db,"/api/admin/addon-quotes","POST",{merchant_id:"merchant-addon",items:[{code:"simple_cart",quantity:1}]})).json();const response=await merchantCall(db,`/api/merchant-admin/addon-quotes/${issued.id}/accept`,"POST",{});const data=await response.json();assert.equal(response.status,201);assert.equal(data.contract_total_minor,2600000);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_contract_signatures").get().c,1);const annex=JSON.parse(db.sqlite.prepare("SELECT annex_b_json FROM merchant_contract_addenda").get().annex_b_json);assert.equal(annex.title,"附件 B｜加購服務");assert.equal(annex.items[0].label,"簡易購物車");});
test("ADDON-V2-11 signed addendum stores PDF/evidence and audits signature",async()=>{const db=new D1(),bucket=new R2();seed(db);const issued=await(await adminCall(db,"/api/admin/addon-quotes","POST",{merchant_id:"merchant-addon",items:[{code:"external_checkout_cart",quantity:1}]})).json();const accepted=await(await merchantCall(db,`/api/merchant-admin/addon-quotes/${issued.id}/accept`,"POST",{},bucket)).json();const signature={strokes:[[[1,1],[2,2],[3,3],[4,4]],[[5,5],[6,6],[7,7]]]};const response=await merchantCall(db,`/api/merchant-admin/addenda/${accepted.addendum_id}/sign`,"POST",{signatory_legal_name:"美玲",signature,read:true,electronic:true,commercial_terms:true,authority:true,signature_evidence:true},bucket);assert.equal(response.status,201);const row=db.sqlite.prepare("SELECT * FROM merchant_contract_addenda WHERE id=?").get(accepted.addendum_id);assert.equal(row.status,"SIGNED");assert.ok(row.pdf_hash);assert.equal(bucket.objects.size,2);assert.throws(()=>db.sqlite.prepare("UPDATE merchant_contract_addenda SET contract_total_minor=1 WHERE id=?").run(accepted.addendum_id),/IMMUTABLE/);});
test("ADDON-V2-12 payment status remains auditable after signature",async()=>{const db=new D1();seed(db);const issued=await(await adminCall(db,"/api/admin/addon-quotes","POST",{merchant_id:"merchant-addon",items:[{code:"simple_cart",quantity:1}]})).json();const accepted=await(await merchantCall(db,`/api/merchant-admin/addon-quotes/${issued.id}/accept`,"POST",{})).json();db.sqlite.prepare("UPDATE merchant_contract_addenda SET status='SIGNED' WHERE id=?").run(accepted.addendum_id);const response=await adminCall(db,`/api/admin/addenda/${accepted.addendum_id}/payment`,"PATCH",{payment_status:"PAID"});assert.equal(response.status,200);assert.equal(db.sqlite.prepare("SELECT payment_status FROM merchant_contract_addenda WHERE id=?").get(accepted.addendum_id).payment_status,"PAID");assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM merchant_addon_audit_logs WHERE action='addendum.payment_status.updated'").get().c,1);});
test("ADDON-V2-13 UI contains request flow and no full CMS editor route",()=>{const ui=readFileSync(new URL("../../src/pages/MerchantAdminPages.tsx",import.meta.url),"utf8");assert.match(ui,/申請內容修改/);assert.match(ui,/merchant_content_editable = false/);assert.doesNotMatch(ui,/to="\/dashboard\/site-editor"|to="\/merchant-admin\/ordering"/);});
