import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { handlePartnerRequest, partnerWorkflowStatus } from "../src/partner.js";
import { ensurePlatformMember, normalizeTaiwanMobile } from "../src/platform-membership.js";

class Statement {
  constructor(statement) { this.statement = statement; this.values = []; }
  bind(...values) { this.values = values; return this; }
  async run() { const result = this.statement.run(...this.values); return { meta: { changes: Number(result.changes || 0) } }; }
  async first() { return this.statement.get(...this.values) || null; }
  async all() { return { results: this.statement.all(...this.values) }; }
}
class D1 {
  constructor() {
    this.sqlite = new DatabaseSync(":memory:");
    const files = readdirSync(new URL("../migrations", import.meta.url)).filter((name) => /^\d+.*\.sql$/.test(name)).sort();
    for (const file of files) this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`, import.meta.url), "utf8"));
  }
  prepare(sql) { return new Statement(this.sqlite.prepare(sql)); }
  async batch(statements) { const results = []; for (const statement of statements) results.push(await statement.run()); return results; }
}
const cors = { "access-control-allow-origin": "https://staging.example" };
const env = (db) => ({ FINANCE_DB: db, PUBLIC_SITE_URL: "https://staging.example", CONTRACT_SIGNING_MODE: "staging" });
const payload = (suffix = "01", overrides = {}) => ({ legal_name: `測試夥伴${suffix}`, display_name: `夥伴${suffix}`, email: `auto-${suffix}@example.test`, phone: `09123456${suffix}`, company_name: "", tax_id: "", note: "", consent: true, ...overrides });
function request(path, data, headers = {}) { return new Request(`https://worker.test${path}`, { method: "POST", headers: { "content-type": "application/json", "CF-Connecting-IP": "203.0.113.9", ...headers }, body: JSON.stringify(data) }); }
async function apply(db, data) { const req = request("/api/partner/apply", data); const response = await handlePartnerRequest(req, env(db), new URL(req.url), cors); return { response, data: await response.json() }; }

test("A01 正常申請立即核准", async () => { const db = new D1(); const result = await apply(db, payload()); assert.equal(result.response.status, 201); assert.equal(result.data.approval_mode, "automatic"); });
test("A02 正常申請不進 pending_review", async () => { const db = new D1(); const result = await apply(db, payload()); assert.equal(result.data.state, "pending_activation"); assert.notEqual(result.data.state, "pending_review"); });
test("A03 approved_at 立即寫入", async () => { const db = new D1(); const result = await apply(db, payload()); assert.ok(result.data.approved_at); assert.ok(db.sqlite.prepare("SELECT approved_at FROM partners WHERE id=?").get(result.data.id).approved_at); });
test("A04 Partner Code 為不可重複 AG 六碼", async () => { const db = new D1(); const a = await apply(db, payload("01")); const b = await apply(db, payload("02")); assert.match(a.data.partner_code, /^AG\d{6}$/); assert.notEqual(a.data.partner_code, b.data.partner_code); });
test("A05 Referral Code 與 Partner Code 建立", async () => { const db = new D1(); const result = await apply(db, payload()); const row = db.sqlite.prepare("SELECT partner_code,referral_code FROM partners WHERE id=?").get(result.data.id); assert.equal(row.referral_code, row.partner_code); });
test("A06 申請同時建立 Activation Invite", async () => { const db = new D1(); const result = await apply(db, payload()); assert.ok(result.data.activation_url); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partner_invites").get().n, 1); });
test("A07 Invite 只保存 Token Hash", async () => { const db = new D1(); const result = await apply(db, payload()); const raw = new URL(result.data.activation_url).hash.split("token=")[1]; const stored = db.sqlite.prepare("SELECT token_hash FROM partner_invites").get().token_hash; assert.notEqual(decodeURIComponent(raw), stored); assert.ok(stored.length >= 40); });
test("A08 Invite 有效期不超過 24 小時", async () => { const db = new D1(); const result = await apply(db, payload()); const hours = (new Date(result.data.activation_expires_at) - Date.now()) / 36e5; assert.ok(hours > 23.9 && hours <= 24.01); });
test("A09 Duplicate Email 不建立第二筆", async () => { const db = new D1(); await apply(db, payload()); const second = await apply(db, payload()); assert.equal(second.data.code, "PARTNER_ALREADY_APPROVED"); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partners").get().n, 1); });
test("A10 Duplicate Phone 不同 Email 被拒絕", async () => { const db = new D1(); await apply(db, payload()); const second = await apply(db, payload("02", { phone: "0912345601" })); assert.equal(second.response.status, 409); assert.equal(second.data.code, "PARTNER_PHONE_ALREADY_REGISTERED"); });
test("A11 Existing Active Partner 回登入", async () => { const db = new D1(); const first = await apply(db, payload()); db.sqlite.prepare("UPDATE partners SET status='active' WHERE id=?").run(first.data.id); const second = await apply(db, payload()); assert.equal(second.response.status, 409); assert.equal(second.data.next_url, "/partner/login"); });
test("A12 Existing Pending Activation 重新取得安全 Invite", async () => { const db = new D1(); const first = await apply(db, payload()); const second = await apply(db, payload()); assert.equal(second.response.status, 200); assert.notEqual(first.data.activation_url, second.data.activation_url); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partner_invites WHERE used_at IS NULL").get().n, 1); });
test("A13 Reapply 不重複 Partner", async () => { const db = new D1(); await apply(db, payload()); await apply(db, payload()); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partners").get().n, 1); });
test("A14 Apply Rate Limit", async () => { const db = new D1(); let result; for (let i = 0; i < 10; i += 1) result = await apply(db, payload()); assert.equal(result.response.status, 429); assert.equal(result.data.code, "RATE_LIMITED"); });
test("A15 Consent Required", async () => { const db = new D1(); const result = await apply(db, payload("01", { consent: false })); assert.equal(result.response.status, 400); });
test("A16 Platform Member Created", async () => { const db = new D1(); await apply(db, payload()); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_members").get().n, 1); });
test("A17 Existing Platform Member Reused", async () => { const db = new D1(); await ensurePlatformMember(db, { phone: "0912345601", source: "phone", privacyConsentVersion: "test", issueSession: false }); await apply(db, payload()); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_members").get().n, 1); });
test("A18 NT$100 Coupon Created", async () => { const db = new D1(); await apply(db, payload()); const row = db.sqlite.prepare("SELECT p.discount_value_minor,c.status FROM platform_member_coupons c JOIN platform_coupon_campaigns p ON p.id=c.campaign_id").get(); assert.deepEqual([row.discount_value_minor, row.status], [10000, "claimed"]); });
test("A19 Reapply 不重複 Coupon", async () => { const db = new D1(); await apply(db, payload()); await apply(db, payload()); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_coupons").get().n, 1); });
test("A20 Welcome Response", async () => { const db = new D1(); const result = await apply(db, payload()); assert.equal(result.data.welcome.show, true); assert.match(result.data.welcome.message, /NT\$100/); });
test("A21 Admin 單筆人工核准已移除", async () => { const db = new D1(); const first = await apply(db, payload()); const req = request(`/api/admin/partners/${first.data.id}`, { action: "approve" }); req.method; const patch = new Request(req.url, { method: "PATCH", headers: req.headers, body: JSON.stringify({ action: "approve" }) }); const response = await handlePartnerRequest(patch, env(db), new URL(patch.url), cors, true); assert.equal(response.status, 410); });
test("A22 Suspended 不可重新申請", async () => { const db = new D1(); const first = await apply(db, payload()); db.sqlite.prepare("UPDATE partners SET status='suspended' WHERE id=?").run(first.data.id); const second = await apply(db, payload()); assert.equal(second.data.code, "PARTNER_SUSPENDED"); });
test("A23 Terminated 不可自動復活", async () => { const db = new D1(); const first = await apply(db, payload()); db.sqlite.prepare("UPDATE partners SET status='terminated' WHERE id=?").run(first.data.id); const second = await apply(db, payload()); assert.equal(second.data.code, "PARTNER_TERMINATED"); assert.equal(db.sqlite.prepare("SELECT status FROM partners WHERE id=?").get(first.data.id).status, "terminated"); });
test("A24 Audit 完整且不保存手機", async () => { const db = new D1(); const result = await apply(db, payload()); const actions = db.sqlite.prepare("SELECT action,metadata FROM audit_logs WHERE entity_id=? ORDER BY action").all(result.data.id); assert.deepEqual(actions.map((x) => x.action), ["partner.activation_invite_created", "partner.application_submitted", "partner.auto_approved"]); assert.equal(actions.some((x) => String(x.metadata).includes("0912345601")), false); });
test("A25 Contract Legal Review 仍 Locked", async () => { const db = new D1(); const result = await apply(db, payload()); assert.equal(result.data.contract.signing_available, false); assert.equal(result.data.contract.legal_review_status, "pending_review"); });
test("A26 Partner Operation Gate 判定未簽署", () => { const state = partnerWorkflowStatus({ status: "active", contract_status: "unsigned", approved_at: new Date().toISOString() }); assert.equal(state.code, "PARTNER_CONTRACT_REQUIRED"); });
test("A27 Phone 正規化後防重", async () => { const db = new D1(); await apply(db, payload()); const second = await apply(db, payload("02", { phone: "+886912345601" })); assert.equal(second.data.code, "PARTNER_PHONE_ALREADY_REGISTERED"); });
test("A28 平台會員不因申請發出可接管舊帳戶 Session", async () => { const db = new D1(); await ensurePlatformMember(db, { phone: "0912345601", source: "phone", privacyConsentVersion: "test", issueSession: false }); const result = await apply(db, payload()); assert.equal(result.data.member_session, undefined); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_sessions").get().n, 0); });
test("A29 身份鎖阻止同手機競態重複", () => { const db = new D1(); db.sqlite.prepare("INSERT INTO partners(id,partner_code,legal_name,display_name,email,phone,status,referral_code) VALUES('a','AGA','甲','甲','a@x.test','0911111111','pending_contract','AGA'),('b','AGB','乙','乙','b@x.test','0922222222','pending_contract','AGB')").run(); db.sqlite.prepare("INSERT INTO partner_application_identities(phone_normalized,partner_id) VALUES('0911111111','a')").run(); assert.throws(() => db.sqlite.prepare("INSERT INTO partner_application_identities(phone_normalized,partner_id) VALUES('0911111111','b')").run(), /UNIQUE/); });
test("A30 歷史待處理狀態不再顯示一般 pending_review", () => { const state = partnerWorkflowStatus({ status: "pending_contract", approved_at: null }); assert.equal(state.state, "historical_pending"); assert.doesNotMatch(state.message, /等待.*審核/); });
test("A31 歷史批次轉換需二次確認並建立 Invite", async () => { const db = new D1(); db.sqlite.prepare("INSERT INTO partners(id,partner_code,legal_name,display_name,email,phone,status,referral_code) VALUES('old','AGOLD1','舊夥伴','舊夥伴','old@example.test','0987654321','pending_contract','AGOLD1')").run(); const req = request("/api/admin/partners/auto-approve-pending", { confirm: "AUTO_APPROVE_EXISTING_PENDING_APPLICATIONS" }); const response = await handlePartnerRequest(req, env(db), new URL(req.url), cors, true); const result = await response.json(); assert.equal(response.status, 200); assert.equal(result.approved.length, 1); assert.ok(db.sqlite.prepare("SELECT approved_at FROM partners WHERE id='old'").get().approved_at); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partner_invites WHERE partner_id='old'").get().n, 1); });
test("A32 新 Invite 可通過 Hash 驗證", async () => { const db = new D1(); const result = await apply(db, payload()); const token = decodeURIComponent(new URL(result.data.activation_url).hash.split("token=")[1]); const req = request("/api/partner/invite/validate", { token }); const response = await handlePartnerRequest(req, env(db), new URL(req.url), cors); assert.equal(response.status, 200); });
test("A33 Email 與手機格式錯誤被拒絕", async () => { const db = new D1(); const email = await apply(db, payload("01", { email: "invalid" })); const phone = await apply(db, payload("01", { phone: "0212345678" })); assert.equal(email.data.code, "INVALID_EMAIL"); assert.equal(phone.data.code, "INVALID_PHONE"); });
test("A34 Blocked 平台會員手機不可自動入會", async () => { const db = new D1(); const member = await ensurePlatformMember(db, { phone: "0912345601", source: "phone", privacyConsentVersion: "test", issueSession: false }); db.sqlite.prepare("UPDATE platform_members SET status='blocked' WHERE id=?").run(member.member.id); const result = await apply(db, payload()); assert.equal(result.response.status, 403); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partners").get().n, 0); });
