import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { handlePartnerRequest } from "../src/partner.js";
import { isValidTaiwanIdNumber } from "../src/partner-identity.js";

class Statement { constructor(statement){this.statement=statement;this.values=[];} bind(...values){this.values=values;return this;} async run(){const result=this.statement.run(...this.values);return{meta:{changes:Number(result.changes||0)}};} async first(){return this.statement.get(...this.values)||null;} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");for(const file of readdirSync(new URL("../migrations",import.meta.url)).filter((name)=>/^\d+.*\.sql$/.test(name)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));} prepare(sql){return new Statement(this.sqlite.prepare(sql));} async batch(statements){const results=[];for(const statement of statements)results.push(await statement.run());return results;} }
const cors={"access-control-allow-origin":"https://baiyeconnect.com"};
const env=(db)=>({FINANCE_DB:db,PUBLIC_SITE_URL:"https://baiyeconnect.com",CONTRACT_SIGNING_MODE:"staging",PARTNER_ID_FIELD_ENCRYPTION_KEY:"test-encryption-key-at-least-32-bytes",PARTNER_ID_HASH_SECRET:"test-hmac-secret-at-least-32-bytes"});
function req(path,data,headers={}){return new Request(`https://worker.test${path}`,{method:"POST",headers:{"content-type":"application/json","CF-Connecting-IP":"203.0.113.20","x-device-id":"test-device",...headers},body:JSON.stringify(data)});}
async function call(db,path,data,headers={}){const request=req(path,data,headers);const response=await handlePartnerRequest(request,env(db),new URL(request.url),cors);return{response,data:await response.json()};}
function idNumber(suffix="01"){const base=`A1${String(Number(suffix)).padStart(7,"0")}`;for(let digit=0;digit<=9;digit+=1)if(isValidTaiwanIdNumber(`${base}${digit}`))return `${base}${digit}`;throw new Error("invalid test id");}
async function applied(db,suffix="01"){return call(db,"/api/partner/apply",{legal_name:`密碼夥伴${suffix}`,id_number:idNumber(suffix),email:`password-${suffix}@example.test`,phone:`09128888${suffix}`,password:"48261735",password_confirm:"48261735",consent:true});}
async function activated(db){const application=await applied(db);const token=decodeURIComponent(new URL(application.data.activation_url).hash.split("token=")[1]);const activation=await call(db,"/api/partner/accept-invite",{token});return{application,activation,cookie:activation.response.headers.get("set-cookie")?.split(";")[0]||""};}
async function login(db,phone="0912888801",password="48261735"){return call(db,"/api/partner/login",{phone,password});}

test("P01 Partner UI uses phone and 8-digit password",()=>{const source=readFileSync(new URL("../../src/pages/PartnerPages.tsx",import.meta.url),"utf8");const loginUi=source.split("export function PartnerLogin()")[1].split("function PartnerPasswordSetup()")[0];assert.match(loginUi,/手機號碼/);assert.match(loginUi,/8 位數字密碼/);assert.match(loginUi,/pattern="\[0-9\]\{8\}"/);assert.doesNotMatch(loginUi,/one-time-code|login\/start|login\/verify/);});
test("P02 apply creates one shared hashed credential",async()=>{const db=new D1();const result=await applied(db);assert.equal(result.response.status,201);const row=db.sqlite.prepare("SELECT password_hash,password_salt FROM platform_member_login_credentials").get();assert.ok(row.password_hash.length>30);assert.notEqual(row.password_hash,"48261735");assert.ok(row.password_salt.length>30);});
test("P03 apply requires password confirmation",async()=>{const db=new D1();const result=await call(db,"/api/partner/apply",{legal_name:"甲",id_number:"A123456789",email:"a@x.test",phone:"0912888801",password:"48261735",password_confirm:"48261734",consent:true});assert.equal(result.data.code,"PASSWORD_CONFIRMATION_MISMATCH");});
test("P04 activation creates active Partner",async()=>{const db=new D1();await activated(db);assert.equal(db.sqlite.prepare("SELECT status FROM partners").get().status,"active");});
test("P05 activation session is password authenticated",async()=>{const db=new D1();await activated(db);const row=db.sqlite.prepare("SELECT assurance_level,credential_assurance FROM partner_sessions").get();assert.equal(row.assurance_level,"activation_invite");assert.equal(row.credential_assurance,"password_authenticated");});
test("P06 activation invite is single use",async()=>{const db=new D1();const app=await applied(db);const token=decodeURIComponent(new URL(app.data.activation_url).hash.split("token=")[1]);await call(db,"/api/partner/accept-invite",{token});assert.equal((await call(db,"/api/partner/accept-invite",{token})).response.status,401);});
test("P07 phone and password login succeeds",async()=>{const db=new D1();await activated(db);const result=await login(db);assert.equal(result.response.status,200);assert.equal(result.data.code,"PARTNER_LOGIN_SUCCESS");assert.equal(result.data.next_url,"/partner/contract");});
test("P08 phone format normalizes",async()=>{const db=new D1();await activated(db);assert.equal((await login(db,"+886912888801")).response.status,200);});
test("P09 invalid phone and malformed passwords reject",async()=>{const db=new D1();await activated(db);assert.equal((await login(db,"0212345678")).data.code,"INVALID_PHONE");for(const value of ["1234567","123456789","abcd1234"])assert.equal((await login(db,"0912888801",value)).data.code,"INVALID_PASSWORD");});
test("P10 wrong or unknown identity uses generic error",async()=>{const db=new D1();await activated(db);for(const [phone,password] of [["0912888801","48261734"],["0999999999","48261735"]])assert.equal((await login(db,phone,password)).data.error,"手機號碼或密碼錯誤。");});
test("P11 legacy challenge endpoints cannot issue a challenge",async()=>{const db=new D1();await activated(db);for(const path of ["/api/partner/login/start","/api/partner/login/verify"]){const response=await handlePartnerRequest(req(path,{phone:"0912888801"}),env(db),new URL(`https://worker.test${path}`),cors);assert.equal(response.status,401);assert.doesNotMatch(await response.text(),/challenge_id|staging_code/);}});
test("P12 Partner source contains no runtime OTP mode",()=>{const source=readFileSync(new URL("../src/partner.js",import.meta.url),"utf8");assert.doesNotMatch(source,/PARTNER_OTP_MODE|staging_otp|login\/start|login\/verify/);});
test("P13 session stores only token hash and secure cookie",async()=>{const db=new D1();await activated(db);const result=await login(db);const cookie=result.response.headers.get("set-cookie");const raw=cookie.match(/partner_session=([^;]+)/)[1];assert.doesNotMatch(db.sqlite.prepare("SELECT token_hash FROM partner_sessions ORDER BY created_at DESC").get().token_hash,new RegExp(raw));assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=None/);});
test("P14 Partner and member share one identity link",async()=>{const db=new D1();const result=await applied(db);const link=db.sqlite.prepare("SELECT partner_id,member_id FROM partner_platform_member_links").get();assert.equal(link.partner_id,result.data.id);assert.ok(link.member_id);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_login_credentials WHERE platform_member_id=?").get(link.member_id).n,1);});
test("P15 logout revokes session",async()=>{const db=new D1();await activated(db);const signedIn=await login(db);const cookie=signedIn.response.headers.get("set-cookie").split(";")[0];assert.equal((await call(db,"/api/partner/logout",{}, {cookie})).response.status,200);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM partner_sessions WHERE revoked_at IS NOT NULL").get().n,1);});
test("P16 repeated wrong passwords lock credential",async()=>{const db=new D1();await activated(db);for(let i=0;i<8;i+=1)await login(db,"0912888801","48261734");assert.ok(db.sqlite.prepare("SELECT locked_until FROM platform_member_login_credentials").get().locked_until);});
test("P17 login audit contains no phone or password",async()=>{const db=new D1();await activated(db);await login(db);const logs=db.sqlite.prepare("SELECT metadata FROM audit_logs").all().map((row)=>String(row.metadata||"")).join(" ");assert.doesNotMatch(logs,/0912888801|48261735/);});
test("P18 active legacy session can configure password once",async()=>{const db=new D1();const result=await activated(db);db.sqlite.prepare("DELETE FROM platform_member_login_credentials").run();const response=await call(db,"/api/partner/password",{password:"59372468",password_confirm:"59372468"},{cookie:result.cookie});assert.equal(response.response.status,200);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_login_credentials").get().n,1);});
test("P19 contract login returnTo is restricted to Partner routes",()=>{const source=readFileSync(new URL("../../src/pages/PartnerPages.tsx",import.meta.url),"utf8");assert.match(source,/startsWith\("\/partner\/"\)/);assert.match(source,/返回原本的承攬夥伴契約頁/);});
test("P20 coupon remains disabled",async()=>{const db=new D1();await applied(db);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_coupons").get().n,0);});
