import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { MERCHANT_PLANS } from "../src/commercial-catalog.js";
import { PLAN_CONTRACT_DRAFTS } from "../src/plan-contract-definitions.js";
import { handlePlanContractAdmin, handlePlanContractPublic, handlePlanContractRequest } from "../src/plan-contracts.js";
import { sha256 } from "../src/contract-pdf.js";

class Statement { constructor(statement){this.statement=statement;this.values=[];} bind(...values){this.values=values;return this;} async run(){const result=this.statement.run(...this.values);return{meta:{changes:Number(result.changes||0)}};} async first(){return this.statement.get(...this.values)||null;} async all(){return{results:this.statement.all(...this.values)};} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");for(const file of readdirSync(new URL("../migrations",import.meta.url)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));} prepare(sql){return new Statement(this.sqlite.prepare(sql));} async batch(statements){this.sqlite.exec("BEGIN IMMEDIATE");try{const results=[];for(const statement of statements)results.push(await statement.run());this.sqlite.exec("COMMIT");return results;}catch(error){this.sqlite.exec("ROLLBACK");throw error;}} }
class R2 { objects=new Map();async put(key,value,options={}){this.objects.set(key,{bytes:value instanceof Uint8Array?value:new Uint8Array(value),options});}async get(key){const item=this.objects.get(key);return item?{body:item.bytes}:null;}async delete(key){this.objects.delete(key);} }

const cors={"access-control-allow-origin":"https://baiyeconnect.com"};
const signature={strokes:[[[12,20],[35,30],[80,22],[110,48]],[[20,60],[55,70],[120,62]]]};
const signBody=(plan)=>({legal_name:"王小明",read:true,plan_details:true,electronic:true,signature,final_confirmed:true,plan_id:plan.plan_id,plan_slug:plan.plan_slug,contract_template_id:plan.contract_template_id});
const request=(path,method="GET",data,headers={})=>new Request(`https://worker.test${path}`,{method,headers:{...(data?{"content-type":"application/json"}:{}),...headers},...(data?{body:JSON.stringify(data)}:{})});
const auth=(merchant="merchant-a")=>({ok:true,session:{merchant_id:merchant,user_id:`${merchant}-owner`,platform_member_id:`${merchant}-member`,display_name:"王小明",session_id:`${merchant}-session`,roles:"owner"}});
function fixture(){const db=new D1();for(const id of ["merchant-a","merchant-b"])db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES(?,?,?,'active')").run(id,id.toUpperCase(),`${id} 商家`);for(const id of ["merchant-a","merchant-b"])db.sqlite.prepare("INSERT INTO merchant_users(id,merchant_id,email,password_hash,password_salt,display_name) VALUES(?,?,?,?,?,?)").run(`${id}-owner`,id,`${id}@test.local`,"h","s","王小明");return{db,bucket:new R2()};}
const staging=(db,bucket)=>({FINANCE_DB:db,CONTRACTS_BUCKET:bucket,CONTRACT_SIGNING_MODE:"staging"});

test("PC01 Pricing contains exactly three stable plan mappings",()=>assert.deepEqual(MERCHANT_PLANS.map(plan=>[plan.plan_id,plan.plan_slug,plan.contract_template_id]),[["baiye_standard_18000_addons","standard-digital-18000","plan_contract_standard_v1_0"],["baiye_commerce_ai_45000","ai-commerce-45000","plan_contract_commerce_v1_0"],["baiye_softpos_24000","softpos-24000","plan_contract_softpos_v1_0"]]));
test("PC02 migration creates three independent pending-review templates",()=>{const db=new D1(),rows=db.sqlite.prepare("SELECT * FROM service_plan_contract_templates ORDER BY plan_id").all();assert.equal(rows.length,3);assert.ok(rows.every(row=>row.status==="pending_review"&&row.legal_review_required===1&&row.approved_content_hash===null));assert.equal(new Set(rows.map(row=>row.contract_snapshot)).size,3);});
test("PC03 each template hash matches its immutable draft snapshot",async()=>{const db=new D1();for(const row of db.sqlite.prepare("SELECT * FROM service_plan_contract_templates").all())assert.equal(await sha256(row.contract_snapshot),row.contract_content_hash);});
test("PC04 definitions and D1 seed remain byte-identical",()=>{const db=new D1();for(const draft of PLAN_CONTRACT_DRAFTS){const row=db.sqlite.prepare("SELECT * FROM service_plan_contract_templates WHERE id=?").get(draft.contract_template_id);assert.equal(row.contract_snapshot,draft.contract_snapshot);assert.deepEqual(JSON.parse(row.plan_details_snapshot),draft.plan_snapshot);}});
for(const plan of MERCHANT_PLANS)test(`PC map ${plan.plan_id} resolves only its contract`,async()=>{const{db}=fixture(),req=request(`/api/public/plan-contracts/${plan.plan_slug}`),response=await handlePlanContractPublic(req,{FINANCE_DB:db},new URL(req.url),cors),data=await response.json();assert.equal(response.status,200);assert.equal(data.plan_id,plan.plan_id);assert.equal(data.contract_template_id,plan.contract_template_id);assert.equal(data.plan.plan_name,plan.display_name);assert.equal(data.plan.plan_price_minor,plan.price_minor);assert.equal(data.production_signing_enabled,false);});
test("PC08 unknown contract slug is rejected",async()=>{const{db}=fixture(),req=request("/api/public/plan-contracts/not-real"),response=await handlePlanContractPublic(req,{FINANCE_DB:db},new URL(req.url),cors);assert.equal(response.status,404);});
test("PC09 Production legal gate blocks all three draft signatures",async()=>{const{db,bucket}=fixture();for(const plan of MERCHANT_PLANS){const req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign-preview`,"POST",signBody(plan)),response=await handlePlanContractRequest(req,{FINANCE_DB:db,CONTRACTS_BUCKET:bucket},new URL(req.url),cors,auth());assert.equal(response.status,423);assert.equal((await response.json()).code,"LEGAL_REVIEW_REQUIRED");}});
test("PC10 selected plan cannot submit another plan contract",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0],req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign-preview`,"POST",{...signBody(plan),plan_id:MERCHANT_PLANS[1].plan_id}),response=await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth());assert.equal(response.status,409);assert.equal((await response.json()).code,"PLAN_CONTRACT_MISMATCH");});
test("PC11 legal name, consents and signature are server-required",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0];for(const body of [{...signBody(plan),legal_name:""},{...signBody(plan),plan_details:false},{...signBody(plan),signature:{strokes:[]}}]){const req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign-preview`,"POST",body),response=await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth());assert.equal(response.status,422);}});
test("PC12 final confirmation names exact plan, price, version and signer",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[1],req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign-preview`,"POST",signBody(plan)),response=await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth()),data=await response.json();assert.deepEqual([data.plan_name,data.plan_price,data.contract_version,data.legal_name],["AI 智慧商城完整版","NT$45,000","v1.0","王小明"]);});
test("PC13 signed plan contract stores full snapshots, hashes, audit and PDF",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[2],req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":"plan-sign-0000001","user-agent":"Mozilla/5.0 (iPhone) Line/15.0","CF-Connecting-IP":"203.0.113.20"}),response=await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth()),data=await response.json(),row=db.sqlite.prepare("SELECT * FROM service_plan_contract_signatures WHERE id=?").get(data.signature_id);assert.equal(response.status,201);assert.equal(row.plan_id,plan.plan_id);assert.equal(row.plan_name,plan.display_name);assert.equal(JSON.parse(row.plan_price_snapshot).amount_minor,2400000);assert.equal(JSON.parse(row.plan_details_snapshot).activation_fee_minor,300000);assert.equal(row.contract_snapshot.includes("免 POS 機智慧點餐"),true);assert.equal(row.contract_content_hash,await sha256(row.contract_snapshot));assert.equal(JSON.parse(row.consent_states_json).plan_details,true);assert.equal(JSON.parse(row.request_metadata_json).browser,"LINE");assert.equal(row.ip_address,"203.0.113.20");assert.equal(bucket.objects.size,2);assert.ok(row.pdf_hash&&row.document_hash&&row.signature_hash);const actions=db.sqlite.prepare("SELECT action FROM service_plan_contract_events WHERE signature_id=?").all(data.signature_id).map(item=>item.action);for(const action of ["plan.contract.submit_requested","plan.contract.signed","plan.contract.pdf_generated"])assert.ok(actions.includes(action));});
test("PC14 same signing intent is idempotent",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0],headers={"idempotency-key":"plan-sign-0000002"},env=staging(db,bucket);for(let index=0;index<2;index++){const req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),headers),response=await handlePlanContractRequest(req,env,new URL(req.url),cors,auth());assert.equal(response.status,index?200:201);}assert.equal(db.sqlite.prepare("SELECT COUNT(*) count FROM service_plan_contract_signatures").get().count,1);assert.equal(bucket.objects.size,2);});
test("PC15 same member may sign a different plan as a new contract",async()=>{const{db,bucket}=fixture(),env=staging(db,bucket);for(const [index,plan] of MERCHANT_PLANS.slice(0,2).entries()){const req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":`multi-plan-sign-${index}`});assert.equal((await handlePlanContractRequest(req,env,new URL(req.url),cors,auth())).status,201);}assert.equal(db.sqlite.prepare("SELECT COUNT(*) count FROM service_plan_contract_signatures WHERE merchant_id='merchant-a'").get().count,2);});
test("PC16 signed plan id, snapshot, signature and time are immutable",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0],req=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":"immutable-plan-sign"}),data=await(await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth())).json();for(const sql of ["UPDATE service_plan_contract_signatures SET plan_id='other' WHERE id=?","UPDATE service_plan_contract_signatures SET signed_at='changed' WHERE id=?","DELETE FROM service_plan_contract_signatures WHERE id=?"])assert.throws(()=>db.sqlite.prepare(sql).run(data.signature_id),/IMMUTABLE/);assert.throws(()=>db.sqlite.prepare("UPDATE service_plan_contract_templates SET contract_snapshot='changed' WHERE id=?").run(plan.contract_template_id),/IMMUTABLE/);});
test("PC17 cross-merchant PDF access is denied",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0],signReq=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":"private-plan-pdf"}),signed=await(await handlePlanContractRequest(signReq,staging(db,bucket),new URL(signReq.url),cors,auth())).json(),pdfReq=request(`/api/merchant/plan-contracts/signatures/${signed.signature_id}/pdf`),response=await handlePlanContractRequest(pdfReq,staging(db,bucket),new URL(pdfReq.url),cors,auth("merchant-b"));assert.equal(response.status,404);});
test("PC18 owner PDF is viewable/downloadable with verified hash",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[1],signReq=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":"owner-plan-pdf"}),signed=await(await handlePlanContractRequest(signReq,staging(db,bucket),new URL(signReq.url),cors,auth())).json();for(const suffix of ["?view=1",""]){const req=request(`/api/merchant/plan-contracts/signatures/${signed.signature_id}/pdf${suffix}`),response=await handlePlanContractRequest(req,staging(db,bucket),new URL(req.url),cors,auth()),bytes=new Uint8Array(await response.arrayBuffer());assert.equal(response.status,200);assert.equal(response.headers.get("x-pdf-sha256"),await sha256(bytes));assert.match(response.headers.get("content-disposition"),suffix?/inline/:/attachment/);}});
test("PC19 admin can query templates, signatures, audit and PDF",async()=>{const{db,bucket}=fixture(),plan=MERCHANT_PLANS[0],signReq=request(`/api/merchant/plan-contracts/${plan.plan_slug}/sign`,"POST",signBody(plan),{"idempotency-key":"admin-plan-query"}),signed=await(await handlePlanContractRequest(signReq,staging(db,bucket),new URL(signReq.url),cors,auth())).json(),listReq=request("/api/admin/plan-contracts"),list=await(await handlePlanContractAdmin(listReq,staging(db,bucket),new URL(listReq.url),cors)).json();assert.equal(list.templates.length,3);assert.equal(list.signatures.length,1);const eventsReq=request(`/api/admin/plan-contracts/${signed.signature_id}/events`),events=await(await handlePlanContractAdmin(eventsReq,staging(db,bucket),new URL(eventsReq.url),cors)).json();assert.ok(events.items.some(item=>item.action==="plan.contract.signed"));const pdfReq=request(`/api/admin/plan-contracts/${signed.signature_id}/pdf`),pdf=await handlePlanContractAdmin(pdfReq,staging(db,bucket),new URL(pdfReq.url),cors);assert.equal(pdf.status,200);});
test("PC20 Pricing UI maps by stable slug, never array index",()=>{const source=readFileSync(new URL("../../src/pages/CommercialV13Pages.tsx",import.meta.url),"utf8");assert.match(source,/查看方案合約/);assert.match(source,/選擇方案/);assert.match(source,/plan\.plan_slug/);assert.doesNotMatch(source,/plans\[index\].*contract|contract.*plans\[index\]/);});
test("PC21 signing UI contains exact required controls and completion actions",()=>{const source=readFileSync(new URL("../../src/pages/PlanContractPage.tsx",import.meta.url),"utf8");for(const text of ["本人已閱讀並理解本方案合作契約全部內容。","本人確認所選方案、服務內容及費用資訊正確。","本人同意以電子方式簽署本契約。","確認並正式簽署","查看正式契約","下載已簽署 PDF","繼續完成方案申請"])assert.ok(source.includes(text),text);});
