import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, readdirSync } from "node:fs";
import { authenticatePlatformMember, ensurePlatformMember, handlePlatformMemberRequest, maskMemberPhone, normalizeTaiwanMobile } from "../src/platform-membership.js";

class Statement { constructor(statement) { this.statement=statement; this.values=[]; } bind(...values){this.values=values;return this;} async run(){const result=this.statement.run(...this.values);return{meta:{changes:Number(result.changes||0)}};} async first(){return this.statement.get(...this.values)||null;} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");this.sqlite.exec("PRAGMA foreign_keys=ON");for(const file of readdirSync(new URL("../migrations",import.meta.url)).filter((name)=>/^\d+.*\.sql$/.test(name)).sort())this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));} prepare(sql){return new Statement(this.sqlite.prepare(sql));} async batch(statements){this.sqlite.exec("BEGIN IMMEDIATE");try{const output=[];for(const statement of statements)output.push(await statement.run());this.sqlite.exec("COMMIT");return output;}catch(error){this.sqlite.exec("ROLLBACK");throw error;}} }
const cors={"access-control-allow-origin":"https://staging.example"};
const req=(path,method="GET",body=undefined,headers={})=>new Request(`https://worker.test${path}`,{method,headers:{...(body?{"content-type":"application/json"}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
const join=async(db,phone="0912345678",headers={})=>{const request=req("/api/members/join","POST",{phone,privacy_consent:true,consent_version:"privacy-v1",device_id:"device-a"},headers);const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db,SMS_OTP_MODE:"disabled"},new URL(request.url),cors);return{response,data:await response.json()};};

for(const [label,input,expected] of [["plain","0912345678","0912345678"],["plus","+886912345678","0912345678"],["country","886912345678","0912345678"],["hyphen","0912-345-678","0912345678"],["spaces","0912 345 678","0912345678"]])test(`M01 normalize ${label}`,()=>assert.equal(normalizeTaiwanMobile(input),expected));
test("M02 rejects landline",()=>assert.equal(normalizeTaiwanMobile("0223456789"),""));
test("M03 rejects too short phone",()=>assert.equal(normalizeTaiwanMobile("091234567"),""));
test("M04 masks phone without exposing it",()=>{const value=maskMemberPhone("0912345678");assert.match(value,/^09\*\*/);assert.doesNotMatch(value,/0912345678/);});

for(const table of ["platform_members","platform_member_sessions","platform_coupon_campaigns","platform_member_coupons","platform_coupon_funding_ledger","platform_member_welcome_events"])test(`M05 migration creates ${table}`,()=>{const db=new D1();assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table));});
test("M06 platform member schema has no password",()=>{const db=new D1();assert.equal(db.sqlite.prepare("PRAGMA table_info(platform_members)").all().some((row)=>String(row.name).includes("password")),false);});
test("M07 customer display name remains compatible",()=>{const db=new D1();assert.equal(db.sqlite.prepare("PRAGMA table_info(ordering_customers)").all().find((row)=>row.name==="display_name").notnull,1);});
test("M08 welcome campaign is claimable but redemption locked",()=>{const db=new D1(),row=db.sqlite.prepare("SELECT * FROM platform_coupon_campaigns WHERE id='platform_welcome_member_v1'").get();assert.equal(row.discount_value_minor,10000);assert.equal(row.redemption_enabled,0);});

test("M09 first join needs only phone and consent",async()=>{const db=new D1(),{response}=await join(db);assert.equal(response.status,201);});
test("M10 no name is required",async()=>{const db=new D1(),{data}=await join(db);assert.equal(db.sqlite.prepare("SELECT display_name FROM ordering_customers").get().display_name,"會員");assert.equal(data.new_member,true);});
test("M11 no email is required",async()=>{const db=new D1();await join(db);assert.equal(db.sqlite.prepare("SELECT email FROM ordering_customers").get().email,null);});
test("M12 no password is accepted or persisted",async()=>{const db=new D1();const request=req("/api/members/join","POST",{phone:"0912345678",password:"must-be-ignored",privacy_consent:true,consent_version:"v",device_id:"d"});await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members").get().c,1);});
test("M13 privacy consent is required",async()=>{const db=new D1();const request=req("/api/members/join","POST",{phone:"0912345678",privacy_consent:false,consent_version:"v"});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.equal(response.status,422);assert.equal((await response.json()).code,"PRIVACY_CONSENT_REQUIRED");});
test("M14 consent version is persisted",async()=>{const db=new D1();await join(db);assert.equal(db.sqlite.prepare("SELECT privacy_consent_version FROM ordering_customers").get().privacy_consent_version,"privacy-v1");});
test("M15 platform member is unique by customer",async()=>{const db=new D1();await join(db);assert.throws(()=>db.sqlite.prepare("INSERT INTO platform_members(id,customer_id,member_no,joined_source) SELECT 'x',id,'X','phone' FROM ordering_customers").run(),/UNIQUE/);});
test("M16 member number is opaque",async()=>{const db=new D1(),{data}=await join(db);assert.match(data.member.member_no,/^BYM-[A-F0-9]{12}$/);assert.doesNotMatch(data.member.member_no,/0912345678/);});
test("M17 first join returns welcome",async()=>{const db=new D1(),{data}=await join(db);assert.equal(data.welcome.show,true);assert.equal(data.welcome.title,"歡迎成為創百業會員！");});
test("M18 welcome event is created once",async()=>{const db=new D1();await join(db);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_welcome_events").get().c,1);});
test("M19 welcome coupon issuance is disabled",async()=>{const db=new D1(),{data}=await join(db);assert.equal(data.coupon,null);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_coupons").get().c,0);});
test("M20 disabled issuance does not set a coupon expiry",async()=>{const db=new D1(),{data}=await join(db);assert.equal(data.coupon,null);assert.equal(db.sqlite.prepare("SELECT welcome_coupon_claimed_at FROM platform_members").get().welcome_coupon_claimed_at,null);});
test("M21 session raw token is returned once",async()=>{const db=new D1(),{data}=await join(db);assert.ok(data.session.token.length>30);assert.equal(db.sqlite.prepare("SELECT token_hash FROM platform_member_sessions").get().token_hash.includes(data.session.token),false);});
test("M22 session lasts 180 days",async()=>{const db=new D1(),{data}=await join(db);const days=(new Date(data.session.expires_at)-Date.now())/86400000;assert.ok(days>179.9&&days<=180.1);});
test("M23 valid session authenticates",async()=>{const db=new D1(),{data}=await join(db);const request=req("/api/members/me","GET",undefined,{authorization:`Bearer ${data.session.token}`});assert.ok(await authenticatePlatformMember(db,request));});
test("M24 existing phone on new device requires member login",async()=>{const db=new D1();await join(db);const second=await join(db);assert.equal(second.response.status,409);assert.equal(second.data.code,"MEMBER_LOGIN_REQUIRED");assert.equal(JSON.stringify(second.data).includes("Provider"),false);});
test("M25 existing phone cannot be hijacked",async()=>{const db=new D1();await join(db);const before=db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_sessions").get().c;await join(db);assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_sessions").get().c,before);});
test("M26 same valid session reuses member",async()=>{const db=new D1(),first=await join(db);const second=await join(db,"0912345678",{authorization:`Bearer ${first.data.session.token}`});assert.equal(second.response.status,200);assert.equal(second.data.new_member,false);});
test("M27 same phone does not duplicate customer",async()=>{const db=new D1(),first=await join(db);await join(db,"0912345678",{authorization:`Bearer ${first.data.session.token}`});assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM ordering_customers").get().c,1);});
test("M28 same phone does not duplicate member",async()=>{const db=new D1(),first=await join(db);await join(db,"0912345678",{authorization:`Bearer ${first.data.session.token}`});assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members").get().c,1);});
test("M29 same phone continues to issue no coupon",async()=>{const db=new D1(),first=await join(db);await join(db,"0912345678",{authorization:`Bearer ${first.data.session.token}`});assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_coupons").get().c,0);});
test("M30 member center returns masked phone",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/me","GET",undefined,{authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);const data=await response.json();assert.equal(data.member.phone_masked,"09** *** 678");assert.equal(JSON.stringify(data).includes("0912345678"),false);});
test("M31 coupon list is hidden while historical tables remain",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/coupons","GET",undefined,{authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);const data=await response.json();assert.deepEqual(data.coupons,[]);assert.equal(data.disabled,true);});
test("M32 coupon redemption is disabled before verification logic",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/coupons/redeem","POST",{}, {authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db,MEMBERSHIP_COUPON_ISSUANCE_ENABLED:"0",PLATFORM_WELCOME_COUPON_REDEMPTION_ENABLED:"1"},new URL(request.url),cors);assert.equal((await response.json()).code,"COUPON_FEATURE_DISABLED");});
test("M33 Production coupon feature remains disabled",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/coupons/redeem","POST",{}, {authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db,MEMBERSHIP_COUPON_ISSUANCE_ENABLED:"0",PLATFORM_WELCOME_COUPON_REDEMPTION_ENABLED:"0"},new URL(request.url),cors);assert.equal((await response.json()).code,"COUPON_FEATURE_DISABLED");});
test("M34 contract origin verifies identity but not phone",async()=>{const db=new D1(),result=await ensurePlatformMember(db,{phone:"0933444555",source:"partner_contract",originVerified:true});const row=db.sqlite.prepare("SELECT * FROM platform_members WHERE id=?").get(result.member.id);assert.equal(row.membership_origin_verified,1);assert.equal(row.phone_verified,0);});
test("M35 Partner and Merchant sources reuse the identity",async()=>{const db=new D1();await ensurePlatformMember(db,{phone:"0933444555",source:"partner_contract"});await ensurePlatformMember(db,{phone:"0933444555",source:"merchant_contract"});assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_members").get().c,1);});
test("M36 contract replay issues no coupon",async()=>{const db=new D1();await ensurePlatformMember(db,{phone:"0933444555",source:"partner_contract"});await ensurePlatformMember(db,{phone:"0933444555",source:"partner_contract"});assert.equal(db.sqlite.prepare("SELECT COUNT(*) c FROM platform_member_coupons").get().c,0);});
test("M37 welcome acknowledge is persistent",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/welcome/acknowledge","POST",{}, {authorization:`Bearer ${first.data.session.token}`});await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.ok(db.sqlite.prepare("SELECT acknowledged_at FROM platform_member_welcome_events").get().acknowledged_at);});
test("M38 logout revokes session",async()=>{const db=new D1(),first=await join(db);const request=req("/api/members/logout","POST",{}, {authorization:`Bearer ${first.data.session.token}`});await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.ok(db.sqlite.prepare("SELECT revoked_at FROM platform_member_sessions").get().revoked_at);});
test("M39 expired session is rejected",async()=>{const db=new D1(),first=await join(db);db.sqlite.prepare("UPDATE platform_member_sessions SET expires_at='2000-01-01'").run();const request=req("/api/members/me","GET",undefined,{authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.equal(response.status,401);});
test("M40 blocked member is rejected",async()=>{const db=new D1(),first=await join(db);db.sqlite.prepare("UPDATE platform_members SET status='blocked'").run();const request=req("/api/members/me","GET",undefined,{authorization:`Bearer ${first.data.session.token}`});const response=await handlePlatformMemberRequest(request,{FINANCE_DB:db},new URL(request.url),cors);assert.equal(response.status,401);});
test("M41 historical funding ledger remains immutable",async()=>{const db=new D1(),first=await join(db);db.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('m','M','商家','active')").run();const memberId=first.data.member.id;db.sqlite.prepare("INSERT INTO platform_member_coupons(id,member_id,campaign_id,status,expires_at) VALUES('old-coupon',?,'platform_welcome_member_v1','claimed','2099-01-01')").run(memberId);db.sqlite.prepare("INSERT INTO platform_coupon_funding_ledger(id,coupon_id,member_id,redeeming_merchant_id,discount_minor,status,idempotency_key) VALUES('l','old-coupon',?, 'm',10000,'reserved','k')").run(memberId);assert.throws(()=>db.sqlite.prepare("UPDATE platform_coupon_funding_ledger SET discount_minor=1 WHERE id='l'").run(),/IMMUTABLE/);});
test("M42 rate limit stores only hashes",async()=>{const db=new D1();await join(db);const serialized=JSON.stringify(db.sqlite.prepare("SELECT * FROM platform_member_rate_limits").all());assert.equal(serialized.includes("0912345678"),false);});
