import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import { calculateOrderLines, canTransitionOrderStatus, handleOrderingAdminRequest, handleOrderingRequest, validateMerchantLineAddFriendUrl } from "../src/qr-ordering.js";
import { permissionForOrderingRequest } from "../src/merchant-permissions.js";

class Statement {
  constructor(statement) { this.statement = statement; this.values = []; }
  bind(...values) { this.values = values; return this; }
  async run() { const result = this.statement.run(...this.values); return { meta: { changes: Number(result.changes || 0) } }; }
  async first() { return this.statement.get(...this.values) || null; }
  async all() { return { results: this.statement.all(...this.values) }; }
}
class D1 {
  constructor() {
    this.sqlite = new DatabaseSync(":memory:");
    this.sqlite.exec("PRAGMA foreign_keys=ON");
    for (const name of ["0001_finance_core.sql", "0011_qr_membership_ordering.sql", "0012_member_benefits_integrations.sql", "0013_growth_completion.sql", "0013_qr_ordering_commercial_v1.sql", "0015_phone_only_platform_membership.sql", "0018_merchant_line_integrations.sql", "0019_demo_payment_adapters.sql", "0020_demo_invoice_core.sql"]) {
      this.sqlite.exec(readFileSync(new URL(`../migrations/${name}`, import.meta.url), "utf8"));
    }
    this.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES('merchant_a','A','商用測試餐廳','active'),('merchant_b','B','隔離商家','active')").run();
    this.sqlite.prepare("INSERT INTO merchant_ordering_settings(merchant_id,display_name,enabled,accepting_orders) VALUES('merchant_a','商用測試餐廳',1,1),('merchant_b','隔離商家',1,1)").run();
    this.sqlite.prepare("INSERT INTO merchant_ordering_qr_codes(id,merchant_id,code,label,purpose,table_label) VALUES('qr_a','merchant_a','opaque-A1-code-0123456789','A1桌','dine_in','A1'),('qr_b','merchant_b','opaque-B1-code-0123456789','B1桌','dine_in','B1')").run();
    this.sqlite.prepare("INSERT INTO merchant_menu_categories(id,merchant_id,name,active) VALUES('cat_a','merchant_a','飲料',1),('cat_b','merchant_b','隔離菜單',1)").run();
    this.sqlite.prepare("INSERT INTO merchant_menu_items(id,merchant_id,category_id,name,price_minor,status,available) VALUES('tea','merchant_a','cat_a','紅茶',5000,'active',1),('sold','merchant_a','cat_a','售完品','4000','sold_out',1),('b_item','merchant_b','cat_b','B 商品',9000,'active',1)").run();
    this.sqlite.prepare("INSERT INTO merchant_menu_option_groups(id,merchant_id,name,selection_type,required,min_select,max_select) VALUES('sweet','merchant_a','甜度','single',1,1,1),('addon','merchant_a','加料','multiple',0,0,2)").run();
    this.sqlite.prepare("INSERT INTO merchant_menu_option_values(id,merchant_id,group_id,name,price_delta_minor) VALUES('normal','merchant_a','sweet','正常甜',0),('pearl','merchant_a','addon','珍珠',1000),('cheese','merchant_a','addon','起司',2000)").run();
    this.sqlite.prepare("INSERT INTO merchant_menu_item_option_groups(merchant_id,menu_item_id,option_group_id,sort_order) VALUES('merchant_a','tea','sweet',0),('merchant_a','tea','addon',1)").run();
  }
  prepare(sql) { return new Statement(this.sqlite.prepare(sql)); }
  async batch(statements) { this.sqlite.exec("BEGIN IMMEDIATE"); try { const results=[]; for (const statement of statements) results.push(await statement.run()); this.sqlite.exec("COMMIT"); return results; } catch (error) { this.sqlite.exec("ROLLBACK"); throw error; } }
}

const env = (db) => ({ FINANCE_DB: db });
const publicRequest = (path, method="GET", body=null, token="", key="") => new Request(`https://ordering.test${path}`, { method, headers: { ...(body ? { "content-type": "application/json" } : {}), ...(token ? { authorization: `Bearer ${token}` } : {}), ...(key ? { "idempotency-key": key } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
const adminRequest = (path, method="GET", body=null, key="") => publicRequest(`${path}${path.includes("?") ? "&" : "?"}merchant_id=merchant_a`, method, body, "", key);
const admin = async (db, path, method="GET", body=null, key="") => { const request=adminRequest(path,method,body,key); return handleOrderingAdminRequest(request,env(db),new URL(request.url),{},true,{actor_id:"admin",actor_role:"platform_admin"}); };

async function join(db, code="opaque-A1-code-0123456789", phone="0912345678", platformToken="") {
  const request=new Request(`https://ordering.test/api/ordering/qr/${code}/join`,{method:"POST",headers:{"content-type":"application/json",...(platformToken?{"x-platform-member-token":platformToken}:{})},body:JSON.stringify({phone,privacy_consent:true,consent_version:"2026-08-27",device_id:"test-device"})});
  const response=await handleOrderingRequest(request,env(db),new URL(request.url),{}); const data=await response.json(); return {response,data,token:data.session?.token,platformToken:data.platform_session?.token};
}
async function createOrder(db, token, overrides={}) {
  const body={order_type:"dine_in",table_label:"A1",items:[{item_id:"tea",quantity:1,option_value_ids:["normal","pearl"]}],...overrides};
  const request=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/orders","POST",body,token,overrides.key || "order-key-0001");
  return handleOrderingRequest(request,env(db),new URL(request.url),{});
}

test("commercial migration applies and creates option/session/auth tables",()=>{const db=new D1();for(const table of ["merchant_menu_option_groups","merchant_menu_option_values","merchant_menu_item_option_groups","merchant_food_order_item_options","merchant_dining_sessions","merchant_users","merchant_user_sessions"])assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table));});
test("QR migrations preserve the existing CRM merchant memberships table",()=>{
  const sqlite=new DatabaseSync(":memory:");
  sqlite.exec("PRAGMA foreign_keys=ON");
  sqlite.exec(readFileSync(new URL("../migrations/0001_finance_core.sql",import.meta.url),"utf8"));
  sqlite.exec(`CREATE TABLE merchant_memberships (
    id TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    member_number TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    points INTEGER NOT NULL DEFAULT 0
  );`);
  sqlite.prepare("INSERT INTO merchant_memberships(id,merchant_id,user_id,member_number,points) VALUES(?,?,?,?,?)").run("crm-member-1","merchant-a","user-1","CRM-001",25);
  for(const name of ["0011_qr_membership_ordering.sql","0012_member_benefits_integrations.sql","0013_growth_completion.sql","0013_qr_ordering_commercial_v1.sql"]){
    sqlite.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),"utf8"));
  }
  assert.equal(sqlite.prepare("SELECT points FROM merchant_memberships WHERE id='crm-member-1'").get().points,25);
  assert.ok(sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_ordering_memberships'").get());
});
test("commercial migration rollback preserves the original ordering tables",()=>{const db=new D1();db.sqlite.exec(readFileSync(new URL("../migrations/rollback/0013_qr_ordering_commercial_v1.down.sql",import.meta.url),"utf8"));assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_food_orders'").get());assert.equal(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='merchant_menu_option_groups'").get(),undefined);});
test("invalid QR is rejected",async()=>{const db=new D1();const r=publicRequest("/api/ordering/qr/nope");assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,404);});
test("merchant LINE add-friend URL accepts only official HTTPS LINE hosts",()=>{assert.equal(validateMerchantLineAddFriendUrl("https://lin.ee/demo123"),"https://lin.ee/demo123");assert.equal(validateMerchantLineAddFriendUrl("javascript:alert(1)"),null);assert.equal(validateMerchantLineAddFriendUrl("https://evil.example/redirect"),null);assert.equal(validateMerchantLineAddFriendUrl("data:text/html,x"),null);});
test("QR context has no enabled LINE CTA until the merchant config is valid",async()=>{const db=new D1();let r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");let data=await (await handleOrderingRequest(r,env(db),new URL(r.url),{})).json();assert.equal(data.context.line.configured,false);await admin(db,"/api/admin/ordering/line-integration","PUT",{enabled:true,display_name:"測試 LINE",basic_id:"@test",add_friend_url:"https://lin.ee/demo123",integration_mode:"add_friend_link"});r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");data=await (await handleOrderingRequest(r,env(db),new URL(r.url),{})).json();assert.equal(data.context.line.configured,true);assert.equal(data.context.line.capabilities.friendshipStatus,false);});
test("LINE analytics resolve merchant only from opaque QR context",async()=>{const db=new D1();await admin(db,"/api/admin/ordering/line-integration","PUT",{enabled:true,add_friend_url:"https://lin.ee/demo123",integration_mode:"add_friend_link"});const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/line-events","POST",{event_type:"click",source:"menu_banner",merchant_id:"merchant_b"});assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,201);const event=db.sqlite.prepare("SELECT merchant_id,event_type,qr_context FROM merchant_line_events").get();assert.deepEqual({...event},{merchant_id:"merchant_a",event_type:"line_cta_click",qr_context:"dine_in:A1"});});
test("disabled QR is rejected",async()=>{const db=new D1();db.sqlite.prepare("UPDATE merchant_ordering_qr_codes SET active=0 WHERE id='qr_a'").run();const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,404);});
test("expired QR is rejected",async()=>{const db=new D1();db.sqlite.prepare("UPDATE merchant_ordering_qr_codes SET expires_at='2000-01-01' WHERE id='qr_a'").run();const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,404);});
test("new member joins without verified phone",async()=>{const db=new D1();const {response,data}=await join(db);assert.equal(response.status,201);assert.equal(db.sqlite.prepare("SELECT phone_verified FROM ordering_customers").get().phone_verified,0);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_members").get().n,1);assert.equal(data.welcome.show,true);});
test("returning member reuses merchant membership",async()=>{const db=new D1();const first=await join(db);const second=await join(db,"opaque-A1-code-0123456789","0912345678",first.platformToken);assert.equal(second.response.status,201);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_ordering_memberships").get().n,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_members").get().n,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM platform_member_coupons").get().n,1);});
test("blocked membership cannot obtain menu",async()=>{const db=new D1();const {token}=await join(db);db.sqlite.prepare("UPDATE merchant_ordering_memberships SET status='blocked'").run();const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/menu","GET",null,token);assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,401);});
test("QR visitor can browse the merchant menu before joining",async()=>{const db=new D1();const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/menu");const response=await handleOrderingRequest(r,env(db),new URL(r.url),{});assert.equal(response.status,200);const data=await response.json();assert.equal(data.member,null);assert.ok(data.items.length>0);});
test("member session stores only SHA-256 token",async()=>{const db=new D1();const {token}=await join(db);const stored=db.sqlite.prepare("SELECT token_hash FROM merchant_member_sessions").get().token_hash;assert.notEqual(stored,token);assert.ok(stored.length>30);});
test("menu exposes active options with the public item/group contract",async()=>{const db=new D1();const {token}=await join(db);const r=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/menu","GET",null,token);const data=await (await handleOrderingRequest(r,env(db),new URL(r.url),{})).json();assert.equal(data.option_groups.length,2);assert.ok(data.option_groups.every((group)=>group.active));assert.ok(data.option_values.every((value)=>value.active));assert.deepEqual(data.item_option_groups[0],{item_id:"tea",group_id:"sweet",sort_order:0});assert.ok(data.items.some((item)=>item.status==="sold_out"));});
test("required option omission is rejected",()=>{const result=calculateOrderLines([{item_id:"tea",quantity:1}], [{id:"tea",name:"紅茶",price_minor:5000,allow_customer_note:1}], [{id:"sweet",name:"甜度",active:1,min_select:1,max_select:1}], [{id:"normal",group_id:"sweet",name:"正常",price_delta_minor:0,active:1}], [{menu_item_id:"tea",option_group_id:"sweet"}]);assert.equal(result.ok,false);});
test("option max selection is enforced",()=>{const result=calculateOrderLines([{item_id:"tea",quantity:1,option_value_ids:["normal","half"]}], [{id:"tea",name:"紅茶",price_minor:5000,allow_customer_note:1}], [{id:"sweet",name:"甜度",active:1,min_select:1,max_select:1}], [{id:"normal",group_id:"sweet",name:"正常",price_delta_minor:0,active:1},{id:"half",group_id:"sweet",name:"半糖",price_delta_minor:0,active:1}], [{menu_item_id:"tea",option_group_id:"sweet"}]);assert.equal(result.ok,false);});
test("worker recalculates base and option prices",()=>{const result=calculateOrderLines([{item_id:"tea",quantity:2,price_minor:1,option_value_ids:["normal","pearl"]}], [{id:"tea",name:"紅茶",price_minor:5000,allow_customer_note:1}], [{id:"sweet",name:"甜度",active:1,min_select:1,max_select:1},{id:"addon",name:"加料",active:1,min_select:0,max_select:2}], [{id:"normal",group_id:"sweet",name:"正常",price_delta_minor:0,active:1},{id:"pearl",group_id:"addon",name:"珍珠",price_delta_minor:1000,active:1}], [{menu_item_id:"tea",option_group_id:"sweet"},{menu_item_id:"tea",option_group_id:"addon"}]);assert.equal(result.subtotal_minor,12000);assert.equal(result.lines[0].unit_total_minor,6000);});
test("sold-out item is rejected again at submission",async()=>{const db=new D1();const {token}=await join(db);const response=await createOrder(db,token,{items:[{item_id:"sold",quantity:1}]});assert.equal(response.status,409);});
test("paused store remains browseable but rejects order",async()=>{const db=new D1();const {token}=await join(db);db.sqlite.prepare("UPDATE merchant_ordering_settings SET accepting_orders=0 WHERE merchant_id='merchant_a'").run();const contextRequest=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");assert.equal((await handleOrderingRequest(contextRequest,env(db),new URL(contextRequest.url),{})).status,200);const response=await createOrder(db,token);assert.equal(response.status,409);assert.match((await response.json()).error,/暫停接單/);});
test("order creation saves option snapshot and dining session",async()=>{const db=new D1();const {token}=await join(db);const response=await createOrder(db,token);assert.equal(response.status,201);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_food_order_item_options").get().n,2);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_dining_sessions WHERE status='open'").get().n,1);});
test("same idempotency key replays first order",async()=>{const db=new D1();const {token}=await join(db);assert.equal((await createOrder(db,token)).status,201);const replay=await createOrder(db,token);assert.equal(replay.status,200);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_food_orders").get().n,1);});
test("re-order creates second order in same table session",async()=>{const db=new D1();const {token}=await join(db);await createOrder(db,token);await createOrder(db,token,{key:"order-key-0002"});assert.equal(db.sqlite.prepare("SELECT COUNT(DISTINCT dining_session_id) sessions,COUNT(*) orders FROM merchant_food_orders").get().sessions,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_food_orders").get().n,2);});
test("closing table causes next party to get a new session",async()=>{const db=new D1();const one=await join(db,"opaque-A1-code-0123456789","0912345678");await createOrder(db,one.token);const session=db.sqlite.prepare("SELECT id FROM merchant_dining_sessions WHERE status='open'").get().id;assert.equal((await admin(db,`/api/admin/ordering/dining-sessions/${session}/close`,"POST")).status,200);const two=await join(db,"opaque-A1-code-0123456789","0922333444");await createOrder(db,two.token,{key:"order-key-party2"});assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_dining_sessions").get().n,2);});
test("customer can see only own order",async()=>{const db=new D1();const a=await join(db);const created=await (await createOrder(db,a.token)).json();const b=await join(db,"opaque-A1-code-0123456789","0922333444");const r=publicRequest(`/api/ordering/orders/${created.order.order_code}`,"GET",null,b.token);assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,404);});
test("submitted customer cancellation requires setting and reason",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();let r=publicRequest(`/api/ordering/orders/${created.order.order_code}/cancel`,"POST",{reason:""},token);assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,400);r=publicRequest(`/api/ordering/orders/${created.order.order_code}/cancel`,"POST",{reason:"顧客臨時取消"},token);assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,200);});
test("accepted order cannot be cancelled by customer",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();await admin(db,`/api/admin/ordering/orders/${created.order.order_code}/status`,"PATCH",{status:"accepted"});const r=publicRequest(`/api/ordering/orders/${created.order.order_code}/cancel`,"POST",{reason:"取消"},token);assert.equal((await handleOrderingRequest(r,env(db),new URL(r.url),{})).status,409);});
test("state machine requires every production step",()=>{for(const [from,to] of [["submitted","accepted"],["accepted","preparing"],["preparing","ready"],["ready","served"],["served","completed"]])assert.equal(canTransitionOrderStatus(from,to),true);assert.equal(canTransitionOrderStatus("submitted","completed"),false);assert.equal(canTransitionOrderStatus("ready","completed"),false);});
test("cancellation requires a reason in admin flow",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();assert.equal((await admin(db,`/api/admin/ordering/orders/${created.order.order_code}/status`,"PATCH",{status:"cancelled"})).status,400);});
test("payment is changed only by dedicated idempotent endpoint",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();const code=created.order.order_code;await admin(db,`/api/admin/ordering/orders/${code}/status`,"PATCH",{status:"accepted",payment_status:"paid"});assert.equal(db.sqlite.prepare("SELECT payment_status FROM merchant_food_orders").get().payment_status,"unpaid");const first=await admin(db,`/api/admin/ordering/orders/${code}/payment`,"POST",{action:"confirm",payment_method:"cash"},"pay-once");assert.equal(first.status,200);const replay=await admin(db,`/api/admin/ordering/orders/${code}/payment`,"POST",{action:"confirm",payment_method:"cash"},"pay-once");assert.equal((await replay.json()).replayed,true);});
test("QR regeneration immediately invalidates old code",async()=>{const db=new D1();const response=await admin(db,"/api/admin/ordering/qrs/qr_a/regenerate","POST");assert.equal(response.status,200);const old=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789");assert.equal((await handleOrderingRequest(old,env(db),new URL(old.url),{})).status,404);});
test("batch QR creates opaque distinct table codes",async()=>{const db=new D1();const response=await admin(db,"/api/admin/ordering/qrs/batch","POST",{prefix:"A",start:2,end:10,suffix:""});assert.equal(response.status,201);const rows=db.sqlite.prepare("SELECT code,table_label FROM merchant_ordering_qr_codes WHERE merchant_id='merchant_a'").all();assert.equal(new Set(rows.map((row)=>row.code)).size,rows.length);assert.ok(rows.every((row)=>!row.code.includes("merchant_a")));});
test("option snapshots are immutable",async()=>{const db=new D1();const {token}=await join(db);await createOrder(db,token);assert.throws(()=>db.sqlite.prepare("UPDATE merchant_food_order_item_options SET price_delta_minor=1").run(),/IMMUTABLE/);assert.throws(()=>db.sqlite.prepare("DELETE FROM merchant_food_order_item_options").run(),/IMMUTABLE/);});
test("merchant permission map separates payment permission",()=>{assert.equal(permissionForOrderingRequest("/api/merchant-admin/ordering/orders/BY-1/payment","POST"),"ordering.payments.manage");assert.equal(permissionForOrderingRequest("/api/merchant-admin/ordering/items/tea","PATCH"),"ordering.menu.manage");assert.equal(permissionForOrderingRequest("/api/merchant-admin/ordering/overview","GET"),"ordering.read");});
test("merchant B cannot reference merchant A option",()=>{const db=new D1();assert.throws(()=>db.sqlite.prepare("INSERT INTO merchant_menu_item_option_groups(merchant_id,menu_item_id,option_group_id) VALUES('merchant_b','b_item','sweet')").run(),/FOREIGN KEY/);});
test("order audit records status actor and cancellation",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();await admin(db,`/api/admin/ordering/orders/${created.order.order_code}/status`,"PATCH",{status:"cancelled",cancel_reason:"現場取消"});const row=db.sqlite.prepare("SELECT action,metadata FROM merchant_ordering_audit_logs WHERE action='order_status_updated'").get();assert.equal(row.action,"order_status_updated");assert.match(row.metadata,/現場取消/);});
test("category CRUD updates name, order and active status",async()=>{const db=new D1();let response=await admin(db,"/api/admin/ordering/categories","POST",{name:"主餐",sort_order:9});assert.equal(response.status,201);const id=(await response.json()).id;response=await admin(db,`/api/admin/ordering/categories/${id}`,"PATCH",{name:"熱門主餐",sort_order:1,active:false});assert.equal(response.status,200);assert.deepEqual(Object.values(db.sqlite.prepare("SELECT name,sort_order,active FROM merchant_menu_categories WHERE id=?").get(id)),["熱門主餐",1,0]);});
test("category archive is soft and preserves historical row",async()=>{const db=new D1();assert.equal((await admin(db,"/api/admin/ordering/categories/cat_a","PATCH",{archived:true})).status,200);const row=db.sqlite.prepare("SELECT active,archived_at FROM merchant_menu_categories WHERE id='cat_a'").get();assert.equal(row.active,0);assert.ok(row.archived_at);});
test("item CRUD supports status, note and daily limit",async()=>{const db=new D1();let response=await admin(db,"/api/admin/ordering/items","POST",{category_id:"cat_a",name:"奶茶",price_minor:6500,daily_limit:8,allow_customer_note:false});assert.equal(response.status,201);const id=(await response.json()).id;response=await admin(db,`/api/admin/ordering/items/${id}`,"PATCH",{status:"hidden",price_minor:7000});assert.equal(response.status,200);const row=db.sqlite.prepare("SELECT status,price_minor,daily_limit,allow_customer_note FROM merchant_menu_items WHERE id=?").get(id);assert.deepEqual([row.status,row.price_minor,row.daily_limit,row.allow_customer_note],["hidden",7000,8,0]);});
test("duplicated item is hidden and preserves option links",async()=>{const db=new D1();const response=await admin(db,"/api/admin/ordering/items/tea/duplicate","POST");const id=(await response.json()).id;assert.equal(db.sqlite.prepare("SELECT status FROM merchant_menu_items WHERE id=?").get(id).status,"hidden");assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_menu_item_option_groups WHERE menu_item_id=?").get(id).n,2);});
test("daily limit trigger rejects concurrent excess quantity",async()=>{const db=new D1();db.sqlite.prepare("UPDATE merchant_menu_items SET daily_limit=1 WHERE id='tea'").run();const {token}=await join(db);assert.equal((await createOrder(db,token)).status,201);const second=await createOrder(db,token,{key:"daily-limit-2"});assert.equal(second.status,409);assert.match((await second.json()).error,/限量/);});
test("fixed dine-in QR ignores a forged table label",async()=>{const db=new D1();const {token}=await join(db);const result=await (await createOrder(db,token,{table_label:"B99"})).json();assert.equal(result.order.table_label,"A1");});
test("customer cancellation can be disabled per merchant",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();db.sqlite.prepare("UPDATE merchant_ordering_settings SET customer_cancel_before_accept=0 WHERE merchant_id='merchant_a'").run();const request=publicRequest(`/api/ordering/orders/${created.order.order_code}/cancel`,"POST",{reason:"取消"},token);assert.equal((await handleOrderingRequest(request,env(db),new URL(request.url),{})).status,409);});
test("all operational states are persisted sequentially",async()=>{const db=new D1();const {token}=await join(db);const created=await (await createOrder(db,token)).json();for(const status of ["accepted","preparing","ready","served","completed"]){const response=await admin(db,`/api/admin/ordering/orders/${created.order.order_code}/status`,"PATCH",{status});assert.equal(response.status,200);}assert.equal(db.sqlite.prepare("SELECT status FROM merchant_food_orders").get().status,"completed");});
test("payment refund is idempotent and audited",async()=>{const db=new D1();const {token}=await join(db);const code=(await (await createOrder(db,token)).json()).order.order_code;await admin(db,`/api/admin/ordering/orders/${code}/payment`,"POST",{action:"confirm",payment_method:"card",reference:"POS-1"},"paid-key");const refund=await admin(db,`/api/admin/ordering/orders/${code}/payment`,"POST",{action:"refund",payment_method:"card",reference:"REF-1"},"refund-key");assert.equal(refund.status,200);assert.equal(db.sqlite.prepare("SELECT payment_status FROM merchant_food_orders").get().payment_status,"refunded");assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_order_payment_events").get().n,2);});
test("option group and option value are created through API",async()=>{const db=new D1();let response=await admin(db,"/api/admin/ordering/option-groups","POST",{name:"辣度",selection_type:"single",required:true,min_select:1,max_select:1});const group=(await response.json()).id;response=await admin(db,`/api/admin/ordering/option-groups/${group}/values`,"POST",{name:"小辣",price_delta_minor:0});assert.equal(response.status,201);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_menu_option_values WHERE group_id=?").get(group).n,1);});
test("cross-merchant option link is rejected by API",async()=>{const db=new D1();const response=await admin(db,"/api/admin/ordering/items/tea/option-groups","PUT",{group_ids:["unknown-b-group"]});assert.equal(response.status,400);});
test("batch QR rejects more than one hundred tables",async()=>{const db=new D1();assert.equal((await admin(db,"/api/admin/ordering/qrs/batch","POST",{prefix:"A",start:1,end:101})).status,400);});
test("join endpoint rate limits repeated public requests",async()=>{const db=new D1();let status=0;for(let index=0;index<13;index++){const result=await join(db,"opaque-A1-code-0123456789",`09${String(10000000+index).slice(-8)}`);status=result.response.status;}assert.equal(status,429);});
test("show_sold_out_items disabled hides sold-out menu entries",async()=>{const db=new D1();db.sqlite.prepare("UPDATE merchant_ordering_settings SET show_sold_out_items=0 WHERE merchant_id='merchant_a'").run();const {token}=await join(db);const request=publicRequest("/api/ordering/qr/opaque-A1-code-0123456789/menu","GET",null,token);const data=await (await handleOrderingRequest(request,env(db),new URL(request.url),{})).json();assert.ok(!data.items.some((item)=>item.id==="sold"));});
test("auto accept creates accepted order with timestamp",async()=>{const db=new D1();db.sqlite.prepare("UPDATE merchant_ordering_settings SET auto_accept_orders=1 WHERE merchant_id='merchant_a'").run();const {token}=await join(db);const response=await createOrder(db,token);assert.equal(response.status,201);const row=db.sqlite.prepare("SELECT status,accepted_at FROM merchant_food_orders").get();assert.equal(row.status,"accepted");assert.ok(row.accepted_at);});
test("mobile barcode invoice preference is masked and requested only after payment confirmation",async()=>{const db=new D1(),j=await join(db),o=await createOrder(db,j.token,{invoice:{type:"mobile_barcode",carrier_value:"/ABC1234"},key:"invoice-order-key-1"});const order=(await o.json()).order;const orderId=db.sqlite.prepare("SELECT id FROM merchant_food_orders WHERE order_code=?").get(order.order_code).id;const pref=db.sqlite.prepare("SELECT carrier_value_encrypted,carrier_value_masked FROM merchant_order_invoice_preferences WHERE order_id=?").get(orderId);assert.equal(pref.carrier_value_encrypted,null);assert.notEqual(pref.carrier_value_masked,"/ABC1234");assert.equal(db.sqlite.prepare("SELECT COUNT(*) count FROM invoice_requests").get().count,0);const paid=await admin(db,`/api/admin/ordering/orders/${order.order_code}/payment`,"POST",{action:"confirmed",payment_method:"cash"},"invoice-payment-key-1");assert.equal(paid.status,200);const request=db.sqlite.prepare("SELECT status,carrier_value_masked FROM invoice_requests").get();assert.equal(request.status,"PENDING");assert.notEqual(request.carrier_value_masked,"/ABC1234");});
