import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import worker from "../src/index.js";
import { deriveAdminPassword } from "../src/admin-auth.js";
import { calculateSettlement, roundByBasisPoints } from "../src/settlement-engine.js";
import { handleSettlementRequest } from "../src/settlements.js";

class Statement { constructor(statement,sql){this.statement=statement;this.sql=sql;this.values=[]} bind(...values){this.values=values;return this} async run(){const r=this.statement.run(...this.values);return{meta:{changes:Number(r.changes||0)}}} async first(){return this.statement.get(...this.values)||null} async all(){return{results:this.statement.all(...this.values)}} }
class D1 { constructor(){this.sqlite=new DatabaseSync(":memory:");this.sqlite.exec("PRAGMA foreign_keys=ON");for(const file of ["0001_finance_core.sql","0002_partner_portal.sql","0009_production_admin_auth.sql","0010_merchant_settlements.sql"])this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8"));this.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES ('merchant_b','B','商家 B','active')").run()} prepare(sql){return new Statement(this.sqlite.prepare(sql),sql)} async batch(statements){this.sqlite.exec("BEGIN IMMEDIATE");try{const out=[];for(const s of statements)out.push(await s.run());this.sqlite.exec("COMMIT");return out}catch(e){this.sqlite.exec("ROLLBACK");throw e}} }
const baseProfile={enabled:true,payment_plan:"upfront_18000",deposit_rate_bp:3000,platform_fee_rate_bp:200,processing_fee_mode:"actual_or_estimated",processing_fee_basis:"deposit_collected",estimated_processing_fee_rate_bp:275,tax_reserve_mode:"disabled",tax_reserve_rate_bp:0,withholding_mode:"disabled",withholding_rate_bp:0,offset_target_amount_minor:1_800_000,continue_platform_fee_after_offset:false,settlement_day:10,legal_review_status:"approved",accounting_review_status:"pending",effective_from:"2026-08-01"};
const calculate=(overrides={})=>calculateSettlement({profile:{...baseProfile,...overrides.profile},total_order_amount_minor:overrides.total_order_amount_minor??1_000_000,actual_processing_fee_minor:overrides.actual_processing_fee_minor,prior_offset_amount_minor:overrides.prior_offset_amount_minor??0,adjustments_minor:overrides.adjustments_minor??0});
function seedProfile(db,merchantId="merchant_meiling_001",plan="upfront_18000"){db.sqlite.prepare("INSERT INTO merchant_settlement_profiles(id,merchant_id,enabled,payment_plan,legal_review_status,effective_from) VALUES (?,?,?,?,?,?)").run(`profile-${merchantId}`,merchantId,1,plan,"approved","2026-08-01")}
function seedStatement(db,{id="statement-1",merchant="merchant_meiling_001",status="draft",start="2026-08-01",end="2026-08-31",payable=10000}={}){db.sqlite.prepare(`INSERT INTO merchant_settlements(id,statement_no,merchant_id,profile_id,period_start,period_end,status,merchant_payable_minor,calculation_version,rules_snapshot_json,locked_at,voided_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,`NO-${id}`,merchant,`profile-${merchant}`,start,end,status,payable,"settlement-v1","{}",["locked","paid","void"].includes(status)?"2026-09-01T00:00:00Z":null,status==="void"?"2026-09-01T00:00:00Z":null)}

test("1. 30% 訂金使用整數分與 basis points",()=>assert.equal(calculate().deposit_collected_minor,300_000));
test("2. 預估金流費預設以代收訂金為基礎",()=>assert.equal(calculate().processing_fee_minor,8_250));
test("3. Provider actual fee 覆蓋 estimated fee",()=>{const r=calculate({actual_processing_fee_minor:7_777});assert.equal(r.processing_fee_minor,7_777);assert.equal(r.processing_fee_source,"actual")});
test("4. tax_reserve 預設為 0",()=>assert.equal(calculate().tax_reserve_minor,0));
test("5. withholding 預設為 0",()=>assert.equal(calculate().withholding_minor,0));
test("6. upfront_18000 不產生銷售抵付",()=>{const r=calculate({prior_offset_amount_minor:900_000});assert.equal(r.current_offset_amount_minor,0);assert.equal(r.cumulative_offset_amount_minor,0);assert.equal(r.remaining_offset_amount_minor,0)});
test("7. sales_offset_18000 正確逐期累計",()=>{const r=calculate({profile:{payment_plan:"sales_offset_18000"},prior_offset_amount_minor:100_000});assert.equal(r.current_offset_amount_minor,20_000);assert.equal(r.cumulative_offset_amount_minor,120_000);assert.equal(r.remaining_offset_amount_minor,1_680_000)});
test("8. 17,500 + 2,000 僅抵 500 並將 1,500 列 ongoing",()=>{const r=calculate({profile:{payment_plan:"sales_offset_18000",continue_platform_fee_after_offset:true},total_order_amount_minor:10_000_000,prior_offset_amount_minor:1_750_000});assert.equal(r.current_offset_amount_minor,50_000);assert.equal(r.cumulative_offset_amount_minor,1_800_000);assert.equal(r.remaining_offset_amount_minor,0);assert.equal(r.ongoing_platform_fee_minor,150_000)});
test("9. locked 後資料庫 trigger 禁止修改金額",()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});assert.throws(()=>db.sqlite.prepare("UPDATE merchant_settlements SET merchant_payable_minor=1 WHERE id='statement-1'").run(),/immutable/)});
test("10. locked 後退款只能建立下一期 pending adjustment",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});const req=new Request("https://worker.test/api/finance/settlements/statement-1/adjustments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adjustment_type:"refund",amount_minor:-5000,reason:"鎖定後退款",idempotency_key:"refund-1"})});const res=await handleSettlementRequest(req,{FINANCE_DB:db},new URL(req.url),{}, {admin_user_id:"admin"});assert.equal(res.status,201);const row=db.sqlite.prepare("SELECT amount_minor,status,applied_settlement_id FROM merchant_settlement_adjustments").get();assert.equal(row.amount_minor,-5000);assert.equal(row.status,"pending");assert.equal(row.applied_settlement_id,null)});
test("11. webhook retry 的相同來源不可重複入帳",()=>{const db=new D1();seedProfile(db);seedStatement(db);const sql="INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?)";db.sqlite.prepare(sql).run("i1","statement-1","merchant_meiling_001","payment","provider_event","evt-1",100,"2026-08-01","{}");assert.throws(()=>db.sqlite.prepare(sql).run("i2","statement-1","merchant_meiling_001","payment","provider_event","evt-1",100,"2026-08-01","{}"),/UNIQUE/)});
test("12. 同一 payment 不得出現在兩張對帳單",()=>{const db=new D1();seedProfile(db);seedStatement(db);seedStatement(db,{id:"statement-2",start:"2026-09-01",end:"2026-09-30"});const sql="INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?)";db.sqlite.prepare(sql).run("i1","statement-1","merchant_meiling_001","payment","payment","pay-1",100,"2026-08-01","{}");assert.throws(()=>db.sqlite.prepare(sql).run("i2","statement-2","merchant_meiling_001","payment","payment","pay-1",100,"2026-09-01","{}"),/UNIQUE/)});
test("13. merchant isolation 的複合外鍵拒絕跨商家 item",()=>{const db=new D1();seedProfile(db);seedStatement(db);assert.throws(()=>db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES ('bad','statement-1','merchant_b','payment','payment','x',1,'2026-08-01','{}')").run(),/FOREIGN KEY/)});

async function authEnv(){const db=new D1(),salt="admin-salt",hash=await deriveAdminPassword("A-secure-admin-password-2026",salt);db.sqlite.prepare("INSERT INTO admin_users(id,email,display_name,password_hash,password_salt,role) VALUES ('admin','owner@example.com','管理員',?,?,'super_admin')").run(hash,salt);return{db,env:{FINANCE_DB:db,ALLOWED_ORIGINS:"https://baiyeconnect.com",CONTRACTS_BUCKET:{async get(){return null},async put(){}}}}}
async function login(env){const req=new Request("https://worker.test/api/admin/auth/login",{method:"POST",headers:{origin:"https://baiyeconnect.com","content-type":"application/json"},body:JSON.stringify({email:"owner@example.com",password:"A-secure-admin-password-2026"})}),res=await worker.fetch(req,env,{}),body=await res.json();return{cookie:res.headers.get("set-cookie").split(";")[0],csrf:body.csrf_token}}
test("14. 未登入 Admin 讀 settlement API 回傳 401",async()=>{const {env}=await authEnv();const res=await worker.fetch(new Request("https://worker.test/api/finance/settlements",{headers:{origin:"https://baiyeconnect.com"}}),env,{});assert.equal(res.status,401)});
test("15. 已登入但缺 CSRF 的 mutation 被拒絕",async()=>{const {env}=await authEnv(),session=await login(env);const res=await worker.fetch(new Request("https://worker.test/api/finance/settlements/preview",{method:"POST",headers:{origin:"https://baiyeconnect.com",cookie:session.cookie,"content-type":"application/json"},body:"{}"}),env,{});assert.equal(res.status,401)});
test("16. 非正式 Origin 被拒絕",async()=>{const {env}=await authEnv();const res=await worker.fetch(new Request("https://worker.test/api/finance/settlements",{headers:{origin:"https://evil.example"}}),env,{});assert.equal(res.status,403)});
test("17. PDF 未授權不得下載",async()=>{const {env}=await authEnv();const res=await worker.fetch(new Request("https://worker.test/api/finance/settlements/secret/pdf",{headers:{origin:"https://baiyeconnect.com"}}),env,{});assert.equal(res.status,401)});
test("18. 四捨五入 half-up 且負數金額被拒絕",()=>{assert.equal(roundByBasisPoints(1,5000),1);assert.throws(()=>roundByBasisPoints(-1,200),/Invalid/);assert.throws(()=>calculate({adjustments_minor:-999_999}),/negative/)});
test("19. void 對帳單不得標記 paid",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"void"});const req=new Request("https://worker.test/api/finance/settlements/statement-1/mark-paid",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transfer_amount_minor:10000,transfer_date:"2026-09-01",transfer_reference:"x"})});assert.equal((await handleSettlementRequest(req,{FINANCE_DB:db},new URL(req.url),{},{admin_user_id:"admin"})).status,409)});
test("20. mark-paid 金額不一致必須先建立正式差額",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked",payable:10000});const req=new Request("https://worker.test/api/finance/settlements/statement-1/mark-paid",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transfer_amount_minor:9999,transfer_date:"2026-09-01",transfer_reference:"x"})});assert.equal((await handleSettlementRequest(req,{FINANCE_DB:db},new URL(req.url),{},{admin_user_id:"admin"})).status,400)});
test("21. 高風險規則未經法務／會計核准不得啟用",async()=>{const db=new D1();const input={...baseProfile,enabled:true,legal_review_status:"pending",tax_reserve_mode:"percentage",tax_reserve_rate_bp:500,accounting_review_status:"pending"};const req=new Request("https://worker.test/api/finance/settlement-profiles/merchant_meiling_001",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const res=await handleSettlementRequest(req,{FINANCE_DB:db},new URL(req.url),{},{admin_user_id:"admin"});assert.equal(res.status,400);assert.equal(db.sqlite.prepare("SELECT COUNT(*) count FROM merchant_settlement_profiles").get().count,0)});
test("22. 草稿鎖定會重新計算並把 PDF 私存 settlements 前綴",async()=>{const db=new D1();seedProfile(db);db.sqlite.prepare("INSERT INTO platform_finance_settings(id,brand_name,legal_entity_name,tax_id) VALUES ('default','創百業智慧鏈','測試法律主體','00000000')").run();db.sqlite.prepare("INSERT INTO orders(id,order_no,merchant_id,title,amount_due,payment_status) VALUES ('ord','ORD','merchant_meiling_001','訂單',10000,'paid')").run();db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,order_id,gross_amount,fee_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES ('pay','PAY','merchant_meiling_001','ord',3000,90,2910,3000,'card','paid','2026-08-15','manual')").run();const createReq=new Request("https://worker.test/api/finance/settlements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({merchant_id:"merchant_meiling_001",period_start:"2026-08-01",period_end:"2026-08-31"})});const created=await handleSettlementRequest(createReq,{FINANCE_DB:db},new URL(createReq.url),{},{admin_user_id:"admin"});assert.equal(created.status,201);const createdBody=await created.json();let storedKey="";const env={FINANCE_DB:db,CONTRACTS_BUCKET:{async put(key){storedKey=key}}};const lockReq=new Request(`https://worker.test/api/finance/settlements/${createdBody.id}/lock`,{method:"POST"});const locked=await handleSettlementRequest(lockReq,env,new URL(lockReq.url),{},{admin_user_id:"admin"});assert.equal(locked.status,200);assert.match(storedKey,/^settlements\/merchant_meiling_001\//);assert.equal(db.sqlite.prepare("SELECT status FROM merchant_settlements WHERE id=?").get(createdBody.id).status,"locked")});
