import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import worker from "../src/index.js";
import { deriveAdminPassword } from "../src/admin-auth.js";
import { calculateProcessingFees, calculateRefundReversal, calculateSettlement, roundByBasisPoints } from "../src/settlement-engine.js";
import { createSettlementRefundAdjustment, handleSettlementRequest } from "../src/settlements.js";
import { formatTaipeiDate, taipeiDateToUtcEndExclusive, taipeiDateToUtcStart } from "../src/taipei-date.js";

class Statement {
  constructor(statement) { this.statement = statement; this.values = []; }
  bind(...values) { this.values = values; return this; }
  async run() { const result = this.statement.run(...this.values); return { meta: { changes: Number(result.changes || 0) } }; }
  async first() { return this.statement.get(...this.values) || null; }
  async all() { return { results: this.statement.all(...this.values) }; }
}
class D1 {
  constructor() {
    this.sqlite = new DatabaseSync(":memory:");
    this.sqlite.exec("PRAGMA foreign_keys=ON");
    for (const file of ["0001_finance_core.sql", "0002_partner_portal.sql", "0009_production_admin_auth.sql", "0010_merchant_settlements.sql"]) this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`, import.meta.url), "utf8"));
    this.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES ('merchant_b','B','商家 B','active')").run();
  }
  prepare(sql) { return new Statement(this.sqlite.prepare(sql)); }
  async batch(statements) { this.sqlite.exec("BEGIN IMMEDIATE"); try { const results = []; for (const statement of statements) results.push(await statement.run()); this.sqlite.exec("COMMIT"); return results; } catch (error) { this.sqlite.exec("ROLLBACK"); throw error; } }
}

const merchantId = "merchant_meiling_001";
const baseProfile = { enabled: true, payment_plan: "upfront_18000", deposit_rate_bp: 3000, platform_fee_rate_bp: 200, processing_fee_mode: "actual_or_estimated", processing_fee_basis: "deposit_collected", estimated_processing_fee_rate_bp: 275, tax_reserve_mode: "disabled", tax_reserve_rate_bp: 0, withholding_mode: "disabled", withholding_rate_bp: 0, refund_platform_fee_policy: "pro_rata_reverse", refund_offset_policy: "pro_rata_reverse", provider_fee_refund_policy: "no_reverse", offset_target_amount_minor: 1_800_000, continue_platform_fee_after_offset: false, settlement_day: 10, legal_review_status: "approved", accounting_review_status: "pending", effective_from: "2026-08-01" };
const calculate = (overrides = {}) => calculateSettlement({ profile: { ...baseProfile, ...overrides.profile }, total_order_amount_minor: overrides.total_order_amount_minor ?? 1_000_000, actual_processing_fee_minor: overrides.actual_processing_fee_minor, actual_deposit_collected_minor: overrides.actual_deposit_collected_minor, prior_offset_amount_minor: overrides.prior_offset_amount_minor ?? 0, adjustments_minor: overrides.adjustments_minor ?? 0, sources: overrides.sources });
function seedProfile(db, id = merchantId, plan = "upfront_18000", overrides = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlement_profiles(id,merchant_id,enabled,payment_plan,deposit_rate_bp,platform_fee_rate_bp,processing_fee_mode,processing_fee_basis,estimated_processing_fee_rate_bp,legal_review_status,effective_from,refund_platform_fee_policy,refund_offset_policy,provider_fee_refund_policy) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`profile-${id}`, id, 1, plan, 3000, 200, overrides.processing_fee_mode || "actual_or_estimated", "deposit_collected", 275, "approved", "2026-08-01", overrides.refund_platform_fee_policy || "pro_rata_reverse", overrides.refund_offset_policy || "pro_rata_reverse", overrides.provider_fee_refund_policy || "no_reverse"); }
function seedStatement(db, { id = "statement-1", merchant = merchantId, status = "draft", start = "2026-08-01", end = "2026-08-31", payable = 10000, variance = 0, actual = 0, platformFee = 0, offset = 0, processingFee = 0 } = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlements(id,statement_no,merchant_id,profile_id,period_start,period_end,period_start_utc,period_end_exclusive_utc,status,merchant_payable_minor,deposit_variance_minor,actual_deposit_collected_minor,platform_service_fee_minor,current_offset_amount_minor,processing_fee_minor,calculation_version,rules_snapshot_json,locked_at,paid_at,transfer_amount_minor,transfer_reference,voided_at,void_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id, `NO-${id}`, merchant, `profile-${merchant}`, start, end, taipeiDateToUtcStart(start), taipeiDateToUtcEndExclusive(end), status, payable, variance, actual, platformFee, offset, processingFee, "settlement-v2", "{}", ["locked", "paid"].includes(status) ? "2026-09-01T00:00:00Z" : null, status === "paid" ? "2026-09-01T01:00:00Z" : null, status === "paid" ? payable : null, status === "paid" ? "TX" : null, status === "void" ? "2026-09-01T00:00:00Z" : null, status === "void" ? "void test" : null); }
function seedPayment(db, { suffix = "1", merchant = merchantId, source = "webhook", status = "paid", gross = 3000, fee = 30, paidAt = "2026-08-31T15:59:59.000Z" } = {}) { const orderId = `order-${suffix}`, paymentId = `payment-${suffix}`; db.sqlite.prepare("INSERT INTO orders(id,order_no,merchant_id,title,amount_due,payment_status) VALUES (?,?,?,?,?,?)").run(orderId, `ORD-${suffix}`, merchant, "訂單", 10000, "paid"); db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,order_id,gross_amount,fee_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").run(paymentId, `PAY-${suffix}`, merchant, orderId, gross, fee, gross - (fee || 0), gross, "card", status, paidAt, source); return { orderId, paymentId }; }
function qualify(db, payment, { role = "platform_deposit", eligible = 1, orderTotal = 1_000_000, expected = 300_000, actual = 300_000, fee = 3000, occurredAt = "2026-08-31T15:59:59.000Z", reserved = null } = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlement_sources(id,merchant_id,payment_id,order_id,collection_role,settlement_eligible,order_total_amount_minor,expected_deposit_amount_minor,actual_collected_amount_minor,provider_fee_actual_minor,occurred_at,reviewed_by,reviewed_at,reserved_statement_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`source-${payment.paymentId}`, merchantId, payment.paymentId, payment.orderId, role, eligible, orderTotal, expected, actual, fee, occurredAt, eligible ? "admin" : null, eligible ? "2026-08-01T00:00:00Z" : null, reserved); }
const req = (path, method = "GET", body = {}, key = null) => new Request(`https://worker.test/api/finance${path}`, { method, headers: { "content-type": "application/json", ...(key ? { "idempotency-key": key } : {}) }, ...(method === "GET" ? {} : { body: JSON.stringify({ ...body, ...(key ? { idempotency_key: key } : {}) }) }) });

test("RC1-1 30% 訂金使用整數分與 basis points", () => assert.equal(calculate().actual_deposit_collected_minor, 300_000));
test("RC1-2 預估金流費預設以代收訂金為基礎", () => assert.equal(calculate().processing_fee_minor, 8_250));
test("RC1-3 Provider actual fee 覆蓋 estimated fee", () => { const result = calculate({ actual_processing_fee_minor: 7777 }); assert.equal(result.processing_fee_minor, 7777); assert.equal(result.processing_fee_source, "actual"); });
test("RC1-4 tax reserve 預設為 0", () => assert.equal(calculate().tax_reserve_minor, 0));
test("RC1-5 withholding 預設為 0", () => assert.equal(calculate().withholding_minor, 0));
test("RC1-6 upfront 不產生銷售抵付", () => assert.equal(calculate({ prior_offset_amount_minor: 900000 }).current_offset_amount_minor, 0));
test("RC1-7 sales offset 正確累計", () => assert.equal(calculate({ profile: { payment_plan: "sales_offset_18000" }, prior_offset_amount_minor: 100000 }).cumulative_offset_amount_minor, 120000));
test("RC1-8 17,500 + 2,000 僅抵 500", () => { const result = calculate({ profile: { payment_plan: "sales_offset_18000", continue_platform_fee_after_offset: true }, total_order_amount_minor: 10_000_000, prior_offset_amount_minor: 1_750_000 }); assert.equal(result.current_offset_amount_minor, 50_000); assert.equal(result.ongoing_platform_fee_minor, 150_000); });
test("RC1-9 locked 金額 immutable", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); assert.throws(() => db.sqlite.prepare("UPDATE merchant_settlements SET merchant_payable_minor=1 WHERE id='statement-1'").run(), /immutable/); });
test("RC1-10 idempotency unique", () => { const db = new D1(); seedProfile(db); seedStatement(db); db.sqlite.prepare("INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,idempotency_key,created_by) VALUES ('a','statement-1',?,'lock','same','admin')").run(merchantId); assert.throws(() => db.sqlite.prepare("INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,idempotency_key,created_by) VALUES ('b','statement-1',?,'lock','same','admin')").run(merchantId), /UNIQUE/); });
test("RC1-11 merchant isolation", () => { const db = new D1(); seedProfile(db); seedStatement(db); assert.throws(() => db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES ('bad','statement-1','merchant_b','deposit','payment','x',1,'2026-08-01','{}')").run(), /FOREIGN KEY/); });
test("RC1-12 rounding 與負數防護", () => { assert.equal(roundByBasisPoints(1, 5000), 1); assert.throws(() => roundByBasisPoints(-1, 200)); });

test("RC2-1 舊付款 CSV 欄位仍存在", () => { const source = readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"); for (const label of ["日期", "商家", "訂單", "付款方式", "Payment Provider", "實收金額", "手續費", "淨額", "狀態", "交易編號", "來源"]) assert.match(source, new RegExp(label)); });
test("RC2-2 付款表淨額與來源存在", () => { const source = readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"); assert.match(source, /<th>淨額<\/th>/); assert.match(source, /人工確認/); assert.match(source, /自動入帳/); });
test("RC2-3 人工付款可選 pending", () => assert.match(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /option value="pending"/));
test("RC2-4 Taipei 2026-08 月底為 31 日", () => assert.equal(formatTaipeiDate("2026-08-31T15:59:59.000Z"), "2026-08-31"));
test("RC2-5 8/31 23:59:59 屬於八月", () => { const end = taipeiDateToUtcEndExclusive("2026-08-31"); assert.ok("2026-08-31T15:59:59.000Z" < end); });
test("RC2-6 9/1 00:00 不屬八月", () => assert.equal("2026-08-31T16:00:00.000Z", taipeiDateToUtcEndExclusive("2026-08-31")));
test("RC2-7 UTC 跨日台灣日期正確", () => assert.equal(formatTaipeiDate("2026-08-31T16:05:00.000Z"), "2026-09-01"));
test("RC2-8 前端月底不使用 UTC slice", () => assert.doesNotMatch(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /toISOString\(\)\.slice/));
test("RC2-9 凌晨匯款日期使用 Taipei helper", () => assert.match(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /getTaipeiToday/));
test("RC2-10 unrelated manual payment 不進 settlement", async () => { const db = new D1(); seedProfile(db); seedPayment(db, { source: "manual" }); const response = await handleSettlementRequest(req("/settlements/preview", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }), { FINANCE_DB: db }, new URL("https://worker.test/api/finance/settlements/preview"), {}, { admin_user_id: "admin" }); assert.equal((await response.json()).transaction_count, 0); });
test("RC2-11 merchant direct 不進 settlement", async () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment, { role: "merchant_direct", eligible: 0 }); const response = await handleSettlementRequest(req("/settlements/preview", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }), { FINANCE_DB: db }, new URL("https://worker.test/api/finance/settlements/preview"), {}, { admin_user_id: "admin" }); assert.equal((await response.json()).transaction_count, 0); });
test("RC2-12 test payment 不進 settlement", () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment, { role: "test", eligible: 0 }); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_settlement_sources WHERE collection_role='platform_deposit' AND settlement_eligible=1").get().n, 0); });
test("RC2-13 缺 order link 不可取得資格", async () => { const db = new D1(); seedProfile(db); db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,gross_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES ('orphan','ORPHAN',?,3000,3000,3000,'card','paid','2026-08-01','webhook')").run(merchantId); const request = req("/settlement-sources/orphan", "PATCH", { collection_role: "platform_deposit", settlement_eligible: true, order_total_amount_minor: 1000000, actual_collected_amount_minor: 300000, confirm_source_review: true }); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.equal(response.status, 400); });
test("RC2-14 actual deposit 使用 captured 金額", () => assert.equal(calculate({ actual_deposit_collected_minor: 280000 }).merchant_payable_minor, 252300));
test("RC2-15 expected/actual variance", () => assert.equal(calculate({ actual_deposit_collected_minor: 280000 }).deposit_variance_minor, -20000));
test("RC2-16 variance 未核准不可鎖定", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "review", variance: -1000 }); const request = req("/settlements/statement-1/lock", "POST", {}, "variance-lock"); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.notEqual(response.status, 200); });
test("RC2-17 mixed actual/estimated fee", () => { const profile = { ...baseProfile }; const fees = calculateProcessingFees([{ order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: 30 }, { order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }, { order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }], profile); assert.equal(fees.actual_fee_total_minor, 30); assert.equal(fees.estimated_fee_total_minor, 1650); assert.equal(fees.processing_fee_minor, 1680); });
test("RC2-18 actual_only 缺費阻止鎖定", () => assert.throws(() => calculate({ profile: { processing_fee_mode: "actual_only" }, sources: [{ order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }] }), /Actual processing fee/));
test("RC2-19 部分退款按比例回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 15000, profile: baseProfile }); assert.equal(result.platform_fee_reversal_minor, -1000); assert.equal(result.offset_reversal_minor, -1000); });
test("RC2-20 完全退款回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 30000, profile: baseProfile }); assert.equal(result.deposit_reversal_minor, -30000); assert.equal(result.platform_fee_reversal_minor, -2000); });
test("RC2-21 Provider 手續費不退", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 30000, profile: baseProfile }); assert.equal(result.provider_fee_retained_minor, 900); });
test("RC2-22 抵付進度回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 1500, refundMinor: 30000, profile: baseProfile }); assert.equal(result.offset_reversal_minor, -1500); });
test("RC2-23 跨月退款建立下一期 adjustment", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked", actual: 30000, platformFee: 2000, processingFee: 900 }); const payment = seedPayment(db); db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,order_id,payment_id,amount_minor,actual_deposit_amount_minor,occurred_at,source_snapshot_json) VALUES ('item','statement-1',?,'deposit','payment',?,?,?,30000,30000,'2026-08-01','{}')").run(merchantId, payment.paymentId, payment.orderId, payment.paymentId); db.sqlite.prepare("INSERT INTO refunds(id,payment_id,amount,status,refunded_at) VALUES ('refund-cross',?,300,'refunded','2026-09-05T00:00:00Z')").run(payment.paymentId); const result = await createSettlementRefundAdjustment(db, { admin_user_id: "admin" }, "refund-cross"); assert.equal(result.deposit_reversal_minor, -30000); assert.equal(db.sqlite.prepare("SELECT status FROM merchant_settlement_adjustments").get().status, "pending"); });
test("RC2-24 draft void 釋放來源", async () => { const db = new D1(); seedProfile(db); seedStatement(db); const payment = seedPayment(db); qualify(db, payment, { reserved: "statement-1" }); const request = req("/settlements/statement-1/void", "POST", { reason: "重建" }, "void-one"); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.equal(response.status, 200); assert.equal(db.sqlite.prepare("SELECT reserved_statement_id FROM merchant_settlement_sources").get().reserved_statement_id, null); });
test("RC2-25 同期間 replacement statement", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "void" }); assert.doesNotThrow(() => seedStatement(db, { id: "replacement" })); });
test("RC2-26 locked 不可 void", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); const request = req("/settlements/statement-1/void", "POST", { reason: "x" }, "void-locked"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-27 paid 不可 void", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "paid" }); const request = req("/settlements/statement-1/void", "POST", { reason: "x" }, "void-paid"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-28 void statement 不可重新啟用", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "void" }); const request = req("/settlements/statement-1/submit-review", "POST", {}, "reactivate"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-29 locked/paid PDF key 不覆寫", () => { const source = readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"); assert.match(source, /locked-\$\{pdf\.pdfHash\}/); assert.match(source, /paid-\$\{pdf\.pdfHash\}/); });
test("RC2-30 R2 成功 D1 失敗有清理策略", () => assert.match(readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"), /CONTRACTS_BUCKET\.delete\(r2Key\)/));
test("RC2-31 mutation idempotency replay", () => assert.match(readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"), /idempotent-replay/));
test("RC2-32 adjustment 重複 key 受 UNIQUE 保護", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); const sql = "INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,idempotency_key,created_by) VALUES (?,?,?,?,?,?,?,?)"; db.sqlite.prepare(sql).run("a", merchantId, "statement-1", "refund", -1, "r", "same", "admin"); assert.throws(() => db.sqlite.prepare(sql).run("b", merchantId, "statement-1", "refund", -1, "r", "same", "admin"), /UNIQUE/); });
test("RC2-33 review 狀態有進有退", async () => { const db = new D1(); seedProfile(db); seedStatement(db); let request = req("/settlements/statement-1/submit-review", "POST", {}, "review-in"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); request = req("/settlements/statement-1/return-draft", "POST", {}, "review-out"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); });
test("RC2-34 settlement 查詢不用 BETWEEN/date(timestamp)", () => { const source = readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"); assert.doesNotMatch(source, /BETWEEN|date\(COALESCE/); assert.match(source, />=\?/); assert.match(source, /<\?/); });
test("RC2-35 PDF/CSV 顯示 fee 組成", () => { const source = readFileSync(new URL("../src/settlement-pdf.js", import.meta.url), "utf8"); assert.match(source, /實際金流手續費/); assert.match(source, /估算金流手續費/); assert.match(source, /processing_fee_source/); });
test("RC2-36 公開頁不顯示內部 enum", () => { for (const file of ["../../src/pages/DepositSettlementPage.tsx", "../../src/pages/CommercialV13Pages.tsx"]) { const source = readFileSync(new URL(file, import.meta.url), "utf8"); assert.doesNotMatch(source, />upfront_18000<|>sales_offset_18000</); } });
test("RC2-37 lock 與 paid 產生兩個不可變 PDF 版本且重試冪等", async () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment); db.sqlite.prepare("INSERT INTO platform_finance_settings(id,legal_entity_name,tax_id) VALUES ('default','測試法律主體','00000000')").run(); const keys = []; const env = { FINANCE_DB: db, CONTRACTS_BUCKET: { async put(key) { keys.push(key); }, async delete() {} } }; let request = req("/settlements", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }); let response = await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" }); const created = await response.json(); request = req(`/settlements/${created.id}/submit-review`, "POST", {}, "review-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); request = req(`/settlements/${created.id}/lock`, "POST", {}, "lock-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); const statement = db.sqlite.prepare("SELECT merchant_payable_minor FROM merchant_settlements WHERE id=?").get(created.id); request = req(`/settlements/${created.id}/mark-paid`, "POST", { transfer_amount_minor: statement.merchant_payable_minor, transfer_date: "2026-09-01", transfer_reference: "TX-1" }, "paid-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM settlement_document_versions").get().n, 2); assert.equal(new Set(keys).size, 2); assert.match(keys[0], /locked-/); assert.match(keys[1], /paid-/); });

async function authEnv() { const db = new D1(); const salt = "admin-salt"; const hash = await deriveAdminPassword("A-secure-admin-password-2026", salt); db.sqlite.prepare("INSERT INTO admin_users(id,email,display_name,password_hash,password_salt,role) VALUES ('admin','owner@example.com','管理員',?,?,'super_admin')").run(hash, salt); return { db, env: { FINANCE_DB: db, ALLOWED_ORIGINS: "https://baiyeconnect.com", CONTRACTS_BUCKET: { async get() { return null; }, async put() {}, async delete() {} } } }; }
async function login(env) { const request = new Request("https://worker.test/api/admin/auth/login", { method: "POST", headers: { origin: "https://baiyeconnect.com", "content-type": "application/json" }, body: JSON.stringify({ email: "owner@example.com", password: "A-secure-admin-password-2026" }) }); const response = await worker.fetch(request, env, {}); const body = await response.json(); return { cookie: response.headers.get("set-cookie").split(";")[0], csrf: body.csrf_token }; }
test("RC2-38 未登入 Admin 仍回 401", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements", { headers: { origin: "https://baiyeconnect.com" } }), env, {}); assert.equal(response.status, 401); });
test("RC2-39 缺 CSRF mutation 被拒絕", async () => { const { env } = await authEnv(); const session = await login(env); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements/preview", { method: "POST", headers: { origin: "https://baiyeconnect.com", cookie: session.cookie, "content-type": "application/json" }, body: "{}" }), env, {}); assert.equal(response.status, 401); });
test("RC2-40 非正式 Origin 被拒絕", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements", { headers: { origin: "https://evil.example" } }), env, {}); assert.equal(response.status, 403); });
test("RC2-41 PDF 未授權不得下載", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements/secret/pdf", { headers: { origin: "https://baiyeconnect.com" } }), env, {}); assert.equal(response.status, 401); });
