import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import worker from "../src/index.js";
import { deriveAdminPassword } from "../src/admin-auth.js";
import { calculateProcessingFees, calculateRefundReversal, calculateSettlement, decimalMajorToMinor, roundByBasisPoints } from "../src/settlement-engine.js";
import { createSettlementRefundAdjustment, handleSettlementRequest } from "../src/settlements.js";
import { financeSummary, handleFinanceRequest } from "../src/finance.js";
import { createSettlementPdf, settlementCsv } from "../src/settlement-pdf.js";
import { formatTaipeiDate, isDate, taipeiDateToUtcEndExclusive, taipeiDateToUtcStart } from "../src/taipei-date.js";

class Statement {
  constructor(statement) { this.statement = statement; this.values = []; }
  bind(...values) { this.values = values; return this; }
  async run() { const result = this.statement.run(...this.values); return { meta: { changes: Number(result.changes || 0) } }; }
  async first() { return this.statement.get(...this.values) || null; }
  async all() { return { results: this.statement.all(...this.values) }; }
}
class D1 {
  constructor() {
    this.sqlite = new DatabaseSync(":memory:");
    this.sqlite.exec("PRAGMA foreign_keys=ON");
    for (const file of ["0001_finance_core.sql", "0002_partner_portal.sql", "0009_production_admin_auth.sql", "0010_merchant_settlements.sql"]) this.sqlite.exec(readFileSync(new URL(`../migrations/${file}`, import.meta.url), "utf8"));
    this.sqlite.prepare("INSERT INTO merchants(id,merchant_code,name,status) VALUES ('merchant_b','B','商家 B','active')").run();
  }
  prepare(sql) { return new Statement(this.sqlite.prepare(sql)); }
  async batch(statements) { this.sqlite.exec("BEGIN IMMEDIATE"); try { const results = []; for (const statement of statements) results.push(await statement.run()); this.sqlite.exec("COMMIT"); return results; } catch (error) { this.sqlite.exec("ROLLBACK"); throw error; } }
}

const merchantId = "merchant_meiling_001";
const baseProfile = { enabled: true, payment_plan: "upfront_18000", deposit_rate_bp: 3000, platform_fee_rate_bp: 200, processing_fee_mode: "actual_or_estimated", processing_fee_basis: "deposit_collected", estimated_processing_fee_rate_bp: 275, tax_reserve_mode: "disabled", tax_reserve_rate_bp: 0, withholding_mode: "disabled", withholding_rate_bp: 0, refund_platform_fee_policy: "pro_rata_reverse", refund_offset_policy: "pro_rata_reverse", provider_fee_refund_policy: "no_reverse", offset_target_amount_minor: 1_800_000, continue_platform_fee_after_offset: false, settlement_day: 10, legal_review_status: "approved", accounting_review_status: "pending", effective_from: "2026-08-01" };
const calculate = (overrides = {}) => calculateSettlement({ profile: { ...baseProfile, ...overrides.profile }, total_order_amount_minor: overrides.total_order_amount_minor ?? 1_000_000, actual_processing_fee_minor: overrides.actual_processing_fee_minor, actual_deposit_collected_minor: overrides.actual_deposit_collected_minor, prior_offset_amount_minor: overrides.prior_offset_amount_minor ?? 0, adjustments_minor: overrides.adjustments_minor ?? 0, sources: overrides.sources });
function seedProfile(db, id = merchantId, plan = "upfront_18000", overrides = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlement_profiles(id,merchant_id,enabled,payment_plan,deposit_rate_bp,platform_fee_rate_bp,processing_fee_mode,processing_fee_basis,estimated_processing_fee_rate_bp,legal_review_status,effective_from,refund_platform_fee_policy,refund_offset_policy,provider_fee_refund_policy) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`profile-${id}`, id, 1, plan, 3000, 200, overrides.processing_fee_mode || "actual_or_estimated", "deposit_collected", 275, "approved", "2026-08-01", overrides.refund_platform_fee_policy || "pro_rata_reverse", overrides.refund_offset_policy || "pro_rata_reverse", overrides.provider_fee_refund_policy || "no_reverse"); }
function seedStatement(db, { id = "statement-1", merchant = merchantId, status = "draft", start = "2026-08-01", end = "2026-08-31", payable = 10000, variance = 0, actual = 0, platformFee = 0, offset = 0, processingFee = 0 } = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlements(id,statement_no,merchant_id,profile_id,period_start,period_end,period_start_utc,period_end_exclusive_utc,status,merchant_payable_minor,deposit_variance_minor,actual_deposit_collected_minor,platform_service_fee_minor,current_offset_amount_minor,processing_fee_minor,calculation_version,rules_snapshot_json,locked_at,paid_at,transfer_amount_minor,transfer_reference,voided_at,void_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id, `NO-${id}`, merchant, `profile-${merchant}`, start, end, taipeiDateToUtcStart(start), taipeiDateToUtcEndExclusive(end), status, payable, variance, actual, platformFee, offset, processingFee, "settlement-v3", "{\"calculation_version\":\"settlement-v3\"}", ["locked", "paid"].includes(status) ? "2026-09-01T00:00:00Z" : null, status === "paid" ? "2026-09-01T01:00:00Z" : null, status === "paid" ? payable : null, status === "paid" ? "TX" : null, status === "void" ? "2026-09-01T00:00:00Z" : null, status === "void" ? "void test" : null); }
function seedPayment(db, { suffix = "1", merchant = merchantId, source = "webhook", status = "paid", gross = 3000, fee = 30, paidAt = "2026-08-31T15:59:59.000Z", orderCurrency = "TWD", paymentCurrency = "TWD" } = {}) { const orderId = `order-${suffix}`, paymentId = `payment-${suffix}`; db.sqlite.prepare("INSERT INTO orders(id,order_no,merchant_id,title,amount_due,currency,payment_status) VALUES (?,?,?,?,?,?,?)").run(orderId, `ORD-${suffix}`, merchant, "訂單", 10000, orderCurrency, "paid"); db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,order_id,gross_amount,fee_amount,net_amount,amount,currency,payment_method,status,paid_at,source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").run(paymentId, `PAY-${suffix}`, merchant, orderId, gross, fee, gross - (fee || 0), gross, paymentCurrency, "card", status, paidAt, source); return { orderId, paymentId }; }
function qualify(db, payment, { role = "platform_deposit", eligible = 1, orderTotal = 1_000_000, expected = 300_000, actual = 300_000, fee = 3000, occurredAt = "2026-08-31T15:59:59.000Z", reserved = null } = {}) { db.sqlite.prepare(`INSERT INTO merchant_settlement_sources(id,merchant_id,payment_id,order_id,collection_role,settlement_eligible,order_total_amount_minor,expected_deposit_amount_minor,actual_collected_amount_minor,provider_fee_actual_minor,occurred_at,reviewed_by,reviewed_at,reserved_statement_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`source-${payment.paymentId}`, merchantId, payment.paymentId, payment.orderId, role, eligible, orderTotal, expected, actual, fee, occurredAt, eligible ? "admin" : null, eligible ? "2026-08-01T00:00:00Z" : null, reserved); }
const req = (path, method = "GET", body = {}, key = null) => new Request(`https://worker.test/api/finance${path}`, { method, headers: { "content-type": "application/json", ...(key ? { "idempotency-key": key } : {}) }, ...(method === "GET" ? {} : { body: JSON.stringify({ ...body, ...(key ? { idempotency_key: key } : {}) }) }) });

test("RC1-1 30% 訂金使用整數分與 basis points", () => assert.equal(calculate().actual_deposit_collected_minor, 300_000));
test("RC1-2 預估金流費預設以代收訂金為基礎", () => assert.equal(calculate().processing_fee_minor, 8_250));
test("RC1-3 Provider actual fee 覆蓋 estimated fee", () => { const result = calculate({ actual_processing_fee_minor: 7777 }); assert.equal(result.processing_fee_minor, 7777); assert.equal(result.processing_fee_source, "actual"); });
test("RC1-4 tax reserve 預設為 0", () => assert.equal(calculate().tax_reserve_minor, 0));
test("RC1-5 withholding 預設為 0", () => assert.equal(calculate().withholding_minor, 0));
test("RC1-6 upfront 不產生銷售抵付", () => assert.equal(calculate({ prior_offset_amount_minor: 900000 }).current_offset_amount_minor, 0));
test("RC1-7 sales offset 正確累計", () => assert.equal(calculate({ profile: { payment_plan: "sales_offset_18000" }, prior_offset_amount_minor: 100000 }).cumulative_offset_amount_minor, 120000));
test("RC1-8 17,500 + 2,000 僅抵 500", () => { const result = calculate({ profile: { payment_plan: "sales_offset_18000", continue_platform_fee_after_offset: true }, total_order_amount_minor: 10_000_000, prior_offset_amount_minor: 1_750_000 }); assert.equal(result.current_offset_amount_minor, 50_000); assert.equal(result.ongoing_platform_fee_minor, 150_000); });
test("RC1-9 locked 金額 immutable", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); assert.throws(() => db.sqlite.prepare("UPDATE merchant_settlements SET merchant_payable_minor=1 WHERE id='statement-1'").run(), /immutable/); });
test("RC1-10 idempotency unique", () => { const db = new D1(); seedProfile(db); seedStatement(db); const sql="INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,operation_scope,idempotency_key,expires_at,created_by) VALUES (?,'statement-1',?,'lock','statement-1','same','2099-01-01','admin')"; db.sqlite.prepare(sql).run('a',merchantId); assert.throws(() => db.sqlite.prepare(sql).run('b',merchantId), /UNIQUE/); });
test("RC1-11 merchant isolation", () => { const db = new D1(); seedProfile(db); seedStatement(db); assert.throws(() => db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES ('bad','statement-1','merchant_b','deposit','payment','x',1,'2026-08-01','{}')").run(), /FOREIGN KEY/); });
test("RC1-12 rounding 與負數防護", () => { assert.equal(roundByBasisPoints(1, 5000), 1); assert.throws(() => roundByBasisPoints(-1, 200)); });

test("RC2-1 舊付款 CSV 欄位仍存在", () => { const source = readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"); for (const label of ["日期", "商家", "訂單", "付款方式", "Payment Provider", "實收金額", "手續費", "淨額", "狀態", "交易編號", "來源"]) assert.match(source, new RegExp(label)); });
test("RC2-2 付款表淨額與來源存在", () => { const source = readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"); assert.match(source, /<th>淨額<\/th>/); assert.match(source, /人工確認/); assert.match(source, /自動入帳/); });
test("RC2-3 人工付款可選 pending", () => assert.match(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /option value="pending"/));
test("RC2-4 Taipei 2026-08 月底為 31 日", () => assert.equal(formatTaipeiDate("2026-08-31T15:59:59.000Z"), "2026-08-31"));
test("RC2-5 8/31 23:59:59 屬於八月", () => { const end = taipeiDateToUtcEndExclusive("2026-08-31"); assert.ok("2026-08-31T15:59:59.000Z" < end); });
test("RC2-6 9/1 00:00 不屬八月", () => assert.equal("2026-08-31T16:00:00.000Z", taipeiDateToUtcEndExclusive("2026-08-31")));
test("RC2-7 UTC 跨日台灣日期正確", () => assert.equal(formatTaipeiDate("2026-08-31T16:05:00.000Z"), "2026-09-01"));
test("RC2-8 前端月底不使用 UTC slice", () => assert.doesNotMatch(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /toISOString\(\)\.slice/));
test("RC2-9 凌晨匯款日期使用 Taipei helper", () => assert.match(readFileSync(new URL("../../src/pages/AdminFinance.tsx", import.meta.url), "utf8"), /getTaipeiToday/));
test("RC2-10 unrelated manual payment 不進 settlement", async () => { const db = new D1(); seedProfile(db); seedPayment(db, { source: "manual" }); const response = await handleSettlementRequest(req("/settlements/preview", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }), { FINANCE_DB: db }, new URL("https://worker.test/api/finance/settlements/preview"), {}, { admin_user_id: "admin" }); assert.equal((await response.json()).transaction_count, 0); });
test("RC2-11 merchant direct 不進 settlement", async () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment, { role: "merchant_direct", eligible: 0 }); const response = await handleSettlementRequest(req("/settlements/preview", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }), { FINANCE_DB: db }, new URL("https://worker.test/api/finance/settlements/preview"), {}, { admin_user_id: "admin" }); assert.equal((await response.json()).transaction_count, 0); });
test("RC2-12 test payment 不進 settlement", () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment, { role: "test", eligible: 0 }); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_settlement_sources WHERE collection_role='platform_deposit' AND settlement_eligible=1").get().n, 0); });
test("RC2-13 缺 order link 不可取得資格", async () => { const db = new D1(); seedProfile(db); db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,gross_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES ('orphan','ORPHAN',?,3000,3000,3000,'card','paid','2026-08-01','webhook')").run(merchantId); const request = req("/settlement-sources/orphan", "PATCH", { collection_role: "platform_deposit", settlement_eligible: true, order_total_amount_minor: 1000000, actual_collected_amount_minor: 300000, confirm_source_review: true }); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.equal(response.status, 400); });
test("RC2-14 actual deposit 使用 captured 金額", () => assert.equal(calculate({ actual_deposit_collected_minor: 280000 }).merchant_payable_minor, 252300));
test("RC2-15 expected/actual variance", () => assert.equal(calculate({ actual_deposit_collected_minor: 280000 }).deposit_variance_minor, -20000));
test("RC2-16 variance 未核准不可鎖定", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "review", variance: -1000 }); const request = req("/settlements/statement-1/lock", "POST", {}, "variance-lock"); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.notEqual(response.status, 200); });
test("RC2-17 mixed actual/estimated fee", () => { const profile = { ...baseProfile }; const fees = calculateProcessingFees([{ order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: 30 }, { order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }, { order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }], profile); assert.equal(fees.actual_fee_total_minor, 30); assert.equal(fees.estimated_fee_total_minor, 1650); assert.equal(fees.processing_fee_minor, 1680); });
test("RC2-18 actual_only 缺費阻止鎖定", () => assert.throws(() => calculate({ profile: { processing_fee_mode: "actual_only" }, sources: [{ order_total_amount_minor: 100000, actual_collected_amount_minor: 30000, provider_fee_actual_minor: null }] }), /Actual processing fee/));
test("RC2-19 部分退款按比例回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 15000, profile: baseProfile }); assert.equal(result.platform_fee_reversal_minor, -1000); assert.equal(result.offset_reversal_minor, -1000); });
test("RC2-20 完全退款回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 30000, profile: baseProfile }); assert.equal(result.deposit_reversal_minor, -30000); assert.equal(result.platform_fee_reversal_minor, -2000); });
test("RC2-21 Provider 手續費不退", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 2000, providerFeeMinor: 900, refundMinor: 30000, profile: baseProfile }); assert.equal(result.provider_fee_retained_minor, 900); });
test("RC2-22 抵付進度回沖", () => { const result = calculateRefundReversal({ depositMinor: 30000, platformFeeMinor: 2000, currentOffsetMinor: 1500, refundMinor: 30000, profile: baseProfile }); assert.equal(result.offset_reversal_minor, -1500); });
test("RC2-23 跨月退款建立下一期 adjustment", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked", actual: 30000, platformFee: 2000, processingFee: 900 }); const payment = seedPayment(db); db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,order_id,payment_id,amount_minor,actual_deposit_amount_minor,occurred_at,source_snapshot_json) VALUES ('item','statement-1',?,'deposit','payment',?,?,?,30000,30000,'2026-08-01','{}')").run(merchantId, payment.paymentId, payment.orderId, payment.paymentId); db.sqlite.prepare("INSERT INTO refunds(id,payment_id,amount,status,refunded_at) VALUES ('refund-cross',?,300,'refunded','2026-09-05T00:00:00Z')").run(payment.paymentId); const result = await createSettlementRefundAdjustment(db, { admin_user_id: "admin" }, "refund-cross"); assert.equal(result.deposit_reversal_minor, -30000); assert.equal(db.sqlite.prepare("SELECT status FROM merchant_settlement_adjustments").get().status, "pending"); });
test("RC2-24 draft void 釋放來源", async () => { const db = new D1(); seedProfile(db); seedStatement(db); const payment = seedPayment(db); qualify(db, payment, { reserved: "statement-1" }); const request = req("/settlements/statement-1/void", "POST", { reason: "重建" }, "void-one"); const response = await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" }); assert.equal(response.status, 200); assert.equal(db.sqlite.prepare("SELECT reserved_statement_id FROM merchant_settlement_sources").get().reserved_statement_id, null); });
test("RC2-25 同期間 replacement statement", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "void" }); assert.doesNotThrow(() => seedStatement(db, { id: "replacement" })); });
test("RC2-26 locked 不可 void", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); const request = req("/settlements/statement-1/void", "POST", { reason: "x" }, "void-locked"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-27 paid 不可 void", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "paid" }); const request = req("/settlements/statement-1/void", "POST", { reason: "x" }, "void-paid"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-28 void statement 不可重新啟用", async () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "void" }); const request = req("/settlements/statement-1/submit-review", "POST", {}, "reactivate"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 409); });
test("RC2-29 locked/paid PDF key 不覆寫", () => { const source = readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"); assert.match(source, /locked-\$\{pdf\.pdfHash\}/); assert.match(source, /paid-\$\{pdf\.pdfHash\}/); });
test("RC2-30 R2 成功 D1 失敗有清理策略", () => assert.match(readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"), /CONTRACTS_BUCKET\.delete\(r2Key\)/));
test("RC2-31 mutation idempotency replay", () => assert.match(readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"), /idempotent-replay/));
test("RC2-32 adjustment 重複 key 受 UNIQUE 保護", () => { const db = new D1(); seedProfile(db); seedStatement(db, { status: "locked" }); const sql = "INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,idempotency_key,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)"; db.sqlite.prepare(sql).run("a", merchantId, "statement-1", "refund", -1, "r", "2026-09-01", "2026-09-01", "same", "admin"); assert.throws(() => db.sqlite.prepare(sql).run("b", merchantId, "statement-1", "refund", -1, "r", "2026-09-01", "2026-09-01", "same", "admin"), /UNIQUE/); });
test("RC2-33 review 狀態有進有退", async () => { const db = new D1(); seedProfile(db); seedStatement(db); let request = req("/settlements/statement-1/submit-review", "POST", {}, "review-in"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); request = req("/settlements/statement-1/return-draft", "POST", {}, "review-out"); assert.equal((await handleSettlementRequest(request, { FINANCE_DB: db }, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); });
test("RC2-34 settlement 查詢不用 BETWEEN/date(timestamp)", () => { const source = readFileSync(new URL("../src/settlements.js", import.meta.url), "utf8"); assert.doesNotMatch(source, /BETWEEN|date\(COALESCE/); assert.match(source, />=\?/); assert.match(source, /<\?/); });
test("RC2-35 PDF/CSV 顯示 fee 組成", () => { const source = readFileSync(new URL("../src/settlement-pdf.js", import.meta.url), "utf8"); assert.match(source, /實際金流手續費/); assert.match(source, /估算金流手續費/); assert.match(source, /processing_fee_source/); });
test("RC2-36 公開頁不顯示內部 enum", () => { for (const file of ["../../src/pages/DepositSettlementPage.tsx", "../../src/pages/CommercialV13Pages.tsx"]) { const source = readFileSync(new URL(file, import.meta.url), "utf8"); assert.doesNotMatch(source, />upfront_18000<|>sales_offset_18000</); } });
test("RC2-37 lock 與 paid 產生兩個不可變 PDF 版本且重試冪等", async () => { const db = new D1(); seedProfile(db); const payment = seedPayment(db); qualify(db, payment); db.sqlite.prepare("INSERT INTO platform_finance_settings(id,legal_entity_name,tax_id) VALUES ('default','測試法律主體','00000000')").run(); const keys = []; const env = { FINANCE_DB: db, CONTRACTS_BUCKET: { async put(key) { keys.push(key); }, async delete() {} } }; let request = req("/settlements", "POST", { merchant_id: merchantId, period_start: "2026-08-01", period_end: "2026-08-31" }, "create-pdf"); let response = await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" }); const created = await response.json(); request = req(`/settlements/${created.id}/submit-review`, "POST", {}, "review-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); request = req(`/settlements/${created.id}/lock`, "POST", {}, "lock-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); const statement = db.sqlite.prepare("SELECT merchant_payable_minor FROM merchant_settlements WHERE id=?").get(created.id); request = req(`/settlements/${created.id}/mark-paid`, "POST", { transfer_amount_minor: statement.merchant_payable_minor, transfer_date: "2026-09-01", transfer_reference: "TX-1" }, "paid-pdf"); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); assert.equal((await handleSettlementRequest(request, env, new URL(request.url), {}, { admin_user_id: "admin" })).status, 200); assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM settlement_document_versions").get().n, 2); assert.equal(new Set(keys).size, 2); assert.match(keys[0], /locked-/); assert.match(keys[1], /paid-/); });

async function authEnv() { const db = new D1(); const salt = "admin-salt"; const hash = await deriveAdminPassword("A-secure-admin-password-2026", salt); db.sqlite.prepare("INSERT INTO admin_users(id,email,display_name,password_hash,password_salt,role) VALUES ('admin','owner@example.com','管理員',?,?,'super_admin')").run(hash, salt); return { db, env: { FINANCE_DB: db, ALLOWED_ORIGINS: "https://baiyeconnect.com", CONTRACTS_BUCKET: { async get() { return null; }, async put() {}, async delete() {} } } }; }
async function login(env) { const request = new Request("https://worker.test/api/admin/auth/login", { method: "POST", headers: { origin: "https://baiyeconnect.com", "content-type": "application/json" }, body: JSON.stringify({ email: "owner@example.com", password: "A-secure-admin-password-2026" }) }); const response = await worker.fetch(request, env, {}); const body = await response.json(); return { cookie: response.headers.get("set-cookie").split(";")[0], csrf: body.csrf_token }; }
test("RC2-38 未登入 Admin 仍回 401", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements", { headers: { origin: "https://baiyeconnect.com" } }), env, {}); assert.equal(response.status, 401); });
test("RC2-39 缺 CSRF mutation 被拒絕", async () => { const { env } = await authEnv(); const session = await login(env); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements/preview", { method: "POST", headers: { origin: "https://baiyeconnect.com", cookie: session.cookie, "content-type": "application/json" }, body: "{}" }), env, {}); assert.equal(response.status, 401); });
test("RC2-40 非正式 Origin 被拒絕", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements", { headers: { origin: "https://evil.example" } }), env, {}); assert.equal(response.status, 403); });
test("RC2-41 PDF 未授權不得下載", async () => { const { env } = await authEnv(); const response = await worker.fetch(new Request("https://worker.test/api/finance/settlements/secret/pdf", { headers: { origin: "https://baiyeconnect.com" } }), env, {}); assert.equal(response.status, 401); });

test("RC3-1 同一訂單兩筆合格訂金被 DB 拒絕", () => { const db=new D1(); seedProfile(db); const first=seedPayment(db,{suffix:"same-a"}); qualify(db,first); const secondId="payment-same-b"; db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,order_id,gross_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES (?,?,?,?,1500,1500,1500,'card','paid','2026-08-01','webhook')").run(secondId,"PAY-SAME-B",merchantId,first.orderId); assert.throws(()=>db.sqlite.prepare("INSERT INTO merchant_settlement_sources(id,merchant_id,payment_id,order_id,collection_role,settlement_eligible,order_total_amount_minor,expected_deposit_amount_minor,actual_collected_amount_minor,occurred_at,reviewed_by,reviewed_at) VALUES ('second',?,?,?,'platform_deposit',1,1000000,300000,150000,'2026-08-01','admin','2026-08-01')").run(merchantId,secondId,first.orderId),/UNIQUE/); });
test("RC3-2 計算引擎阻止同訂單重複平台費", () => assert.throws(()=>calculate({sources:[{order_id:"same",order_total_amount_minor:1_000_000,expected_deposit_amount_minor:300_000,actual_collected_amount_minor:150_000,provider_fee_actual_minor:0},{order_id:"same",order_total_amount_minor:1_000_000,expected_deposit_amount_minor:300_000,actual_collected_amount_minor:150_000,provider_fee_actual_minor:0}]}),/同一訂單/));
test("RC3-3 Offset Ledger 三期維持 8,500", () => { const db=new D1(); seedProfile(db,merchantId,"sales_offset_18000"); const sql="INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES (?,?,?,?,?,?,?)"; db.sqlite.prepare(sql).run("aug",merchantId,"offset_earned",1_000_000,"2026-08-31","aug","admin"); db.sqlite.prepare(sql).run("sep-r",merchantId,"refund_reversal",-200_000,"2026-09-05","sep-r","admin"); db.sqlite.prepare(sql).run("sep-e",merchantId,"offset_earned",50_000,"2026-09-30","sep-e","admin"); assert.equal(db.sqlite.prepare("SELECT SUM(amount_minor) balance FROM merchant_offset_ledger WHERE merchant_id=? AND status='posted'").get(merchantId).balance,850_000); });
test("RC3-4 回沖後抵付不會被歷史 MAX 復活", () => { const db=new D1(); seedProfile(db,merchantId,"sales_offset_18000"); db.sqlite.exec(`INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('a','${merchantId}','offset_earned',1000000,'2026-08-31','a','admin'); INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('b','${merchantId}','refund_reversal',-200000,'2026-09-05','b','admin');`); assert.equal(db.sqlite.prepare("SELECT SUM(amount_minor) n FROM merchant_offset_ledger").get().n,800000); });
test("RC3-5 跨月退款在原單仍 draft 時建立九月 Adjustment", async()=>{ const db=new D1();seedProfile(db);seedStatement(db);const p=seedPayment(db,{paidAt:"2026-08-25T04:00:00Z"});db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,item_type,source_type,source_id,order_id,payment_id,order_total_amount_minor,actual_deposit_amount_minor,processing_fee_minor,amount_minor,occurred_at,source_snapshot_json) VALUES ('cross','statement-1',?,'deposit','payment',?,?,?,1000000,300000,3000,300000,'2026-08-25','{}')").run(merchantId,p.paymentId,p.orderId,p.paymentId);db.sqlite.prepare("INSERT INTO refunds(id,payment_id,amount,status,refunded_at) VALUES ('sep-refund',?,1000,'refunded','2026-09-05T04:00:00Z')").run(p.paymentId);const result=await createSettlementRefundAdjustment(db,{admin_user_id:"admin"},"sep-refund");assert.equal(result.review_status,"approved");const a=db.sqlite.prepare("SELECT effective_date,eligible_period_start,source_refund_id FROM merchant_settlement_adjustments").get();assert.equal(a.effective_date,"2026-09-05");assert.equal(a.eligible_period_start,"2026-09-05");assert.equal(a.source_refund_id,"sep-refund");});
test("RC3-6 Adjustment 不套用退款日前月份",()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,idempotency_key,created_by) VALUES ('late',?,'statement-1','refund',-100,'x','2026-09-05','2026-09-05','late','admin')").run(merchantId);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_settlement_adjustments WHERE eligible_period_start<='2026-08-31'").get().n,0);});
test("RC3-7 同一 refund 只能有一筆有效 Adjustment",()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});const p=seedPayment(db);db.sqlite.prepare("INSERT INTO refunds(id,payment_id,amount,status,refunded_at) VALUES ('same-ref',?,1,'refunded','2026-09-01')").run(p.paymentId);const sql="INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,source_refund_id,idempotency_key,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)";db.sqlite.prepare(sql).run("two",merchantId,"statement-1","refund",-1,"r","2026-09-01","2026-09-01","same-ref","two","admin");assert.throws(()=>db.sqlite.prepare(sql).run("three",merchantId,"statement-1","refund",-1,"r","2026-09-01","2026-09-01","same-ref","three","admin"),/UNIQUE/);});
test("RC3-8 平台費與 Offset 退款政策獨立",()=>{const a=calculateRefundReversal({depositMinor:30000,platformFeeMinor:2000,currentOffsetMinor:2000,refundMinor:15000,profile:{...baseProfile,refund_platform_fee_policy:"pro_rata_reverse",refund_offset_policy:"no_reverse"}});assert.equal(a.platform_fee_reversal_minor,-1000);assert.equal(a.offset_reversal_minor,0);const b=calculateRefundReversal({depositMinor:30000,platformFeeMinor:2000,currentOffsetMinor:2000,refundMinor:15000,profile:{...baseProfile,refund_platform_fee_policy:"no_reverse",refund_offset_policy:"pro_rata_reverse"}});assert.equal(b.platform_fee_reversal_minor,0);assert.equal(b.offset_reversal_minor,-1000);});
test("RC3-9 Provider fee 只有覆核後按比例回沖",()=>{const blocked=calculateRefundReversal({depositMinor:30000,platformFeeMinor:2000,currentOffsetMinor:0,providerFeeMinor:900,refundMinor:15000,profile:{...baseProfile,provider_fee_refund_policy:"pro_rata_reverse"}});assert.equal(blocked.provider_fee_reversal_minor,0);assert.equal(blocked.requires_provider_fee_review,true);const approved=calculateRefundReversal({depositMinor:30000,platformFeeMinor:2000,currentOffsetMinor:0,providerFeeMinor:900,refundMinor:15000,providerFeeRefundReviewed:true,providerFeeRefundMinor:450,profile:{...baseProfile,provider_fee_refund_policy:"pro_rata_reverse"}});assert.equal(approved.provider_fee_reversal_minor,450);});
test("RC3-10 無新交易負數 carry forward 可鎖定計算",()=>{const result=calculate({sources:[],adjustments_minor:-280000});assert.equal(result.merchant_payable_minor,0);assert.equal(result.merchant_due_to_platform_minor,280000);assert.equal(result.carry_forward_balance_minor,-280000);});
test("RC3-11 部分退款累計不得超過付款",async()=>{const db=new D1();const p=seedPayment(db);const env={FINANCE_DB:db};let request=req(`/payments/${p.paymentId}/refunds`,"POST",{amount:2000},"refund-a");assert.equal((await handleFinanceRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).status,201);request=req(`/payments/${p.paymentId}/refunds`,"POST",{amount:2000},"refund-b");assert.equal((await handleFinanceRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).status,409);});
test("RC3-12 Refund Idempotency replay 不重複",async()=>{const db=new D1();const p=seedPayment(db);const env={FINANCE_DB:db};let request=req(`/payments/${p.paymentId}/refunds`,"POST",{amount:1000},"refund-replay");assert.equal((await handleFinanceRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).status,201);request=req(`/payments/${p.paymentId}/refunds`,"POST",{amount:1000},"refund-replay");assert.equal((await handleFinanceRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).headers.get("idempotent-replay"),"true");assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM refunds").get().n,1);});
test("RC3-13 pending 轉 paid 會填入 paid_at",async()=>{const db=new D1();const p=seedPayment(db,{status:"pending",paidAt:null});const request=req(`/payments/${p.paymentId}`,"PATCH",{status:"paid"});assert.equal((await handleFinanceRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,200);assert.ok(db.sqlite.prepare("SELECT paid_at FROM payments WHERE id=?").get(p.paymentId).paid_at);});
test("RC3-14 付款月份依 paid_at 而非 created_at",async()=>{const db=new D1();seedProfile(db);const p=seedPayment(db,{status:"pending",paidAt:null});db.sqlite.prepare("UPDATE payments SET created_at='2026-08-31T15:00:00Z',status='paid',paid_at='2026-08-31T16:00:00Z' WHERE id=?").run(p.paymentId);const request=req(`/settlement-sources/${p.paymentId}`,"PATCH",{collection_role:"platform_deposit",settlement_eligible:true,order_total_amount_minor:1000000,actual_collected_amount_minor:300000,confirm_source_review:true});assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,200);assert.equal(db.sqlite.prepare("SELECT occurred_at FROM merchant_settlement_sources").get().occurred_at,"2026-08-31T16:00:00Z");});
test("RC3-15/16 保留中與 locked 來源不可修改",()=>{const db=new D1();seedProfile(db);seedStatement(db);const p=seedPayment(db);qualify(db,p,{reserved:"statement-1"});assert.throws(()=>db.sqlite.prepare("UPDATE merchant_settlement_sources SET actual_collected_amount_minor=1 WHERE payment_id=?").run(p.paymentId),/immutable/);db.sqlite.prepare("UPDATE merchant_settlements SET status='review' WHERE id='statement-1'").run();assert.throws(()=>db.sqlite.prepare("UPDATE merchant_settlement_sources SET collection_role='test' WHERE payment_id=?").run(p.paymentId),/immutable/);});
test("RC3-17 同一來源不可進兩張非 void 對帳單",()=>{const db=new D1();seedProfile(db);seedStatement(db);seedStatement(db,{id:"statement-2",start:"2026-09-01",end:"2026-09-30"});const p=seedPayment(db);qualify(db,p,{reserved:"statement-1"});db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,settlement_source_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES ('i1','statement-1',?,?,'deposit','payment',?,1,'2026-08-01','{}')").run(merchantId,`source-${p.paymentId}`,p.paymentId);assert.throws(()=>db.sqlite.prepare("INSERT INTO merchant_settlement_items(id,settlement_id,merchant_id,settlement_source_id,item_type,source_type,source_id,amount_minor,occurred_at,source_snapshot_json) VALUES ('i2','statement-2',?,?,'deposit','payment',?,1,'2026-09-01','{}')").run(merchantId,`source-${p.paymentId}`,p.paymentId),/reserved|active statement/);});
test("RC3-18 PDF document version 禁止修改與刪除",()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO settlement_document_versions(id,settlement_id,merchant_id,pdf_version,pdf_status,pdf_object_key,pdf_hash,created_by) VALUES ('doc','statement-1',?,1,'locked','x','h','admin')").run(merchantId);assert.throws(()=>db.sqlite.prepare("UPDATE settlement_document_versions SET pdf_hash='z' WHERE id='doc'").run(),/immutable/);assert.throws(()=>db.sqlite.prepare("DELETE FROM settlement_document_versions WHERE id='doc'").run(),/immutable/);});
test("RC3-19 同 key 不同 statement 不會錯誤衝突",()=>{const db=new D1();seedProfile(db);seedStatement(db);seedStatement(db,{id:"statement-2",start:"2026-09-01",end:"2026-09-30"});const sql="INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,operation_scope,idempotency_key,expires_at,created_by) VALUES (?,?,?,'lock',?,'same','2099-01-01','admin')";db.sqlite.prepare(sql).run("a","statement-1",merchantId,"statement-1");assert.doesNotThrow(()=>db.sqlite.prepare(sql).run("b","statement-2",merchantId,"statement-2"));});
test("RC3-20 committed operation 可安全 replay",async()=>{const db=new D1();seedProfile(db);seedStatement(db);let request=req("/settlements/statement-1/submit-review","POST",{},"same-op");assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,200);const replay=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(replay.status,200);assert.equal(replay.headers.get("idempotent-replay"),"true");});
test("RC3-21 嚴格拒絕不存在日期",()=>{for(const value of ["2026-02-30","2026-02-31","2026-13-01","2026-00-10"])assert.equal(isDate(value),false);assert.equal(isDate("2026-02-28"),true);});
test("RC3-22 來源覆核 API 回傳 409 與既有 payment_id",async()=>{const db=new D1();seedProfile(db);const first=seedPayment(db,{suffix:"api-one"});qualify(db,first);const second="payment-api-two";db.sqlite.prepare("INSERT INTO payments(id,payment_no,merchant_id,order_id,gross_amount,net_amount,amount,payment_method,status,paid_at,source) VALUES (?,?,?,?,1500,1500,1500,'card','paid','2026-08-01','webhook')").run(second,"PAY-API-TWO",merchantId,first.orderId);const request=req(`/settlement-sources/${second}`,"PATCH",{collection_role:"platform_deposit",settlement_eligible:true,order_total_amount_minor:1000000,actual_collected_amount_minor:150000,confirm_source_review:true});const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,409);assert.equal((await response.json()).existing_payment_id,first.paymentId);});
test("RC3-23 manual review Adjustment 阻止本期預覽與鎖定",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,review_status,idempotency_key,created_by) VALUES ('manual',?,'statement-1','refund',-100,'review','2026-09-01','2026-09-01','pending','manual','admin')").run(merchantId);const request=req("/settlements/preview","POST",{merchant_id:merchantId,period_start:"2026-09-01",period_end:"2026-09-30"});assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,422);});
test("RC3-24 負數對帳單可正式鎖定並保存待返還",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,idempotency_key,created_by) VALUES ('negative',?,'statement-1','refund',-280000,'跨月退款','2026-09-01','2026-09-01','negative','admin')").run(merchantId);db.sqlite.prepare("INSERT INTO platform_finance_settings(id,legal_entity_name,tax_id) VALUES ('default','測試法律主體','00000000')").run();const env={FINANCE_DB:db,CONTRACTS_BUCKET:{async put(){},async delete(){}}};let request=req("/settlements","POST",{merchant_id:merchantId,period_start:"2026-09-01",period_end:"2026-09-30"},"create-negative");let response=await handleSettlementRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"});const created=await response.json();request=req(`/settlements/${created.id}/submit-review`,"POST",{},"review-negative");assert.equal((await handleSettlementRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).status,200);request=req(`/settlements/${created.id}/lock`,"POST",{},"lock-negative");assert.equal((await handleSettlementRequest(request,env,new URL(request.url),{}, {admin_user_id:"admin"})).status,200);const row=db.sqlite.prepare("SELECT merchant_payable_minor,merchant_due_to_platform_minor,carry_forward_balance_minor FROM merchant_settlements WHERE id=?").get(created.id);assert.equal(row.merchant_payable_minor,0);assert.equal(row.merchant_due_to_platform_minor,280000);assert.equal(row.carry_forward_balance_minor,-280000);});
test("RC3-25 Worker 中斷後依 statement 狀態恢復 operation",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"review"});db.sqlite.prepare("INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,operation_scope,idempotency_key,expires_at,created_by) VALUES ('interrupted','statement-1',?,'submit-review','statement-1','recover','2099-01-01','admin')").run(merchantId);const request=req("/settlements/statement-1/submit-review","POST",{},"recover");const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,200);assert.equal(response.headers.get("idempotent-replay"),"true");assert.equal(db.sqlite.prepare("SELECT reconciliation_status FROM merchant_settlement_operations WHERE id='interrupted'").get().reconciliation_status,"reconciled");});

test("RC3.1-1 Profile、Statement、Snapshot、PDF 與 CSV 統一 settlement-v3", async()=>{const db=new D1();seedProfile(db);assert.equal(db.sqlite.prepare("SELECT calculation_version FROM merchant_settlement_profiles").get().calculation_version,"settlement-v3");const request=req("/settlements","POST",{merchant_id:merchantId,period_start:"2026-08-01",period_end:"2026-08-31"},"calc-v3");const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,201);const created=await response.json();const statement=db.sqlite.prepare("SELECT * FROM merchant_settlements WHERE id=?").get(created.id);assert.equal(statement.calculation_version,"settlement-v3");assert.equal(JSON.parse(statement.rules_snapshot_json).calculation_version,"settlement-v3");assert.match(new TextDecoder().decode(settlementCsv(statement)),/settlement-v3/);const pdf=await createSettlementPdf({...statement,merchant_name:"測試商家",generated_at:"2026-09-01T00:00:00Z"});const encoded=Array.from("settlement-v3").map((char)=>char.charCodeAt(0).toString(16).padStart(4,"0")).join("").toUpperCase();assert.match(new TextDecoder().decode(pdf.bytes),new RegExp(encoded));});

test("RC3.1-2 Offset Ledger 禁止 UPDATE 與 DELETE",()=>{const db=new D1();seedProfile(db,merchantId,"sales_offset_18000");db.sqlite.prepare("INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('ledger',?,'offset_earned',100,'2026-08-31','ledger','admin')").run(merchantId);assert.throws(()=>db.sqlite.prepare("UPDATE merchant_offset_ledger SET amount_minor=200 WHERE id='ledger'").run(),/immutable/);assert.throws(()=>db.sqlite.prepare("DELETE FROM merchant_offset_ledger WHERE id='ledger'").run(),/immutable/);});

test("RC3.1-3 抵付目標低於 Ledger 餘額回傳 409",async()=>{const db=new D1();seedProfile(db,merchantId,"sales_offset_18000");db.sqlite.prepare("INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('ledger',?,'offset_earned',50000,'2026-08-31','ledger','admin')").run(merchantId);const request=req(`/settlement-profiles/${merchantId}`,"PATCH",{...baseProfile,payment_plan:"sales_offset_18000",offset_target_amount_minor:40000});const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,409);assert.equal((await response.json()).code,"OFFSET_TARGET_BELOW_LEDGER_BALANCE");});

test("RC3.1-4 有 Ledger 時不可直接改為一次付清",async()=>{const db=new D1();seedProfile(db,merchantId,"sales_offset_18000");db.sqlite.prepare("INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('ledger',?,'offset_earned',50000,'2026-08-31','ledger','admin')").run(merchantId);const request=req(`/settlement-profiles/${merchantId}`,"PATCH",{...baseProfile,payment_plan:"upfront_18000"});const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,409);assert.equal((await response.json()).code,"PAYMENT_PLAN_SETTLEMENT_REQUIRED");});

test("RC3.1-5 Ledger 跨商家 settlement／adjustment reference 被拒絕",()=>{const db=new D1();seedProfile(db);seedProfile(db,"merchant_b","sales_offset_18000");seedStatement(db,{id:"b-statement",merchant:"merchant_b"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,idempotency_key,created_by) VALUES ('b-adjustment','merchant_b','b-statement','correction',1,'x','2026-09-01','2026-09-01','b','admin')").run();const sql="INSERT INTO merchant_offset_ledger(id,merchant_id,settlement_id,adjustment_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES (?,?,?,?, 'manual_correction',1,'2026-09-01',?,'admin')";assert.throws(()=>db.sqlite.prepare(sql).run("cross-s",merchantId,"b-statement",null,"cross-s"),/merchant mismatch/);assert.throws(()=>db.sqlite.prepare(sql).run("cross-a",merchantId,null,"b-adjustment","cross-a"),/merchant mismatch/);});

test("RC3.1-6 Pending Adjustment 可核准且重送安全 replay",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,source_statement_id,adjustment_type,deposit_reversal_minor,platform_fee_reversal_minor,offset_reversal_minor,provider_fee_reversal_minor,amount_minor,reason,effective_date,eligible_period_start,review_status,idempotency_key,created_by) VALUES ('review-me',?,'statement-1','statement-1','refund',-30000,-2000,-1500,0,-28000,'pending','2026-09-05','2026-09-05','pending','auto-review','system')").run(merchantId);const body={decision:"approved",confirmed_deposit_reversal_minor:-30000,confirmed_platform_fee_reversal_minor:-2000,confirmed_offset_reversal_minor:-1500,confirmed_provider_fee_reversal_minor:0,reason:"契約與退款資料已確認",confirm_professional_review:true};const request=req("/settlement-adjustments/review-me/review","POST",body,"review-key");let response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,200);response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.headers.get("idempotent-replay"),"true");const row=db.sqlite.prepare("SELECT review_status,amount_minor,reviewed_by FROM merchant_settlement_adjustments WHERE id='review-me'").get();assert.deepEqual([row.review_status,row.amount_minor,row.reviewed_by],["approved",-28000,"admin"]);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='merchant_settlement_adjustment_reviewed'").get().n,1);});

test("RC3.1-7 Adjustment 拒絕後不可回 pending，Provider 退費需 reference",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});const insert="INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,source_statement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,review_status,idempotency_key,created_by) VALUES (?,?, 'statement-1','statement-1','refund',-100,'pending','2026-09-05','2026-09-05','pending',?,'system')";db.sqlite.prepare(insert).run("reject-me",merchantId,"reject-auto");let request=req("/settlement-adjustments/reject-me/review","POST",{decision:"rejected",confirmed_deposit_reversal_minor:-100,confirmed_platform_fee_reversal_minor:0,confirmed_offset_reversal_minor:0,confirmed_provider_fee_reversal_minor:0,reason:"資料不足",confirm_professional_review:true},"reject-key");assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,200);assert.throws(()=>db.sqlite.prepare("UPDATE merchant_settlement_adjustments SET review_status='pending' WHERE id='reject-me'").run(),/final/);db.sqlite.prepare(insert).run("provider-me",merchantId,"provider-auto");request=req("/settlement-adjustments/provider-me/review","POST",{decision:"approved",confirmed_deposit_reversal_minor:-100,confirmed_platform_fee_reversal_minor:0,confirmed_offset_reversal_minor:0,confirmed_provider_fee_reversal_minor:30,reason:"Provider 退費",confirm_professional_review:true},"provider-key");assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,400);});

test("RC3.1-8 Adjustment 查詢支援 review_status 與月份",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked"});db.sqlite.prepare("INSERT INTO merchant_settlement_adjustments(id,merchant_id,source_settlement_id,source_statement_id,adjustment_type,amount_minor,reason,effective_date,eligible_period_start,review_status,idempotency_key,created_by) VALUES ('listed',?,'statement-1','statement-1','refund',-100,'pending','2026-09-05','2026-09-05','pending','listed','system')").run(merchantId);const request=req("/settlement-adjustments?review_status=pending&effective_month=2026-09&limit=10");const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,200);assert.equal((await response.json()).items[0].id,"listed");});

test("RC3.1-9 重疊期間與歷史普通對帳被拒絕",async()=>{const db=new D1();seedProfile(db);seedStatement(db,{status:"locked",start:"2026-08-01",end:"2026-08-31"});assert.throws(()=>seedStatement(db,{id:"overlap",start:"2026-08-15",end:"2026-09-15"}),/overlap/);const db2=new D1();seedProfile(db2);seedStatement(db2,{status:"locked",start:"2026-09-01",end:"2026-09-30"});const request=req("/settlements/preview","POST",{merchant_id:merchantId,period_start:"2026-08-01",period_end:"2026-08-31"});const response=await handleSettlementRequest(request,{FINANCE_DB:db2},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,409);assert.equal((await response.json()).code,"HISTORICAL_CORRECTION_REQUIRED");});

test("RC3.1-10 未來 Ledger 不回流過去，Void 不擋替代且連續月份可建立",async()=>{const db=new D1();seedProfile(db,merchantId,"sales_offset_18000");db.sqlite.prepare("INSERT INTO merchant_offset_ledger(id,merchant_id,entry_type,amount_minor,effective_at,idempotency_key,created_by) VALUES ('future',?,'offset_earned',50000,'2026-09-30','future','admin')").run(merchantId);let request=req("/settlements/preview","POST",{merchant_id:merchantId,period_start:"2026-08-01",period_end:"2026-08-31"});let response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal((await response.json()).preview.prior_offset_amount_minor,0);const db2=new D1();seedProfile(db2);seedStatement(db2,{status:"void"});assert.doesNotThrow(()=>seedStatement(db2,{id:"replacement"}));const db3=new D1();seedProfile(db3);seedStatement(db3,{status:"locked"});request=req("/settlements","POST",{merchant_id:merchantId,period_start:"2026-09-01",period_end:"2026-09-30"},"continuous");response=await handleSettlementRequest(request,{FINANCE_DB:db3},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,201);});

test("RC3.1-11 USD 與 Order／Payment 幣別不一致不得取得資格",async()=>{for(const currencies of [["USD","USD"],["TWD","USD"]]){const db=new D1();seedProfile(db);const payment=seedPayment(db,{suffix:currencies.join("-"),orderCurrency:currencies[0],paymentCurrency:currencies[1]});const request=req(`/settlement-sources/${payment.paymentId}`,"PATCH",{collection_role:"platform_deposit",settlement_eligible:true,order_total_amount_minor:1000000,actual_collected_amount_minor:300000,confirm_source_review:true});assert.equal((await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"})).status,422);}});

test("RC3.1-12 嚴格 decimal parser 拒絕三位小數、科學記號與超大值",()=>{assert.equal(decimalMajorToMinor("100.12"),10012);for(const value of ["100.123","1e2","NaN","Infinity","-1","9007199254740991"])assert.equal(decimalMajorToMinor(value),null);});

test("RC3.1-13 同 Statement 同 action 不同 key 不可並行",async()=>{const db=new D1();seedProfile(db);seedStatement(db);db.sqlite.prepare("INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,operation_scope,idempotency_key,expires_at,created_by) VALUES ('running','statement-1',?,'submit-review','statement-1','first','2099-01-01','admin')").run(merchantId);const request=req("/settlements/statement-1/submit-review","POST",{},"second");const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,409);assert.equal(db.sqlite.prepare("SELECT status FROM merchant_settlements WHERE id='statement-1'").get().status,"draft");});

test("RC3.1-14 過期 operation 可重新取得並完成",async()=>{const db=new D1();seedProfile(db);seedStatement(db);db.sqlite.prepare("INSERT INTO merchant_settlement_operations(id,settlement_id,merchant_id,operation_type,operation_scope,idempotency_key,expires_at,created_by) VALUES ('expired','statement-1',?,'submit-review','statement-1','retry','2000-01-01','admin')").run(merchantId);const request=req("/settlements/statement-1/submit-review","POST",{},"retry");const response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,200);assert.equal(db.sqlite.prepare("SELECT status FROM merchant_settlement_operations WHERE id='expired'").get().status,"completed");});

test("RC3.1-15 Legacy Finance 以 Asia/Taipei 月份 UTC 邊界統計",async()=>{const db=new D1();seedPayment(db,{suffix:"taipei-summary",paidAt:"2026-08-31T16:30:00.000Z"});const result=await financeSummary(db,new Date("2026-08-31T16:30:00.000Z"));assert.equal(result.payment_count,1);assert.equal(result.month_gross,3000);});
test("RC3.1-16 Migration rollback 保留既有 Finance／Partner／Admin 資料表",()=>{const db=new D1();db.sqlite.exec(readFileSync(new URL("../migrations/rollback/0010_merchant_settlements.down.sql",import.meta.url),"utf8"));for(const table of ["merchants","payments","orders","refunds","partners","admin_users"])assert.ok(db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table));for(const table of ["platform_finance_settings","merchant_settlement_profiles","merchant_settlement_sources","merchant_settlements","merchant_settlement_items","merchant_settlement_adjustments","merchant_offset_ledger","merchant_settlement_events","settlement_document_versions","merchant_settlement_operations","finance_refund_operations"])assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='table' AND name=?").get(table).n,0);});

test("RC3.1-17 Create Draft 重送先 replay，不被自身期間重疊阻擋",async()=>{const db=new D1();seedProfile(db);const makeRequest=()=>req("/settlements","POST",{merchant_id:merchantId,period_start:"2026-08-01",period_end:"2026-08-31"},"create-replay");let request=makeRequest();let response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,201);const first=await response.json();request=makeRequest();response=await handleSettlementRequest(request,{FINANCE_DB:db},new URL(request.url),{}, {admin_user_id:"admin"});assert.equal(response.status,201);assert.equal(response.headers.get("idempotent-replay"),"true");assert.equal((await response.json()).id,first.id);assert.equal(db.sqlite.prepare("SELECT COUNT(*) n FROM merchant_settlements").get().n,1);});
