import type {
  Business,
  CollaborationNeed,
  Conversation,
  Product,
  QuoteRecord,
  Review,
} from "./types";

export const categories = [
  "居家修繕",
  "工程營造",
  "水電冷氣",
  "木工鐵工",
  "設計裝潢",
  "攝影錄影",
  "影音剪輯",
  "廣告行銷",
  "網站與程式",
  "餐飲美食",
  "食品供應",
  "農漁畜牧",
  "批發零售",
  "電商服務",
  "美容美髮",
  "健康健身",
  "教育顧問",
  "法律會計",
  "婚禮活動",
  "物流運輸",
  "汽機車服務",
  "寵物服務",
  "文創手作",
  "印刷包裝",
  "清潔除蟲",
  "其他專業服務",
];

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const businesses: Business[] = [
  {
    id: 1,
    slug: "qiang-ge-aquarium",
    name: "強哥水族",
    shortName: "強水",
    category: "其他專業服務",
    location: "台北市",
    district: "中正區",
    serviceMode: ["到府服務", "實體店面"],
    rating: 5,
    reviewCount: 128,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#116b5d",
    cover: `${import.meta.env.BASE_URL}assets/business-aquarium-cover.jpg`,
    tagline: "專業水族造景・水族工程設計與維護",
    intro:
      "強哥水族成立於 2016 年，專注於商業與居家水族造景、水族工程設計與定期維護。從空間評估、缸體規劃、魚種搭配到後續保養，提供一站式服務。",
    services: ["客製化水族造景設計", "大型水族工程規劃施工", "定期維護與保養", "水族設備銷售與升級"],
    products: ["客製生態缸", "企業水族牆", "水質檢測保養"],
    priceRange: "NT$ 3,000－300,000",
    years: 8,
    completed: 350,
    responseRate: 98,
    responseTime: "30 分鐘內",
    joinedAt: "2021 年 3 月",
    lastOnline: "5 分鐘前",
    phone: "0912-345-678",
    email: "service@qiangge-aqua.tw",
    line: "@qiangge",
    address: "台北市中正區重慶南路一段 123 號",
    hours: "週一至週日 10:00－20:00",
    certificates: ["水族景觀規劃證書", "商業登記認證", "環境用藥安全訓練"],
    partners: ["森森設備", "藍海水族", "原生水草"],
  },
  {
    id: 2,
    slug: "a-cheng-electric",
    name: "阿誠水電工程",
    shortName: "誠電",
    category: "水電冷氣",
    location: "新北市",
    district: "板橋區",
    serviceMode: ["到府服務", "緊急支援"],
    rating: 4.9,
    reviewCount: 160,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#d97706",
    cover: image("photo-1621905251918-48416bd8575a"),
    tagline: "水電維修・裝潢配線・衛浴安裝",
    intro:
      "超過十二年住宅與商用水電經驗，提供透明報價、現場照片紀錄與完工保固。從一盞燈到整層辦公室配線，都用同樣標準完成。",
    services: ["住宅水電維修", "商空配線工程", "衛浴設備安裝", "緊急漏水處理"],
    products: ["全屋健檢", "電箱更新", "衛浴安裝包"],
    priceRange: "NT$ 800－180,000",
    years: 12,
    completed: 680,
    responseRate: 96,
    responseTime: "20 分鐘內",
    joinedAt: "2020 年 8 月",
    lastOnline: "剛剛",
    phone: "0922-118-520",
    email: "hello@acheng-elec.tw",
    line: "@acheng520",
    address: "新北市板橋區文化路二段 88 號",
    hours: "週一至週六 08:30－19:00",
    certificates: ["室內配線技術士", "自來水管承裝認證"],
    partners: ["國際牌", "和成衛浴"],
  },
  {
    id: 3,
    slug: "wooday-studio",
    name: "木日木工工作室",
    shortName: "木日",
    category: "木工鐵工",
    location: "台中市",
    district: "西屯區",
    serviceMode: ["到府丈量", "工作室"],
    rating: 4.8,
    reviewCount: 53,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#8b5e3c",
    cover: image("photo-1452860606245-08befc0ff44b"),
    tagline: "客製化木作・系統家具・室內裝修",
    intro:
      "木日相信好家具應該陪伴生活很久。我們從選材、打樣到安裝皆由固定團隊完成，擅長小宅收納、品牌陳列與實木訂製。",
    services: ["實木家具訂製", "小宅收納規劃", "店面陳列木作", "老家具修復"],
    products: ["實木餐桌", "模組層架", "品牌展示櫃"],
    priceRange: "NT$ 8,000－500,000",
    years: 9,
    completed: 214,
    responseRate: 92,
    responseTime: "2 小時內",
    joinedAt: "2022 年 1 月",
    lastOnline: "1 小時前",
    phone: "04-2451-7788",
    email: "hi@wooday.tw",
    line: "@wooday",
    address: "台中市西屯區福星路 18 巷 5 號",
    hours: "週二至週六 10:00－18:30",
    certificates: ["建築物室內裝修技術士", "FSC 選材合作證明"],
    partners: ["台灣檜木", "島嶼設計"],
  },
  {
    id: 4,
    slug: "daily-sweet",
    name: "日日甜點",
    shortName: "日日",
    category: "餐飲美食",
    location: "台北市",
    district: "中山區",
    serviceMode: ["門市取貨", "宅配服務"],
    rating: 4.9,
    reviewCount: 142,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#e45b6b",
    cover: image("photo-1578985545062-69928b1d9587"),
    tagline: "手作甜點・客製蛋糕・午後茶點心",
    intro:
      "日日甜點以當季水果與台灣食材製作少甜、耐吃的日常甜點，提供企業茶會、婚禮小物與品牌聯名客製。",
    services: ["客製生日蛋糕", "企業茶會點心", "婚禮小物", "品牌聯名開發"],
    products: ["季節水果塔", "鐵盒餅乾", "企業茶點盒"],
    priceRange: "NT$ 120－50,000",
    years: 6,
    completed: 460,
    responseRate: 97,
    responseTime: "1 小時內",
    joinedAt: "2021 年 9 月",
    lastOnline: "20 分鐘前",
    phone: "02-2571-0909",
    email: "order@dailysweet.tw",
    line: "@dailysweet",
    address: "台北市中山區赤峰街 21 號",
    hours: "週三至週日 12:00－19:00",
    certificates: ["食品業者登錄", "HACCP 基礎訓練"],
    partners: ["富田農產", "拾光婚禮"],
  },
  {
    id: 5,
    slug: "swift-air",
    name: "迅捷冷氣工程",
    shortName: "迅捷",
    category: "水電冷氣",
    location: "桃園市",
    district: "中壢區",
    serviceMode: ["到府服務", "企業維護"],
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#1584c4",
    cover: image("photo-1581092160562-40aa08e78837"),
    tagline: "空調安裝・清洗保養・商用維護",
    intro: "服務北北桃的冷氣安裝與保養團隊，重視準時、保護施工與完工清潔，企業客戶可簽年度巡檢合約。",
    services: ["分離式冷氣安裝", "冷氣深層清洗", "商用空調維護", "故障檢修"],
    products: ["居家清洗方案", "年度保養合約", "商用空調規劃"],
    priceRange: "NT$ 1,800－800,000",
    years: 10,
    completed: 920,
    responseRate: 95,
    responseTime: "40 分鐘內",
    joinedAt: "2020 年 5 月",
    lastOnline: "15 分鐘前",
    phone: "03-425-0098",
    email: "service@swift-air.tw",
    line: "@swiftair",
    address: "桃園市中壢區環北路 101 號",
    hours: "週一至週六 08:00－19:30",
    certificates: ["冷凍空調裝修技術士", "商業登記認證"],
    partners: ["大金空調", "日立冷氣"],
  },
  {
    id: 6,
    slug: "lightframe-photo",
    name: "光影攝影工作室",
    shortName: "光影",
    category: "攝影錄影",
    location: "台北市",
    district: "大安區",
    serviceMode: ["到場拍攝", "攝影棚"],
    rating: 4.8,
    reviewCount: 76,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#4338ca",
    cover: image("photo-1452780212940-6f5c0d14d848"),
    tagline: "品牌影像・商品攝影・人物肖像",
    intro: "擅長把品牌故事轉化為有溫度的照片與短影音，從前期企劃、場景陳設到後期修圖完整執行。",
    services: ["商品形象攝影", "企業人物肖像", "活動紀錄", "短影音拍攝"],
    products: ["電商白背照", "品牌形象日", "活動半日紀錄"],
    priceRange: "NT$ 6,000－180,000",
    years: 7,
    completed: 310,
    responseRate: 94,
    responseTime: "2 小時內",
    joinedAt: "2021 年 11 月",
    lastOnline: "2 小時前",
    phone: "02-2700-8612",
    email: "studio@lightframe.tw",
    line: "@lightframe",
    address: "台北市大安區信義路三段 16 巷 8 號",
    hours: "預約制 09:00－21:00",
    certificates: ["Adobe Certified Professional", "空拍機操作證"],
    partners: ["島嶼品牌設計", "日日甜點"],
  },
  {
    id: 7,
    slug: "goodfood-supply",
    name: "好食食品供應",
    shortName: "好食",
    category: "食品供應",
    location: "新北市",
    district: "三重區",
    serviceMode: ["全台配送", "企業供應"],
    rating: 4.7,
    reviewCount: 64,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#b45309",
    cover: image("photo-1542838132-92c53300491e"),
    tagline: "餐飲原料・冷凍食材・穩定供貨",
    intro: "服務中小型餐廳、咖啡店與團膳業者，提供透明產地、彈性起訂量與定期配送。",
    services: ["餐飲原料批發", "冷凍食材配送", "客製規格分裝", "新品共同開發"],
    products: ["冷凍莓果", "烘焙原料箱", "餐飲調味組"],
    priceRange: "NT$ 1,500－500,000",
    years: 11,
    completed: 740,
    responseRate: 93,
    responseTime: "1 小時內",
    joinedAt: "2019 年 12 月",
    lastOnline: "30 分鐘前",
    phone: "02-2981-7760",
    email: "sales@goodfood.tw",
    line: "@goodfoodb2b",
    address: "新北市三重區重新路五段 609 巷 12 號",
    hours: "週一至週五 08:30－18:00",
    certificates: ["食品業者登錄", "低溫物流稽核"],
    partners: ["富田農產", "山海水產"],
  },
  {
    id: 8,
    slug: "island-brand",
    name: "島嶼品牌設計",
    shortName: "島嶼",
    category: "設計裝潢",
    location: "台北市",
    district: "松山區",
    serviceMode: ["線上服務", "到店會議"],
    rating: 4.9,
    reviewCount: 48,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#0f766e",
    cover: image("photo-1545235617-9465d2a55698"),
    tagline: "品牌策略・視覺識別・包裝整合",
    intro: "協助地方品牌與新創企業把價值說清楚、做一致，從品牌定位到識別與包裝落地。",
    services: ["品牌定位策略", "Logo 與視覺識別", "包裝設計", "品牌網站企劃"],
    products: ["品牌健檢", "識別設計專案", "包裝系列設計"],
    priceRange: "NT$ 18,000－600,000",
    years: 8,
    completed: 126,
    responseRate: 91,
    responseTime: "3 小時內",
    joinedAt: "2020 年 6 月",
    lastOnline: "1 小時前",
    phone: "02-2766-8018",
    email: "hello@islandbrand.tw",
    line: "@islandbrand",
    address: "台北市松山區民生東路五段 55 號",
    hours: "週一至週五 10:00－18:30",
    certificates: ["經濟部設計服務能量登錄", "商業登記認證"],
    partners: ["光影攝影", "日新印刷"],
  },
  {
    id: 9,
    slug: "safehome-clean",
    name: "安心居家清潔",
    shortName: "安心",
    category: "清潔除蟲",
    location: "新竹市",
    district: "東區",
    serviceMode: ["到府服務", "定期方案"],
    rating: 4.8,
    reviewCount: 112,
    verified: true,
    invoice: true,
    enterprise: false,
    recommended: true,
    accent: "#059669",
    cover: image("photo-1581578731548-c64695cc6952"),
    tagline: "居家清潔・退租整理・定期維護",
    intro: "固定清潔師配對與標準化檢核，服務前確認重點、完工後照片回報，讓忙碌家庭放心把家交給我們。",
    services: ["鐘點居家清潔", "空屋退租清潔", "裝潢後細清", "辦公室定期清潔"],
    products: ["四小時清潔", "搬家細清", "企業月方案"],
    priceRange: "NT$ 1,800－60,000",
    years: 5,
    completed: 860,
    responseRate: 99,
    responseTime: "15 分鐘內",
    joinedAt: "2022 年 4 月",
    lastOnline: "剛剛",
    phone: "03-577-1314",
    email: "care@safehome-clean.tw",
    line: "@safehome",
    address: "新竹市東區光復路一段 180 號",
    hours: "每日 08:00－20:00",
    certificates: ["清潔服務人員訓練", "環保清潔劑使用認證"],
    partners: ["一品室內裝修"],
  },
  {
    id: 10,
    slug: "futian-farm",
    name: "富田農產",
    shortName: "富田",
    category: "農漁畜牧",
    location: "雲林縣",
    district: "西螺鎮",
    serviceMode: ["產地直送", "批發合作"],
    rating: 4.8,
    reviewCount: 38,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#3f7d20",
    cover: image("photo-1500382017468-9049fed747ef"),
    tagline: "產地蔬果・契作供應・冷鏈直送",
    intro: "串聯雲林在地小農，按規格分級包裝並提供餐廳、加工廠與通路穩定契作供應。",
    services: ["蔬果批發", "契作栽培", "規格分級包裝", "冷鏈配送"],
    products: ["產地時蔬箱", "餐飲大宗蔬果", "加工規格品"],
    priceRange: "NT$ 2,000－1,200,000",
    years: 14,
    completed: 530,
    responseRate: 90,
    responseTime: "4 小時內",
    joinedAt: "2020 年 10 月",
    lastOnline: "今天 08:12",
    phone: "05-586-7721",
    email: "order@futian-farm.tw",
    line: "@futianfarm",
    address: "雲林縣西螺鎮新豐里 28 號",
    hours: "週一至週六 06:00－17:00",
    certificates: ["產銷履歷", "農產品初級加工場登記"],
    partners: ["好食食品", "全通物流"],
  },
  {
    id: 11,
    slug: "pet-daily-grooming",
    name: "毛孩日常寵物美容",
    shortName: "毛日",
    category: "寵物服務",
    location: "台南市",
    district: "東區",
    serviceMode: ["實體店面", "預約服務"],
    rating: 4.9,
    reviewCount: 95,
    verified: true,
    invoice: false,
    enterprise: false,
    recommended: true,
    accent: "#a855f7",
    cover: image("photo-1516734212186-a967f81ad0d7"),
    tagline: "犬貓美容・溫柔洗護・造型修剪",
    intro: "採一對一預約與低壓洗護流程，重視毛孩情緒與皮膚狀況，家長可收到完整美容紀錄。",
    services: ["犬貓基礎洗護", "造型修剪", "皮膚照護浴", "老犬友善服務"],
    products: ["基礎洗護", "全套美容", "月保養方案"],
    priceRange: "NT$ 650－4,500",
    years: 6,
    completed: 1200,
    responseRate: 98,
    responseTime: "25 分鐘內",
    joinedAt: "2021 年 7 月",
    lastOnline: "10 分鐘前",
    phone: "06-268-7716",
    email: "hi@petdaily.tw",
    line: "@petdaily",
    address: "台南市東區崇善路 76 號",
    hours: "週二至週日 10:00－19:30",
    certificates: ["KCT 寵物美容師", "寵物急救訓練"],
    partners: ["毛森選物"],
  },
  {
    id: 12,
    slug: "time-wedding",
    name: "拾光婚禮企劃",
    shortName: "拾光",
    category: "婚禮活動",
    location: "高雄市",
    district: "鼓山區",
    serviceMode: ["到場服務", "線上諮詢"],
    rating: 4.9,
    reviewCount: 71,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#be6a7c",
    cover: image("photo-1519741497674-611481863552"),
    tagline: "婚禮統籌・品牌活動・場地佈置",
    intro: "從概念、流程到現場執行，讓每場婚禮與活動都保有主角的個性，也讓合作團隊工作順暢。",
    services: ["婚禮全程統籌", "證婚儀式", "企業活動", "花藝與場佈"],
    products: ["婚禮顧問", "小型證婚", "品牌發表會"],
    priceRange: "NT$ 35,000－500,000",
    years: 8,
    completed: 168,
    responseRate: 96,
    responseTime: "1 小時內",
    joinedAt: "2020 年 2 月",
    lastOnline: "35 分鐘前",
    phone: "07-522-1138",
    email: "hello@timewedding.tw",
    line: "@timewedding",
    address: "高雄市鼓山區美術東二路 39 號",
    hours: "週一至週六 10:00－19:00",
    certificates: ["婚禮顧問培訓認證", "活動安全管理訓練"],
    partners: ["光影攝影", "日日甜點"],
  },
  {
    id: 13,
    slug: "dongsheng-metal",
    name: "東盛鐵工",
    shortName: "東盛",
    category: "木工鐵工",
    location: "彰化縣",
    district: "和美鎮",
    serviceMode: ["到府丈量", "工廠製作"],
    rating: 4.7,
    reviewCount: 44,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#475569",
    cover: image("photo-1531058020387-3be344556be6"),
    tagline: "金屬加工・鐵件工程・客製製作",
    intro: "兩代鐵工團隊，承作住宅欄杆、店面鐵件與工廠設備架，提供丈量、製圖、製作與安裝。",
    services: ["建築鐵件", "不鏽鋼加工", "設備架製作", "鐵件修繕"],
    products: ["客製欄杆", "店面招牌架", "設備推車"],
    priceRange: "NT$ 5,000－1,000,000",
    years: 22,
    completed: 790,
    responseRate: 89,
    responseTime: "半天內",
    joinedAt: "2019 年 7 月",
    lastOnline: "昨天",
    phone: "04-755-8090",
    email: "work@dongsheng-metal.tw",
    line: "@dongsheng",
    address: "彰化縣和美鎮彰美路四段 210 號",
    hours: "週一至週六 08:00－17:30",
    certificates: ["氬氣鎢極電銲技術士", "工廠登記"],
    partners: ["一品室內裝修"],
  },
  {
    id: 14,
    slug: "morning-hair",
    name: "沐晨美髮",
    shortName: "沐晨",
    category: "美容美髮",
    location: "台中市",
    district: "北區",
    serviceMode: ["實體店面", "預約服務"],
    rating: 4.8,
    reviewCount: 132,
    verified: true,
    invoice: false,
    enterprise: false,
    recommended: true,
    accent: "#9f5f80",
    cover: image("photo-1560066984-138dadb4c035"),
    tagline: "質感染髮・頭皮養護・日常造型",
    intro: "以好整理、適合日常為設計核心，服務前充分溝通髮況與維護習慣，提供透明價格與居家建議。",
    services: ["剪髮造型", "質感染髮", "燙髮設計", "頭皮養護"],
    products: ["設計師剪髮", "染護套餐", "頭皮月方案"],
    priceRange: "NT$ 700－8,800",
    years: 7,
    completed: 1450,
    responseRate: 97,
    responseTime: "30 分鐘內",
    joinedAt: "2021 年 5 月",
    lastOnline: "12 分鐘前",
    phone: "04-2236-2018",
    email: "book@morninghair.tw",
    line: "@morninghair",
    address: "台中市北區太原路二段 60 號",
    hours: "週二至週日 11:00－20:00",
    certificates: ["美容美髮技術士", "頭皮管理師認證"],
    partners: ["光影攝影"],
  },
  {
    id: 15,
    slug: "maker-web",
    name: "創客網站工作室",
    shortName: "創客",
    category: "網站與程式",
    location: "台北市",
    district: "信義區",
    serviceMode: ["線上服務", "到店會議"],
    rating: 4.9,
    reviewCount: 58,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#6d28d9",
    cover: image("photo-1498050108023-c5249f4df085"),
    tagline: "品牌網站・電商開發・系統整合",
    intro: "專為中小企業打造清楚、好管理、能帶來詢問的網站，從需求梳理、設計到上線與維護一站完成。",
    services: ["企業形象網站", "電商網站", "後台系統", "網站維護與優化"],
    products: ["品牌官網方案", "電商啟動包", "月維護方案"],
    priceRange: "NT$ 48,000－1,500,000",
    years: 9,
    completed: 188,
    responseRate: 93,
    responseTime: "2 小時內",
    joinedAt: "2019 年 9 月",
    lastOnline: "25 分鐘前",
    phone: "02-2722-5518",
    email: "hello@makerweb.tw",
    line: "@makerweb",
    address: "台北市信義區基隆路一段 180 號",
    hours: "週一至週五 09:30－18:30",
    certificates: ["Google UX Design", "AWS Partner 基礎認證"],
    partners: ["島嶼品牌設計", "日新印刷"],
  },
  {
    id: 16,
    slug: "allway-logistics",
    name: "全通物流",
    shortName: "全通",
    category: "物流運輸",
    location: "桃園市",
    district: "蘆竹區",
    serviceMode: ["全台配送", "企業合約"],
    rating: 4.7,
    reviewCount: 86,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#1d4ed8",
    cover: image("photo-1586528116311-ad8dd3c8310d"),
    tagline: "企業配送・倉儲理貨・冷鏈運輸",
    intro: "提供北中南幹線、末端配送與彈性倉儲，專人對接出貨異常，適合成長中的食品與電商品牌。",
    services: ["企業配送", "倉儲理貨", "低溫冷鏈", "大型設備運輸"],
    products: ["常溫配送合約", "冷鏈月方案", "電商倉配"],
    priceRange: "NT$ 3,000－2,000,000",
    years: 15,
    completed: 2300,
    responseRate: 94,
    responseTime: "1 小時內",
    joinedAt: "2019 年 5 月",
    lastOnline: "8 分鐘前",
    phone: "03-322-6618",
    email: "dispatch@allway.tw",
    line: "@allwaylogi",
    address: "桃園市蘆竹區南山路二段 120 號",
    hours: "全年無休 07:00－22:00",
    certificates: ["汽車運輸業登記", "低溫物流管理認證"],
    partners: ["富田農產", "山海水產"],
  },
  {
    id: 17,
    slug: "joylearn-class",
    name: "樂學才藝教室",
    shortName: "樂學",
    category: "教育顧問",
    location: "新北市",
    district: "永和區",
    serviceMode: ["實體課程", "線上課程"],
    rating: 4.9,
    reviewCount: 103,
    verified: true,
    invoice: false,
    enterprise: false,
    recommended: true,
    accent: "#f59e0b",
    cover: image("photo-1509062522246-3755977927d7"),
    tagline: "兒童美術・創意手作・小班教學",
    intro: "以探索與表達為核心的小班才藝教室，依年齡設計課程，家長每堂都能收到學習紀錄。",
    services: ["兒童美術", "創意手作", "寒暑假營隊", "校園合作課程"],
    products: ["四堂體驗班", "學期課程", "企業親子活動"],
    priceRange: "NT$ 650－80,000",
    years: 8,
    completed: 970,
    responseRate: 98,
    responseTime: "20 分鐘內",
    joinedAt: "2020 年 3 月",
    lastOnline: "15 分鐘前",
    phone: "02-2922-8786",
    email: "class@joylearn.tw",
    line: "@joylearn",
    address: "新北市永和區中正路 410 號 2 樓",
    hours: "週二至週日 10:00－20:00",
    certificates: ["兒童藝術師資認證", "兒童安全急救訓練"],
    partners: ["島嶼品牌設計"],
  },
  {
    id: 18,
    slug: "mountain-sea-fish",
    name: "山海水產",
    shortName: "山海",
    category: "農漁畜牧",
    location: "屏東縣",
    district: "東港鎮",
    serviceMode: ["產地直送", "批發合作"],
    rating: 4.8,
    reviewCount: 61,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#0284c7",
    cover: image("photo-1535591273668-578e31182c4f"),
    tagline: "當日水產・餐飲批發・規格處理",
    intro: "每日東港產地採購，提供餐廳規格分切、急速冷凍與低溫宅配，批次皆可追溯。",
    services: ["鮮魚批發", "規格分切", "急速冷凍", "餐廳定期供應"],
    products: ["當日鮮魚箱", "生食級水產", "餐飲規格包"],
    priceRange: "NT$ 2,500－800,000",
    years: 13,
    completed: 880,
    responseRate: 91,
    responseTime: "2 小時內",
    joinedAt: "2019 年 11 月",
    lastOnline: "今天 06:30",
    phone: "08-833-1028",
    email: "sales@mountainsea.tw",
    line: "@mountainsea",
    address: "屏東縣東港鎮新生一路 99 號",
    hours: "週一至週六 05:00－16:00",
    certificates: ["水產品追溯", "HACCP 管理訓練"],
    partners: ["好食食品", "全通物流"],
  },
  {
    id: 19,
    slug: "yipin-interior",
    name: "一品室內裝修",
    shortName: "一品",
    category: "設計裝潢",
    location: "台中市",
    district: "南屯區",
    serviceMode: ["到府丈量", "企業合作"],
    rating: 4.8,
    reviewCount: 67,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: true,
    accent: "#334155",
    cover: image("photo-1600566753190-17f0baa2a6c3"),
    tagline: "住宅設計・商業空間・工程管理",
    intro: "重視預算透明與施工品質的設計工程團隊，提供完整圖說、進度回報與第三方驗收協作。",
    services: ["住宅空間設計", "店面辦公室設計", "老屋翻新", "工程管理"],
    products: ["空間健檢", "全案設計", "設計施工統包"],
    priceRange: "NT$ 60,000－6,000,000",
    years: 12,
    completed: 146,
    responseRate: 90,
    responseTime: "3 小時內",
    joinedAt: "2019 年 4 月",
    lastOnline: "50 分鐘前",
    phone: "04-2251-3920",
    email: "hello@yipin-interior.tw",
    line: "@yipinspace",
    address: "台中市南屯區大墩十一街 128 號",
    hours: "週一至週五 09:30－18:30",
    certificates: ["建築物室內裝修業登記", "室內設計技術士"],
    partners: ["木日木工", "東盛鐵工"],
  },
  {
    id: 20,
    slug: "renew-print",
    name: "日新印刷包裝",
    shortName: "日新",
    category: "印刷包裝",
    location: "新北市",
    district: "中和區",
    serviceMode: ["全台配送", "企業打樣"],
    rating: 4.7,
    reviewCount: 55,
    verified: true,
    invoice: true,
    enterprise: true,
    recommended: false,
    accent: "#db2777",
    cover: image("photo-1562813733-b31f71025d54"),
    tagline: "品牌印刷・包裝打樣・小量製作",
    intro: "協助品牌把設計穩定轉化為成品，提供紙材建議、色彩校正、包裝打樣與少量彈性製作。",
    services: ["商業印刷", "彩盒與包裝", "貼紙標籤", "少量數位打樣"],
    products: ["品牌名片", "食品包裝盒", "防水貼紙"],
    priceRange: "NT$ 1,200－800,000",
    years: 18,
    completed: 1800,
    responseRate: 95,
    responseTime: "1 小時內",
    joinedAt: "2019 年 6 月",
    lastOnline: "18 分鐘前",
    phone: "02-2222-0918",
    email: "quote@renewprint.tw",
    line: "@renewprint",
    address: "新北市中和區建一路 168 號",
    hours: "週一至週五 08:30－18:00",
    certificates: ["FSC 紙材供應鏈認證", "印刷色彩管理訓練"],
    partners: ["島嶼品牌設計", "日日甜點"],
  },
];

const needSeeds = [
  ["尋找長期穩定的食品原料供應商", "尋找供應商", "食品供應", "NT$ 50,000－200,000", "台北市"],
  ["尋找專業室內設計師合作新案", "異業合作", "設計裝潢", "NT$ 200,000－1,000,000", "新北市"],
  ["電商品牌徵求成長行銷團隊", "尋找設計或行銷", "廣告行銷", "NT$ 100,000－300,000", "全台"],
  ["品牌官網改版與會員系統開發", "專案外包", "網站與程式", "NT$ 80,000－250,000", "台中市"],
  ["連鎖餐飲尋找冷鏈配送夥伴", "通路合作", "物流運輸", "NT$ 300,000－800,000", "北部"],
  ["活動急徵兩日攝影錄影團隊", "短期支援", "攝影錄影", "NT$ 30,000－60,000", "高雄市"],
  ["旅宿業尋找備品批發供應商", "批發合作", "批發零售", "NT$ 100,000－500,000", "花蓮縣"],
  ["新門市徵求招牌與鐵件製作", "尋找承包商", "木工鐵工", "NT$ 60,000－150,000", "台南市"],
  ["企業家庭日尋找親子課程團隊", "活動合作", "教育顧問", "NT$ 80,000－180,000", "新竹市"],
  ["烘焙品牌採購台灣當季水果", "商品採購", "農漁畜牧", "NT$ 50,000－120,000", "全台"],
  ["商辦空調年度保養招標", "尋找承包商", "水電冷氣", "NT$ 150,000－400,000", "台北市"],
  ["婚禮場地尋找甜點合作品牌", "異業合作", "餐飲美食", "NT$ 30,000－100,000", "台中市"],
  ["寵物品牌尋找包裝設計與印刷", "專案外包", "印刷包裝", "NT$ 70,000－160,000", "全台"],
  ["食品工廠徵短期設備維修技師", "尋找技術人員", "工程營造", "NT$ 20,000－50,000", "彰化縣"],
  ["共享工作室招募駐點品牌顧問", "長期合作夥伴", "教育顧問", "NT$ 40,000－90,000", "台北市"],
  ["電商旺季尋找臨時倉儲空間", "場地合作", "物流運輸", "NT$ 60,000－180,000", "桃園市"],
  ["社區大樓徵清潔與病媒防治", "尋找承包商", "清潔除蟲", "NT$ 180,000－360,000", "新北市"],
  ["外銷品牌徵英文商品影片剪輯", "專案外包", "影音剪輯", "NT$ 35,000－85,000", "線上"],
  ["建設公司尋找固定水電協力商", "長期合作夥伴", "水電冷氣", "NT$ 500,000－2,000,000", "北部"],
  ["地方創生市集招募特色攤商", "活動合作", "文創手作", "NT$ 5,000－30,000", "宜蘭縣"],
] as const;

export const collaborationNeeds: CollaborationNeed[] = needSeeds.map((item, index) => ({
  id: index + 1,
  title: item[0],
  type: item[1],
  category: item[2],
  budget: item[3],
  location: item[4],
  deadline: `2026/0${8 + (index % 2)}/${String(6 + index).padStart(2, "0")}`,
  description:
    "希望找到重視溝通、交付品質與長期合作的夥伴。請提供公司／個人介紹、相關案例、初步時程與報價方式，合適者將安排線上會議進一步確認。",
  requirements: ["具相關合作案例", "可提供正式報價", "回覆時請附預計時程"],
  publisher: businesses[(index + 3) % businesses.length].name,
  publisherId: businesses[(index + 3) % businesses.length].id,
  proposals: 4 + ((index * 7) % 24),
  urgent: index === 5 || index === 13,
  createdAt: `${1 + (index % 6)} 小時前`,
}));

const productSeeds = [
  ["客製生態水族缸", "客製化服務", "其他專業服務", 68000],
  ["居家水電安全健檢", "專業服務", "水電冷氣", 2500],
  ["實木模組層架", "實體商品", "文創手作", 12800],
  ["企業午茶點心盒", "批發商品", "餐飲美食", 480],
  ["分離式冷氣深層清洗", "專業服務", "水電冷氣", 2200],
  ["電商商品攝影方案", "專業服務", "攝影錄影", 12000],
  ["烘焙原料綜合箱", "原物料", "食品供應", 3600],
  ["品牌定位工作坊", "顧問服務", "廣告行銷", 18000],
  ["四小時居家清潔", "專業服務", "清潔除蟲", 1900],
  ["產地時蔬批發箱", "批發商品", "農漁畜牧", 2200],
  ["犬貓基礎洗護", "專業服務", "寵物服務", 850],
  ["小型證婚企劃", "客製化服務", "婚禮活動", 68000],
  ["不鏽鋼客製展示架", "設備租借", "木工鐵工", 35000],
  ["質感染護套餐", "專業服務", "美容美髮", 4200],
  ["中小企業品牌官網", "線上服務", "網站與程式", 88000],
  ["常溫企業配送月約", "專業服務", "物流運輸", 32000],
  ["兒童創意美術四堂班", "線上服務", "教育顧問", 2800],
  ["東港當日鮮魚箱", "實體商品", "農漁畜牧", 3200],
  ["住宅空間設計提案", "顧問服務", "設計裝潢", 80000],
  ["食品品牌包裝盒彩印", "客製化服務", "印刷包裝", 16000],
  ["商用空調年度保養", "專業服務", "水電冷氣", 56000],
  ["品牌形象短影音", "線上服務", "影音剪輯", 26000],
  ["電商防水貼紙 1,000 張", "批發商品", "印刷包裝", 6800],
  ["餐飲用冷凍莓果 10kg", "原物料", "食品供應", 2400],
  ["企業人物形象攝影", "專業服務", "攝影錄影", 36000],
  ["小宅收納櫃訂製", "客製化服務", "木工鐵工", 68000],
  ["品牌 Logo 與識別系統", "顧問服務", "廣告行銷", 120000],
  ["辦公室定期清潔月約", "專業服務", "清潔除蟲", 18000],
  ["電商倉儲理貨方案", "專業服務", "物流運輸", 45000],
  ["企業親子手作活動", "客製化服務", "教育顧問", 38000],
] as const;

export const products: Product[] = productSeeds.map((seed, index) => {
  const business = businesses[index % businesses.length];
  return {
    id: index + 1,
    slug: `service-${index + 1}`,
    name: seed[0],
    type: seed[1],
    category: seed[2],
    price: seed[3],
    wholesalePrice: Math.round(seed[3] * 0.86),
    moq: seed[1] === "批發商品" || seed[1] === "原物料" ? 10 : 1,
    image: business.cover,
    businessId: business.id,
    description: `${business.name} 提供的${seed[0]}，包含需求確認、規格建議與交付後說明。企業大量採購可另行報價。`,
    specs: ["正式報價單", "可開立發票", "交期依需求確認"],
    rating: Number((4.6 + ((index * 3) % 4) / 10).toFixed(1)),
    reviewCount: 12 + ((index * 11) % 96),
  };
});

const reviewCopy = [
  "回覆很快，說明也很清楚，報價透明，合作過程比預期順利。",
  "很懂我們真正的需求，提出的細節都有替品牌多想一步。",
  "準時完成，現場也收得很乾淨，下次有案子會再合作。",
  "從第一次詢問到交付都有人追進度，適合企業長期合作。",
  "作品品質穩定，遇到臨時調整也能快速提出解法。",
  "溝通務實、不過度承諾，最後成品與一開始確認的一致。",
];
const reviewerNames = ["林小姐", "陳先生", "許店長", "王經理", "楊老師", "黃小姐", "郭主理人", "蔡先生"];

export const reviews: Review[] = Array.from({ length: 30 }, (_, index) => ({
  id: index + 1,
  businessId: (index % businesses.length) + 1,
  author: reviewerNames[index % reviewerNames.length],
  rating: index % 9 === 0 ? 4 : 5,
  content: reviewCopy[index % reviewCopy.length],
  date: `2026/07/${String(28 - (index % 25)).padStart(2, "0")}`,
  project: businesses[index % businesses.length].services[index % 3],
}));

export const conversations: Conversation[] = Array.from({ length: 10 }, (_, index) => {
  const business = businesses[(index + 1) % businesses.length];
  return {
    id: index + 1,
    businessId: business.id,
    name: business.name,
    preview: index % 2 ? "收到，我們整理報價後今天回覆您。" : "想了解這個方案是否能配合企業採購？",
    time: index < 3 ? `${9 + index}:2${index}` : `7/${28 - index}`,
    unread: index < 3 ? 1 + index : 0,
    messages: [
      {
        id: 1,
        from: "them",
        text: `您好，我們正在評估「${business.services[0]}」，想先了解合作方式。`,
        time: "09:12",
        read: true,
      },
      {
        id: 2,
        from: "me",
        text: "您好，謝謝聯絡！方便告訴我預計數量、地點與希望完成時間嗎？",
        time: "09:18",
        read: true,
      },
      {
        id: 3,
        from: "them",
        text: "可以，初步需求已整理在卡片中，麻煩協助評估。",
        time: "09:22",
        read: index >= 3,
        card: {
          type: index % 3 === 0 ? "need" : index % 3 === 1 ? "quote" : "product",
          title: index % 3 === 0 ? "品牌合作需求" : index % 3 === 1 ? "初步報價需求" : business.products[0],
          meta: index % 3 === 1 ? "預算 NT$ 50,000－100,000" : "希望 8 月底前完成",
        },
      },
    ],
  };
});

export const quoteRecords: QuoteRecord[] = Array.from({ length: 8 }, (_, index) => ({
  id: `BQ-2607-${String(index + 1).padStart(3, "0")}`,
  kind: index % 2 ? "報價" : "詢價",
  customer: businesses[(index + 4) % businesses.length].name,
  subject: products[index + 1].name,
  amount: `NT$ ${(18000 + index * 12500).toLocaleString("zh-TW")}`,
  status: (["待回覆", "議價中", "已接受", "已完成"] as const)[index % 4],
  date: `2026/07/${String(28 - index).padStart(2, "0")}`,
}));

export const platformStats = [
  { label: "活躍商家", value: "12,800+" },
  { label: "行業分類", value: "26" },
  { label: "合作媒合", value: "18,600+" },
  { label: "平均回覆率", value: "92%" },
];

export const faqs = [
  {
    q: "免費會員可以使用哪些功能？",
    a: "免費會員是純消費者購物帳號，可免費註冊、瀏覽商城、查看商品、使用購物車並完成結帳。",
  },
  {
    q: "商家如何建立商家頁與網站？",
    a: "先免費建立商家帳號，再依營運需求選擇百工標準方案、AI 智慧商城完整版或免 POS 機智慧點餐方案，完成正式簽約與啟用後即可使用對應功能。",
  },
  {
    q: "目前有哪些商家方案？",
    a: "目前提供 NT$18,000 百工標準方案、NT$45,000 AI 智慧商城完整版，以及 NT$24,000／24 個月的免 POS 機智慧點餐方案；實際內容與契約條件以伺服器正式方案目錄及簽署文件為準。",
  },
  {
    q: "如何取得商業登記或專業證照標章？",
    a: "已啟用適用商家方案的商家可在商家後台上傳證明文件，平台管理員審核通過後會顯示對應認證。",
  },
  {
    q: "商家推廣上架後包含哪些合作功能？",
    a: "包含合作需求、收到提案、我的提案、詢價、報價、商家訂單、私訊、評價與數據分析等既有功能。",
  },
];

export const pageDirectory = [
  ["首頁", "/"],
  ["所有行業分類", "/categories"],
  ["商家搜尋結果", "/search"],
  ["商家公開網站", "/business/qiang-ge-aquarium"],
  ["商家列表", "/businesses"],
  ["合作需求廣場", "/collaborations"],
  ["合作需求詳情", "/collaborations/1"],
  ["發布合作需求", "/collaborations/new"],
  ["商品服務市集", "/marketplace"],
  ["商品詳情", "/marketplace/service-1"],
  ["詢價單", "/inquiry-cart"],
  ["登入頁", "/login"],
  ["註冊頁", "/register"],
  ["忘記密碼", "/forgot-password"],
  ["商家後台", "/dashboard"],
  ["我的網站編輯器", "/dashboard/site-editor"],
  ["商品管理", "/dashboard/products"],
  ["合作需求管理", "/dashboard/collaborations"],
  ["私訊中心", "/messages"],
  ["通知中心", "/notifications"],
  ["方案與價格", "/pricing"],
  ["關於平台", "/about"],
  ["如何運作", "/how-it-works"],
  ["成功案例", "/success-stories"],
  ["常見問題", "/faq"],
  ["聯絡我們", "/contact"],
  ["隱私權政策", "/privacy"],
  ["使用條款", "/terms"],
  ["檢舉頁面", "/report"],
  ["404 頁面", "/not-found-demo"],
  ["管理員後台", "/admin"],
];
